ACDOCA = I_GLACCOUNTLINEITEMRAWDATA
ACCAS = ACCOUNTASSIGNMENT
ZEKKN = ACCOUNTASSIGNMENTNUMBER
ACCASTY = ACCOUNTASSIGNMENTTYPE
USNAM = ACCOUNTINGDOCCREATEDBYUSER
BELNR = ACCOUNTINGDOCUMENT
BSTAT = ACCOUNTINGDOCUMENTCATEGORY
BUZEI = ACCOUNTINGDOCUMENTITEM
BLART = ACCOUNTINGDOCUMENTTYPE
ACCTG_NOTIF_UUID = ACCOUNTINGNOTIFICATIONUUID
ACRITMTYPE = ACCRUALITEMTYPE
ACROBJ_ID = ACCRUALOBJECT
ACRLOGSYS = ACCRUALOBJECTLOGICALSYSTEM
ACROBJTYPE = ACCRUALOBJECTTYPE
ACRREFOBJ_ID = ACCRUALREFERENCEOBJECT
ACRSOBJ_ID = ACCRUALSUBOBJECT
ACRVALDAT = ACCRUALVALUEDATE
QUANT1 = ADDITIONALQUANTITY1
QUNIT1 = ADDITIONALQUANTITY1UNIT
QUANT2 = ADDITIONALQUANTITY2
QUNIT2 = ADDITIONALQUANTITY2UNIT
QUANT3 = ADDITIONALQUANTITY3
QUNIT3 = ADDITIONALQUANTITY3UNIT
LOKKT = ALTERNATIVEGLACCOUNT
TSL = AMOUNTINBALANCETRANSACCRCY
HSL = AMOUNTINCOMPANYCODECURRENCY
OSL = AMOUNTINFREEDEFINEDCURRENCY1
VSL = AMOUNTINFREEDEFINEDCURRENCY2
BSL = AMOUNTINFREEDEFINEDCURRENCY3
CSL = AMOUNTINFREEDEFINEDCURRENCY4
DSL = AMOUNTINFREEDEFINEDCURRENCY5
ESL = AMOUNTINFREEDEFINEDCURRENCY6
FSL = AMOUNTINFREEDEFINEDCURRENCY7
GSL = AMOUNTINFREEDEFINEDCURRENCY8
FCSL = AMOUNTINFUNCTIONALCURRENCY
KSL = AMOUNTINGLOBALCURRENCY
GM_OSL = AMOUNTINGRANTCURRENCY
CO_OSL = AMOUNTINOBJECTCURRENCY
WSL = AMOUNTINTRANSACTIONCURRENCY
ISTRU = ASSEMBLY
MOVCAT = ASSETACCTTRANSCLASSFCTN
ANLKL = ASSETCLASS
AFABE = ASSETDEPRECIATIONAREA
ANBWA = ASSETTRANSACTIONTYPE
BZDAT = ASSETVALUEDATE
ZUONR = ASSIGNMENTREFERENCE
RTCUR = BALANCETRANSACTIONCURRENCY
RUNIT = BASEUNIT
BEMOT = BILLABLECONTROL
FKART = BILLINGDOCUMENTTYPE
KUNRE = BILLTOPARTY
RBUDGET_PD = BUDGETPERIOD
RBUSA = BUSINESSAREA
PRZNR = BUSINESSPROCESS
SOLUTION_ORDER_ID = BUSINESSSOLUTIONORDER
SOLUTION_ORDER_ITEM_ID = BUSINESSSOLUTIONORDERITEM
BTTYPE = BUSINESSTRANSACTIONCATEGORY
CBTTYPE = BUSINESSTRANSACTIONTYPE
RE_ACCOUNT = CASHLEDGERACCOUNT
RE_BUKRS = CASHLEDGERCOMPANYCODE
KTOPL = CHARTOFACCOUNTS
AUGBL = CLEARINGACCOUNTINGDOCUMENT
AUGDT = CLEARINGDATE
AUGGJ = CLEARINGDOCFISCALYEAR
AUGBL = CLEARINGJOURNALENTRY
AUGGJ = CLEARINGJOURNALENTRYFISCALYEAR
RITEM = CNSLDTNFINANCIALSTATEMENTITEM
SUBIT = CNSLDTNSUBITEM
SITYP = CNSLDTNSUBITEMCATEGORY
FIPEX = COMMITMENTITEM
RCOMP = COMPANY
RBUKRS = COMPANYCODE
RHCUR = COMPANYCODECURRENCY
COCO_NUM = CONDITIONCONTRACT
RITCLG = CONSOLIDATIONCHARTOFACCOUNTS
RBUNIT = CONSOLIDATIONUNIT
KOKRS = CONTROLLINGAREA
VRGNG = CONTROLLINGBUSTRANSACTYPE
CO_BELKZ = CONTROLLINGDEBITCREDITCODE
CO_BUZEI = CONTROLLINGDOCUMENTITEM
OBJNR = CONTROLLINGOBJECT
SCOPE = CONTROLLINGOBJECTCLASS
RCO_OCUR = CONTROLLINGOBJECTCURRENCY
BELTP = CONTROLLINGOBJECTDEBITTYPE
RSRCE = COSTANALYSISRESOURCE
RCNTR = COSTCENTER
LSTAR = COSTCTRACTIVITYTYPE
KALNR = COSTESTIMATE
KSTRG = COSTOBJECT
HKGRP = COSTORIGINGROUP
RVUNIT = COSTSOURCEUNIT
KTOP2 = COUNTRYCHARTOFACCOUNTS
TIMESTAMP = CREATIONDATETIME
RISK_CLASS = CREDITRISKCLASS
KUNNR = CUSTOMER
KDGRP = CUSTOMERGROUP
QMNUM = CUSTOMERSERVICENOTIFICATION
KONZS = CUSTOMERSUPPLIERCORPORATEGROUP
LAND1 = CUSTOMERSUPPLIERCOUNTRY
BRSCH = CUSTOMERSUPPLIERINDUSTRY
CBRACCT = CUTBACKACCOUNT
CBOBJNR = CUTBACKCOSTOBJECT
CBRUNID = CUTBACKRUN
DRCRK = DEBITCREDITCODE
DEPR_PERIOD = DEPRECIATIONFISCALPERIOD
VTWEG = DISTRIBUTIONCHANNEL
BLDAT = DOCUMENTDATE
SGTXT = DOCUMENTITEMTEXT
KBLNR = EARMARKEDFUNDSDOCUMENT
KBLPOS = EARMARKEDFUNDSDOCUMENTITEM
EPRCTR = ELIMINATIONPROFITCENTER
EQUNR = EQUIPMENT
WWERT = EXCHANGERATEDATE
KOART = FINANCIALACCOUNTTYPE
CLOSINGSTEP = FINANCIALCLOSINGSTEP
DATASOURCE_ID = FINANCIALDATASOURCE
FIKRS = FINANCIALMANAGEMENTAREA
BRANCH_ID = FINANCIALSERVICESBRANCH
FS_PRODUCT_GROUP = FINANCIALSERVICESPRODUCTGROUP
RMVCT = FINANCIALTRANSACTIONTYPE
VALOBJ_ID = FINANCIALVALUATIONOBJECT
VALOBJTYPE = FINANCIALVALUATIONOBJECTTYPE
VALSOBJ_ID = FINANCIALVALUATIONSUBOBJECT
POPER = FISCALPERIOD
GJAHR = FISCALYEAR
FISCYEARPER = FISCALYEARPERIOD
PERIV = FISCALYEARVARIANT
KFSL = FIXEDAMOUNTINGLOBALCRCY
ANLN2 = FIXEDASSET
PFSL = FIXEDPRICEVARCINGLOBALCRCY
MFSL = FIXEDQUANTITY
REBZT = FOLLOWONDOCUMENTTYPE
ROCUR = FREEDEFINEDCURRENCY1
RVCUR = FREEDEFINEDCURRENCY2
RBCUR = FREEDEFINEDCURRENCY3
RCCUR = FREEDEFINEDCURRENCY4
RDCUR = FREEDEFINEDCURRENCY5
RECUR = FREEDEFINEDCURRENCY6
RFCUR = FREEDEFINEDCURRENCY7
RGCUR = FREEDEFINEDCURRENCY8
RFAREA = FUNCTIONALAREA
RFCCUR = FUNCTIONALCURRENCY
TPLNR = FUNCTIONALLOCATION
RFUND = FUND
MEASURE = FUNDEDPROGRAM
FISTL = FUNDSCENTER
AGING_INCRMNT = GENERALLEDGERAGINGINCREMENT
AGING = GENERALLEDGERAGINGSCOPE
RACCT = GLACCOUNT
GLACCOUNT_TYPE = GLACCOUNTTYPE
VORGN = GLBUSINESSTRANSACTIONTYPE
RKCUR = GLOBALCURRENCY
RRCTY = GLRECORDTYPE
RGM_OCUR = GRANTCURRENCY
RGRANT_NBR = GRANTID
ANLGR2 = GROUPFIXEDASSET
ANLGR = GROUPMASTERFIXEDASSET
KFSL2 = GRPVALNFIXEDAMTINGLOBCRCY
PFSL2 = GRPVALNFIXEDPRCVARCINGLOBCRCY
PSL2 = GRPVALNTOTPRCVARCINGLOBCRCY
RBDGT_VLDTY_NBR = GTEEMBUDGETVALIDITYNUMBER
HBKID = HOUSEBANK
HKTID = HOUSEBANKACCOUNT
CO_MEFBTR = INCMPLTSUMMABLEVALNFXDQTY
CO_MEGBTR = INCMPLTSUMMABLEVALNQTY
CO_MEINH = INCMPLTSUMMABLEVALNQTYUNT
MAT_KDPOS = INVENTORYSPCLSTKSALESDOCITM
MAT_KDAUF = INVENTORYSPCLSTKSALESDOCUMENT
MAT_PS_POSID = INVENTORYSPCLSTOCKWBSELEMENT
MAT_LIFNR = INVENTORYSPECIALSTOCKSUPPLIER
SOBKZ = INVENTORYSPECIALSTOCKTYPE
KZBWS = INVENTORYSPECIALSTOCKVALNTYPE
BWTAR = INVENTORYVALUATIONTYPE
REBZZ = INVOICEITEMREFERENCE
REBZG = INVOICEREFERENCE
REBZJ = INVOICEREFERENCEFISCALYEAR
MAT_PSPNR = INVTRYSPCLSTOCKWBSELMNTINTID
XCOMMITMENT = ISCOMMITMENT
XOPVW = ISOPENITEMMANAGED
XREVERSING = ISREVERSAL
XREVERSED = ISREVERSED
XSETTLED = ISSETTLED
XSETTLING = ISSETTLEMENT
XOBEW = ISSUPPLIERSTOCKVALUATION
XSPLITMOD = ITEMISSPLIT
VNAME = JOINTVENTURE
JVACTIVITY = JOINTVENTUREACCOUNTINGACTIVITY
BILLM = JOINTVENTUREBILLINGDATE
BTYPE = JOINTVENTUREBILLINGTYPE
RECID = JOINTVENTURECOSTRECOVERYCODE
EGRUP = JOINTVENTUREEQUITYGROUP
ETYPE = JOINTVENTUREEQUITYTYPE
POM = JOINTVENTUREOPERATIONALDATE
VPTNR = JOINTVENTUREPARTNER
PRODPER = JOINTVENTUREPRODUCTIONDATE
XSECONDARY = JOURNALENTRYISSECONDARYENTRY
LINETYPE = JOURNALENTRYITEMCATEGORY
DOCNR_LD = JRNLENTRALTVFYCONSECUTIVEID
MIG_SOURCE = JRNLENTRYITEMMIGRATIONSOURCE
OBS_REASON = JRNLENTRYITEMOBSOLETEREASON
CLOSING_RUN_ID = JRNLPERIODENDCLOSINGRUNLOGUUID
RYEAR = LEDGERFISCALYEAR
DOCLN = LEDGERGLLINEITEM
ERLKZ = LINEITEMISCOMPLETED
AWSYS = LOGICALSYSTEM
ILART = MAINTENANCEACTIVITYTYPE
PLANNED_PARTS_WORK = MAINTENANCEORDERISPLANNED
PLKNZ = MAINTENANCEORDERPLANNINGCODE
PRIOK = MAINTPRIORITY
ARTPR = MAINTPRIORITYTYPE
RCLNT = MANDT
ANLN1 = MASTERFIXEDASSET
MLCATEG = MATERIALLEDGERCATEGORY
MLPTYP = MATERIALLEDGERPROCESSTYPE
NETDT = NETDUEDATE
GKONT = OFFSETTINGACCOUNT
GKOAR = OFFSETTINGACCOUNTTYPE
ERKRS = OPERATINGCONCERN
AUTYP = ORDERCATEGORY
AUFNR = ORDERID
AUFPS = ORDERITEM
VORNR = ORDEROPERATION
UVORN = ORDERSUBOPERATION
ORGL_CHANGE = ORGANIZATIONALCHANGE
SPART = ORGANIZATIONDIVISION
UKOSTL = ORIGINCOSTCENTER
ULSTAR = ORIGINCOSTCTRACTIVITYTYPE
CO_BEKNZ = ORIGINCTRLGDEBITCREDITCODE
RHOART = ORIGINOBJECTTYPE
AUFNR_ORG = ORIGINORDER
VORNR_ORG = ORIGINORDEROPERATION
UMATNR = ORIGINPRODUCT
UPRCTR = ORIGINPROFITCENTER
USPOB = ORIGINSENDEROBJECT
PACCAS = PARTNERACCOUNTASSIGNMENT
PACCASTY = PARTNERACCOUNTASSIGNMENTTYPE
SBUDGET_PD = PARTNERBUDGETPERIOD
SBUSA = PARTNERBUSINESSAREA
PPRZNR = PARTNERBUSINESSPROCESS
RASSC = PARTNERCOMPANY
PBUKRS = PARTNERCOMPANYCODE
RBUPTR = PARTNERCONSOLIDATIONUNIT
PSCOPE = PARTNERCONTROLLINGOBJECTCLASS
SCNTR = PARTNERCOSTCENTER
PLSTAR = PARTNERCOSTCTRACTIVITYTYPE
PKSTRG = PARTNERCOSTOBJECT
PEGRUP = PARTNEREQUITYGROUP
PANL2 = PARTNERFIXEDASSET
SFAREA = PARTNERFUNCTIONALAREA
SFUND = PARTNERFUND
SGRANT_NBR = PARTNERGRANT
PANL1 = PARTNERMASTERFIXEDASSET
PAUFNR = PARTNERORDER
PAUTYP = PARTNERORDERCATEGORY
PAUFPS = PARTNERORDERITEM
PPRCTR = PARTNERPROFITCENTER
PPS_PSPID = PARTNERPROJECT
PPS_PRJ_PNR = PARTNERPROJECTINTERNALID
PNPLNR = PARTNERPROJECTNETWORK
PNPLNR_VORGN = PARTNERPROJECTNETWORKACTIVITY
PKDAUF = PARTNERSALESDOCUMENT
PKDPOS = PARTNERSALESDOCUMENTITEM
PSEGMENT = PARTNERSEGMENT
PSERVICE_DOC_ID = PARTNERSERVICEDOCUMENT
PSERVICE_DOC_ITEM_ID = PARTNERSERVICEDOCUMENTITEM
PSERVICE_DOC_TYPE = PARTNERSERVICEDOCUMENTTYPE
PDABRZ = PARTNERSETTLEMENTREFERENCEDATE
PVNAME = PARTNERVENTURE
PPS_POSID = PARTNERWBSELEMENT
PPS_PSP_PNR = PARTNERWBSELEMENTINTERNALID
RA_POB_ID = PERFORMANCEOBLIGATION
PEROP_END = PERFORMANCEPERIODENDDATE
PEROP_BEG = PERFORMANCEPERIODSTARTDATE
PERNR = PERSONNELNUMBER
WERKS = PLANT
BUDAT = POSTINGDATE
BSCHL = POSTINGKEY
PREC_BUKRS = PRDCSSRJOURNALENTRYCOMPANYCODE
PREC_GJAHR = PRDCSSRJOURNALENTRYFISCALYEAR
PREC_BELNR = PREDECESSORJOURNALENTRY
PREC_DOCLN = PREDECESSORJOURNALENTRYITEM
PREC_AWORG = PREDECESSORREFERENCEDOCCNTXT
PREC_AWITEM = PREDECESSORREFERENCEDOCITEM
PREC_AWTYP = PREDECESSORREFERENCEDOCTYPE
PREC_AWREF = PREDECESSORREFERENCEDOCUMENT
KFSL3 = PRFTCTRVALNFXDAMTINGLOBCRCY
PFSL3 = PRFTCTRVALNFXDPRCVARCINGLBCRCY
PSL3 = PRFTCTRVALNTOTPRCVARCINGLBCRCY
MATNR = PRODUCT
MATKL_MM = PRODUCTGROUP
VPRSV = PRODUCTPRICECONTROL
PRCTR = PROFITCENTER
PS_PSPID = PROJECT
PS_PRJ_PNR = PROJECTINTERNALID
NPLNR = PROJECTNETWORK
VTKEY = PROVIDERCONTRACT
VTPOS = PROVIDERCONTRACTITEM
BDGT_ACCOUNT = PUBSECBUDGETACCOUNT
BDGT_ACCOUNT_COCODE = PUBSECBUDGETACCOUNTCOCODE
BDGT_CNSMPN_AMOUNT_TYPE = PUBSECBUDGETCNSMPNAMTTYPE
BDGT_CNSMPN_DATE = PUBSECBUDGETCNSMPNDATE
BDGT_CNSMPN_PERIOD = PUBSECBUDGETCNSMPNFSCLPERIOD
BDGT_CNSMPN_YEAR = PUBSECBUDGETCNSMPNFSCLYEAR
BDGT_CNSMPN_TYPE = PUBSECBUDGETCNSMPNTYPE
BDGT_RELEVANT = PUBSECBUDGETISRELEVANT
EBELN = PURCHASINGDOCUMENT
EBELP = PURCHASINGDOCUMENTITEM
MSL = QUANTITY
MUVFLG = QUANTITYISINCOMPLETE
SGENR = REALESTATEBUILDING
RECNNR = REALESTATECONTRACT
PSGENR = REALESTATEPARTNERBUILDING
PRECNNR = REALESTATEPARTNERCONTRACT
PSGRNR = REALESTATEPARTNERPROPERTY
SGRNR = REALESTATEPROPERTY
SWENR = REBUSINESSENTITY
AWREF = REFERENCEDOCUMENT
AWORG = REFERENCEDOCUMENTCONTEXT
AWITEM = REFERENCEDOCUMENTITEM
AWITGRP = REFERENCEDOCUMENTITEMGROUP
AWTYP = REFERENCEDOCUMENTTYPE
RBEST = REFERENCEPURCHASEORDERCATEGORY
RMSL = REFERENCEQUANTITY
RRUNIT = REFERENCEQUANTITYUNIT
NPLNR_VORGN = RELATEDNETWORKACTIVITY
PSWENR = REPARTNERBUSINESSENTITY
PSMENR = REPARTNERRENTALOBJECT
PSNKSL = REPARTNERSERVICECHARGEKEY
PSEMPSL = REPARTNERSETTLEMENTUNITID
SMENR = RERENTALOBJECT
SNKSL = RESERVICECHARGEKEY
SEMPSL = RESETTLEMENTUNITID
RA_CONTRACT_ID = REVENUEACCOUNTINGCONTRACT
AWREF_REV = REVERSALREFERENCEDOCUMENT
AWORG_REV = REVERSALREFERENCEDOCUMENTCNTXT
AWTYP_REV = REVERSALREFERENCEDOCUMENTTYPE
SUBTA_REV = REVERSALTRANSACTIONSUBITEM
BZIRK = SALESDISTRICT
KDAUF = SALESDOCUMENT
KDPOS = SALESDOCUMENTITEM
VKORG = SALESORGANIZATION
SEGMENT = SEGMENT
ACCAS_SENDER = SENDERACCOUNTASSIGNMENT
ACCASTY_SENDER = SENDERACCOUNTASSIGNMENTTYPE
BUKRS_SENDER = SENDERCOMPANYCODE
S_RECIND = SENDERCOSTRECOVERYCODE
RACCT_SENDER = SENDERGLACCOUNT
SERVICE_CONTRACT_ID = SERVICECONTRACT
SERVICE_CONTRACT_ITEM_ID = SERVICECONTRACTITEM
SERVICE_CONTRACT_TYPE = SERVICECONTRACTTYPE
SERVICE_DOC_ID = SERVICEDOCUMENT
SERVICE_DOC_ITEM_ID = SERVICEDOCUMENTITEM
SERVICE_DOC_TYPE = SERVICEDOCUMENTTYPE
FBUDA = SERVICESRENDEREDDATE
DABRZ = SETTLEMENTREFERENCEDATE
KUNWE = SHIPTOPARTY
HVKWRT = SLSPRICEAMOUNTINCOCODECRCY
MATNR_COPA = SOLDPRODUCT
MATKL = SOLDPRODUCTGROUP
RLDNR = SOURCELEDGER
SRC_AWSYS = SOURCELOGICALSYSTEM
SRC_AWSUBIT = SOURCEREFERENCEDOCSUBITEM
SRC_AWREF = SOURCEREFERENCEDOCUMENT
SRC_AWORG = SOURCEREFERENCEDOCUMENTCNTXT
SRC_AWITEM = SOURCEREFERENCEDOCUMENTITEM
SRC_AWTYP = SOURCEREFERENCEDOCUMENTTYPE
UMSKZ = SPECIALGLCODE
RSPONSORED_CLASS = SPONSOREDCLASS
RSPONSORED_PROG = SPONSOREDPROGRAM
CO_ACCASTY_N1 = STSTCLACCOUNTASSIGNMENTTYPE1
CO_ACCASTY_N2 = STSTCLACCOUNTASSIGNMENTTYPE2
CO_ACCASTY_N3 = STSTCLACCOUNTASSIGNMENTTYPE3
SLALITTYPE = SUBLEDGERACCTLINEITEMTYPE
MAUFNR = SUPERIORORDER
LIFNR = SUPPLIER
MWSKZ = TAXCODE
TAX_COUNTRY = TAXCOUNTRY
OVERTIMECAT = TIMESHEETOVERTIMECATEGORY
PSL = TOTALPRICEVARCINGLOBALCRCY
RWCUR = TRANSACTIONCURRENCY
SUBTA = TRANSACTIONSUBITEM
KTOSL = TRANSACTIONTYPEDETERMINATION
BWKEY = VALUATIONAREA
VMFSL = VALUATIONFIXEDQUANTITY
VMSL = VALUATIONQUANTITY
VALUT = VALUEDATE
VARC_UACCT = VARIANCEORIGINGLACCOUNT
VARC_HKGRP = VARIANCEORIGINGROUP
PS_POSID = WBSELEMENT
PS_PSP_PNR = WBSELEMENTINTERNALID
ARBID = WORKCENTERINTERNALID
WORK_ITEM_ID = WORKITEM
PS_POSID = WORKPACKAGE
