AFKO = I_MANUFACTURINGORDER
KLVARI = ACTUALCOSTSCOSTINGVARIANT
TERKZ = BASICSCHEDULINGTYPE
STLNR = BILLOFMATERIAL
STLTY = BILLOFMATERIALCATEGORY
STLNR = BILLOFMATERIALINTERNALID
STLAL = BILLOFMATERIALVARIANT
STLAN = BILLOFMATERIALVARIANTUSAGE
BOM_VERSN = BILLOFMATERIALVERSION
PLNNR = BILLOFOPERATIONS
PLNAW = BILLOFOPERATIONSAPPLICATION
PLNNR = BILLOFOPERATIONSGROUP
PLNBEZ = BILLOFOPERATIONSMATERIAL
PLNTY = BILLOFOPERATIONSTYPE
PVERW = BILLOFOPERATIONSUSAGE
PLNAL = BILLOFOPERATIONSVARIANT
TL_VERSN = BILLOFOPERATIONSVERSION
AUFLD = BOMEXPLOSIONDATE
SDATV = BOMVALIDITYSTARTDATE
PLAUF = BOOEXPLOSIONDATE
ZAEHL = BOOINTERNALVERSIONCOUNTER
PDATV = BOOVALIDITYSTARTDATE
KAPVERSA = CAPACITYACTIVEVERSION
BEDID = CAPACITYREQUIREMENT
KBED = CAPACITYRQMTHASNOTTOBECREATED
AENNR = CHANGENUMBER
EXTENDED_QUALITY_CHECKS = EXTDQUALITYCHECKISREQUIRED
SICHZ = FLOATAFTERPRODUCTIONINWORKDAYS
VORGZ = FLOATBEFOREPRODUCTIONINWRKDAYS
TRKZP = FORECASTSCHEDULINGTYPE
PRUEFLOS = INSPECTIONLOT
LEAD_AUFNR = LEADINGORDER
APRIO = MANUFACTURINGORDERIMPORTANCE
FSH_MPROD_ORD = MASTERPRODUCTIONORDER
REVLV = MATERIALREVISIONLEVEL
REVLV = MATERIALREVISIONLEVEL_2
GLTRI = MFGORDERACTUALENDDATE
FTRMI = MFGORDERACTUALRELEASEDATE
GSTRI = MFGORDERACTUALSTARTDATE
GSUZI = MFGORDERACTUALSTARTTIME
RUECK = MFGORDERCONFIRMATION
GETRI = MFGORDERCONFIRMEDENDDATE
GEUZI = MFGORDERCONFIRMEDENDTIME
RMNGA = MFGORDERCONFIRMEDREWORKQTY
IASMG = MFGORDERCONFIRMEDSCRAPQTY
IGMNG = MFGORDERCONFIRMEDYIELDQTY
STUFE = MFGORDERHIERARCHYLEVEL
AUFPL = MFGORDERINTERNALID
PRODNET = MFGORDERISPARTOFCOLLVORDER
GLTRP = MFGORDERPLANNEDENDDATE
GLUZP = MFGORDERPLANNEDENDTIME
GASMG = MFGORDERPLANNEDSCRAPQTY
GSTRP = MFGORDERPLANNEDSTARTDATE
GSUZP = MFGORDERPLANNEDSTARTTIME
GAMNG = MFGORDERPLANNEDTOTALQTY
GLTRS = MFGORDERSCHEDULEDENDDATE
GLUZS = MFGORDERSCHEDULEDENDTIME
FTRMS = MFGORDERSCHEDULEDRELEASEDATE
GSTRS = MFGORDERSCHEDULEDSTARTDATE
GSUZS = MFGORDERSCHEDULEDSTARTTIME
SPLSTAT = MFGORDERSPLITSTATUS
DISPO = MRPCONTROLLER
RMZHL = NUMBEROFMFGORDERCONFIRMATIONS
NAUCOST = ORDERISNOTCOSTEDAUTOMATICALLY
CY_SEQNR = ORDERSEQUENCENUMBER
NAUTERM = ORDISNOTSCHEDLDAUTOMATICALLY
KLVARP = PLANNEDCOSTSCOSTINGVARIANT
FLEXIBLE_PROCESSING = PRODNPROCGISFLEXIBLE
SFCPF = PRODUCTIONSCHEDULINGPROFILE
FEVOR = PRODUCTIONSUPERVISOR
GMEIN = PRODUCTIONUNIT
FREIZ = RELEASEPERIODINWORKDAYS
RSNUM = RESERVATION
PLGRP = RESPONSIBLEPLANNERGROUP
FHORI = SCHEDULINGFLOATPROFILE
ARSNR = SETTLEMENTRESERVATION
MAUFNR = SUPERIORORDER
