AFPO = I_MANUFACTURINGORDERITEM
KNTTP = ACCOUNTASSIGNMENTCATEGORY
MEINS = BASEUNIT
CHARG = BATCH
GSBER = BUSINESSAREA
KZVBR = CONSUMPTIONPOSTING
KRSNR = COPRODUCTRESERVATION
KRSPS = COPRODUCTRESERVATIONITEM
WEWRT = GOODSRECEIPTAMOUNTINCOCODECRCY
WEPOS = GOODSRECEIPTISEXPECTED
WEUNB = GOODSRECEIPTISNONVALUATED
WEMPF = GOODSRECIPIENTNAME
SOBKZ = INVENTORYSPECIALSTOCKTYPE
KZBWS = INVENTORYSPECIALSTOCKVALNTYPE
INSMK = INVENTORYUSABILITYCODE
BWTTY = INVENTORYVALUATIONCATEGORY
BWTAR = INVENTORYVALUATIONTYPE
ELIKZ = ISCOMPLETELYDELIVERED
XLOEK = ISMARKEDFORDELETION
MANDT = MANDT
AUFNR = MANUFACTURINGORDER
DAUTY = MANUFACTURINGORDERCATEGORY
POSNR = MANUFACTURINGORDERITEM
DAUAT = MANUFACTURINGORDERTYPE
MATNR = MATERIAL
WEBAZ = MATERIALGOODSRECEIPTDURATION
BESKZ = MATERIALPROCUREMENTCATEGORY
PSOBS = MATERIALPROCUREMENTTYPE
LTRMI = MFGORDERITEMACTUALDELIVERYDATE
IAMNG = MFGORDERITEMACTUALDEVIATIONQTY
WEMNG = MFGORDERITEMGOODSRECEIPTQTY
DGLTP = MFGORDERITEMPLANNEDENDDATE
PSAMG = MFGORDERITEMPLANNEDSCRAPQTY
PSMNG = MFGORDERITEMPLANNEDTOTALQTY
LTRMP = MFGORDERITEMPLNDDELIVERYDATE
KBNKZ = MFGORDERITEMREPLNMTELMNTTYPE
DGLTS = MFGORDERITEMSCHEDULEDENDDATE
GSBTR = MFGORDERITEMTOTALCMTMTDATE
BERID = MRPAREA
ANZSN = NUMBEROFSERIALNUMBERS
OBJNP = OBJECTINTERNALID
DNREL = ORDERITEMISNOTRELEVANTFORMRP
UEBTO = OVERDELIVTOLRTDLMTRATIOINPCT
PLNUM = PLANNEDORDER
ETRMP = PLANNEDORDEROPENINGDATE
PWERK = PLANNINGPLANT
PAMNG = PLNDORDERPLANNEDSCRAPQTY
STRMP = PLNDORDERPLANNEDSTARTDATE
PGMNG = PLNDORDERPLANNEDTOTALQTY
MATNR = PRODUCT
FSH_COLLECTION = PRODUCTCOLLECTION
CUOBJ = PRODUCTCONFIGURATION
DWERK = PRODUCTIONPLANT
AMEIN = PRODUCTIONUNIT
VERID = PRODUCTIONVERSION
FSH_SEASON = PRODUCTSEASON
FSH_SEASON_YEAR = PRODUCTSEASONYEAR
FSH_THEME = PRODUCTTHEME
VERTO = QUANTITYDISTRIBUTIONKEY
QUNUM = QUOTAARRANGEMENT
QUPOS = QUOTAARRANGEMENTITEM
KDAUF = SALESORDER
KDPOS = SALESORDERITEM
KDEIN = SALESORDERSCHEDULELINE
SERNP = SERIALNUMBERASSGMTPROFILE
ARSNR = SETTLEMENTRESERVATION
ARSPS = SETTLEMENTRESERVATIONITEM
SGT_SCAT = STOCKSEGMENT
LGORT = STORAGELOCATION
UNTTO = UNDERDELIVTOLRTDLMTRATIOINPCT
UEBTK = UNLIMITEDOVERDELIVERYISALLOWED
ABLAD = UNLOADINGPOINTNAME
PROJN = WBSELEMENTINTERNALID
PROJN = WBSELEMENTINTERNALID_2
