AFRU = I_MFGORDERCONFIRMATION
PEDD = ACTUALFORECASTENDDATE
PEDZ = ACTUALFORECASTENDTIME
NO_GOODSMOVEMENT_VIA_API = APICONFHASNOGOODSMOVEMENTS
ZEIER = BREAKDURATIONUNIT
PRZ01 = BUSINESSPROCESS
IPRZ1 = BUSINESSPROCESSCONFIRMEDQTY
IPRE1 = BUSINESSPROCESSENTRYUNIT
OPRZ1 = BUSINESSPROCESSREMAININGQTY
OPRE1 = BUSINESSPROCREMAININGQTYUNIT
STZHL = CANCLDMFGORDERCONFCOUNT
KAPID = CAPACITYINTERNALID
SPLIT = CAPACITYREQUIREMENTSPLIT
ORIND = CONFIRMATIONAPPLICATIONORIGIN
EXERD = CONFIRMATIONEXTERNALENTRYDATE
EXERZ = CONFIRMATIONEXTERNALENTRYTIME
RMNGA = CONFIRMATIONREWORKQUANTITY
XMNGA = CONFIRMATIONSCRAPQUANTITY
LTXA1 = CONFIRMATIONTEXT
MEINH = CONFIRMATIONUNIT
LMNGA = CONFIRMATIONYIELDQUANTITY
ISERH = CONFIRMEDBREAKDURATION
IEDD = CONFIRMEDEXECUTIONENDDATE
IEDZ = CONFIRMEDEXECUTIONENDTIME
ISDD = CONFIRMEDEXECUTIONSTARTDATE
ISDZ = CONFIRMEDEXECUTIONSTARTTIME
IEBD = CONFIRMEDPROCESSINGENDDATE
IEBZ = CONFIRMEDPROCESSINGENDTIME
ISBD = CONFIRMEDPROCESSINGSTARTDATE
ISBZ = CONFIRMEDPROCESSINGSTARTTIME
IERD = CONFIRMEDSETUPENDDATE
IERZ = CONFIRMEDSETUPENDTIME
ISAD = CONFIRMEDTEARDOWNSTARTDATE
ISAZ = CONFIRMEDTEARDOWNSTARTTIME
GMNGA = CONFYIELDQTYINPRODUCTIONUNIT
QUALF = EMPLOYEESUITABILITY
LOGRP = EMPLOYEEWAGEGROUP
LOART = EMPLOYEEWAGETYPE
EXNAM = ENTEREDBYEXTERNALUSER
ERNAM = ENTEREDBYUSER
EXTID = EXTERNALSYSTEMCONFIRMATION
WEBLNR = FAILEDGOODSMOVEMENT
AUERU = FINALCONFIRMATIONTYPE
STOKZ = ISREVERSED
TXTSP = LANGUAGE
LAEDA = LASTCHANGEDATE
AENAM = LASTCHANGEDBYUSER
MANDT = MANDT
AUFNR = MANUFACTURINGORDER
VORNR = MANUFACTURINGORDEROPERATION
VORNR = MANUFACTURINGORDEROPERATION_2
APLFL = MANUFACTURINGORDERSEQUENCE
WABLNR = MATERIALDOCUMENT
RMZHL = MFGORDERCONFIRMATION
ERSDA = MFGORDERCONFIRMATIONENTRYDATE
ERZET = MFGORDERCONFIRMATIONENTRYTIME
RUECK = MFGORDERCONFIRMATIONGROUP
RMZHL_MST = MILESTONECONFIRMATION
RUECK_MST = MILESTONECONFIRMATIONGROUP
MEILR = MILESTONECONFIRMATIONTYPE
MEILR = MILESTONEISCONFIRMED
IPRK1 = NOFURTHERBUSINESSPROCQTYISEXPD
LEK01 = NOFURTHEROPWORKQUANTITY1ISEXPD
LEK02 = NOFURTHEROPWORKQUANTITY2ISEXPD
LEK03 = NOFURTHEROPWORKQUANTITY3ISEXPD
LEK04 = NOFURTHEROPWORKQUANTITY4ISEXPD
LEK05 = NOFURTHEROPWORKQUANTITY5ISEXPD
LEK06 = NOFURTHEROPWORKQUANTITY6ISEXPD
ANZMA = NUMBEROFEMPLOYEES
ISM01 = OPCONFIRMEDWORKQUANTITY1
ISM02 = OPCONFIRMEDWORKQUANTITY2
ISM03 = OPCONFIRMEDWORKQUANTITY3
ISM04 = OPCONFIRMEDWORKQUANTITY4
ISM05 = OPCONFIRMEDWORKQUANTITY5
ISM06 = OPCONFIRMEDWORKQUANTITY6
AUSOR = OPENRESERVATIONSISCLEARED
SMENG = OPPLANNEDTOTALQUANTITY
ILE01 = OPWORKQUANTITYUNIT1
ILE02 = OPWORKQUANTITYUNIT2
ILE03 = OPWORKQUANTITYUNIT3
ILE04 = OPWORKQUANTITYUNIT4
ILE05 = OPWORKQUANTITYUNIT5
ILE06 = OPWORKQUANTITYUNIT6
SATZA = ORDERCONFIRMATIONRECORDTYPE
MANUR = ORDERCONFIRMATIONTYPE
AUFPL = ORDERINTERNALID
APLZL = ORDEROPERATIONINTERNALID
PERNR = PERSONNEL
WERKS = PLANT
PDSNR = PLANTDATACOLLECTIONID
BUDAT = POSTINGDATE
GMEIN = PRODUCTIONUNIT
KAPTPROG = SHIFTDEFINITION
SCHGRUP = SHIFTGROUPING
SUMNR = SUPERIOROPERATIONINTERNALID
ZAUSW = TIMERECORDING
GRUND = VARIANCEREASONCODE
ARBID = WORKCENTERINTERNALID
