AFVV = I_MANUFACTURINGORDEROPERATION
ISTTY = BILLOFMATERIALCATEGORY
ISTNR = BILLOFMATERIALINTERNALID
ISTNR = BILLOFMATERIALINTERNALID_2
ISTKN = BILLOFMATERIALITEMNODENUMBER
PLNNR = BILLOFOPERATIONSGROUP
PLNFL = BILLOFOPERATIONSSEQUENCE
PLNTY = BILLOFOPERATIONSTYPE
PLNAL = BILLOFOPERATIONSVARIANT
TL_VERSN = BILLOFOPERATIONSVERSION
ISTPO = BOMITEMNODECOUNT
PLNKN = BOOOPERATIONINTERNALID
GSBER = BUSINESSAREA
PRZ01 = BUSINESSPROCESS
BEDID = CAPACITYREQUIREMENT
BEDZL = CAPACITYREQUIREMENTITEM
AENNR = CHANGENUMBER
BUKRS = COMPANYCODE
SCOPE = CONTROLLINGOBJECTCLASS
OWAER = CONTROLLINGOBJECTCURRENCY
PHSEQ = CONTROLRECIPEDESTINATION
LAR01 = COSTCTRACTIVITYTYPE1
LAR02 = COSTCTRACTIVITYTYPE2
LAR03 = COSTCTRACTIVITYTYPE3
LAR04 = COSTCTRACTIVITYTYPE4
LAR05 = COSTCTRACTIVITYTYPE5
LAR06 = COSTCTRACTIVITYTYPE6
SAKTO = COSTELEMENT
KALNR = COSTESTIMATE
KALSM = COSTINGSHEET
KLVAR = COSTINGVARIANT
QUALF = EMPLOYEESUITABILITY
LOGRP = EMPLOYEEWAGEGROUP
LOART = EMPLOYEEWAGETYPE
FRDLB = EXTPROCGOPERATIONHASSUBCONTRG
KALID = FACTORYCALENDAR
FUNC_AREA = FUNCTIONALAREA
WEMPF = GOODSRECIPIENTNAME
TXTSP = LANGUAGE
RSTRA = LEADTIMEREDUCTIONSTRATEGY
MANDT = MANDT
APLFL = MANUFACTURINGORDERSEQUENCE
MATKL = MATERIALGROUP
SPLIM = MAXIMUMNUMBEROFSPLITS
AUFPL = MFGORDERINTERNALID
PHFLG = MFGORDEROPERATIONISPHASE
VORNR = MFGORDEROPERATIONORSUBOP
VORNR = MFGORDEROPERATIONORSUBOP_2
LTXA1 = MFGORDEROPERATIONTEXT
VORNR = MFGORDERPHASESUPERIOROPERATION
LEK01 = NOFURTHEROPWORKQUANTITY1ISEXPD
LEK02 = NOFURTHEROPWORKQUANTITY2ISEXPD
LEK03 = NOFURTHEROPWORKQUANTITY3ISEXPD
LEK04 = NOFURTHEROPWORKQUANTITY4ISEXPD
LEK05 = NOFURTHEROPWORKQUANTITY5ISEXPD
LEK06 = NOFURTHEROPWORKQUANTITY6ISEXPD
ANZZL = NUMBEROFCAPACITIES
RSANZ = NUMBEROFCONFIRMATIONSLIPS
ANZMA = NUMBEROFEMPLOYEES
RMZHL = NUMBEROFOPERATIONCONFIRMATIONS
PEINH = NUMBEROFOPERATIONPRICEUNITS
LOANZ = NUMBEROFTIMETICKETS
OBJNR = OBJECTINTERNALID
RUECK = OPERATIONCONFIRMATION
STEUS = OPERATIONCONTROLPROFILE
NPRIO = OPERATIONIMPORTANCE
LOEKZ = OPERATIONISTOBEDELETED
UEKAN = OPERATIONOVERLAPPINGISPOSSIBLE
UEMUS = OPERATIONOVERLAPPINGISREQUIRED
AUFAK = OPERATIONSCRAPPERCENT
RFSCH = OPERATIONSETUPGROUP
RFGRP = OPERATIONSETUPGROUPCATEGORY
RASCH = OPERATIONSETUPTYPE
FLIES = OPERATIONSISALWAYSOVERLAPPING
SPMUS = OPERATIONSPLITISREQUIRED
KTSCH = OPERATIONSTANDARDTEXTCODE
BEDNR = OPERATIONTRACKINGNUMBER
WAERS = OPEXTERNALPROCESSINGCURRENCY
PREIS = OPEXTERNALPROCESSINGPRICE
RSTUF = OPSCHEDLDREDUCTIONLEVEL
PVZKN = ORDERINTBILLOFOPITEMOFPHASE
APLZL = ORDEROPERATIONINTERNALID
PERNR = PERSONNEL
WERKS = PLANT
OAN_INST_ID_PRODUCE = PRODUCEOPACTYNTWKINSTANCE
PRCTR = PROFITCENTER
EBELN = PURCHASEORDER
EBELP = PURCHASEORDERITEM
BANFN = PURCHASEREQUISITION
BNFPO = PURCHASEREQUISITIONITEM
EKGRP = PURCHASINGGROUP
INFNR = PURCHASINGINFORECORD
ESOKZ = PURCHASINGINFORECORDCATEGORY
EKORG = PURCHASINGORGANIZATION
KZFIX = PURGINFORECDDATAISFIXED
ANFKO = REQUESTINGCOSTCENTER
OAN_INST_ID_SETUP = SETUPOPACTYNTWKINSTANCE
VGWTS = STANDARDWORKFORMULAPARAMGROUP
SUMNR = SUPERIOROPERATIONINTERNALID
VORNR = SUPERIOROPERATION_2
LIFNR = SUPPLIER
TXJCD = TAXJURISDICTION
OAN_INST_ID_TEARDOWN = TEARDOWNOPACTYNTWKINSTANCE
ABLAD = UNLOADINGPOINTNAME
ARBID = WORKCENTERINTERNALID
