AFVV = I_MANUFACTURINGORDEROPERATION
USR06 = FREEDEFINEDAMOUNT1
USE06 = FREEDEFINEDAMOUNT1CURRENCY
USR07 = FREEDEFINEDAMOUNT2
USE07 = FREEDEFINEDAMOUNT2CURRENCY
USR00 = FREEDEFINEDATTRIBUTE01
USR01 = FREEDEFINEDATTRIBUTE02
USR02 = FREEDEFINEDATTRIBUTE03
USR03 = FREEDEFINEDATTRIBUTE04
USR08 = FREEDEFINEDDATE1
USR09 = FREEDEFINEDDATE2
USR10 = FREEDEFINEDINDICATOR1
USR11 = FREEDEFINEDINDICATOR2
USR04 = FREEDEFINEDQUANTITY1
USE04 = FREEDEFINEDQUANTITY1UNIT
USR05 = FREEDEFINEDQUANTITY2
USE05 = FREEDEFINEDQUANTITY2UNIT
SLWID = FREEDEFINEDTABLEFIELDSEMANTIC
