AFVV = I_MANUFACTURINGORDEROPERATION
PDAU = ACTUALFORECASTDURATION
PDAE = ACTUALFORECASTDURATIONUNIT
PEDD = ACTUALFORECASTENDDATE
PEDZ = ACTUALFORECASTENDTIME
ZEIER = BREAKDURATIONUNIT
IPRZ1 = BUSINESSPROCESSCONFIRMEDQTY
IPRE1 = BUSINESSPROCESSENTRYUNIT
OPRZ1 = BUSINESSPROCESSREMAININGQTY
OPRE1 = BUSINESSPROCREMAININGQTYUNIT
ISERH = CONFIRMEDBREAKDURATION
FSELD = EARLIESTSCHEDULEDWAITENDDATE
FSELZ = EARLIESTSCHEDULEDWAITENDTIME
FSSLD = EARLIESTSCHEDULEDWAITSTARTDATE
FSSLZ = EARLIESTSCHEDULEDWAITSTARTTIME
OFFSTE = ENDDATEOFFSETDURATION
EHOFFE = ENDDATEOFFSETDURATIONUNIT
BZOFFE = ENDDATEOFFSETREFERENCECODE
OFM01 = FORECASTWORKQUANTITY1
OFM02 = FORECASTWORKQUANTITY2
OFM03 = FORECASTWORKQUANTITY3
OFM04 = FORECASTWORKQUANTITY4
OFM05 = FORECASTWORKQUANTITY5
OFM06 = FORECASTWORKQUANTITY6
SPEDD = LATESTSCHEDLDFCSTDENDDATE
SPAVD = LATESTSCHEDLDFCSTDSTARTDATE
SSELD = LATESTSCHEDULEDWAITENDDATE
SSELZ = LATESTSCHEDULEDWAITENDTIME
SSSLD = LATESTSCHEDULEDWAITSTARTDATE
SSSLZ = LATESTSCHEDULEDWAITSTARTTIME
ZLMAX = MAXIMUMWAITDURATION
ZEILM = MAXIMUMWAITDURATIONUNIT
DAUMI = MINIMUMDURATION
DAUME = MINIMUMDURATIONUNIT
ZTMIN = MINIMUMMOVEDURATION
ZEITM = MINIMUMMOVEDURATIONUNIT
ZWMIN = MINIMUMQUEUEDURATION
ZEIWM = MINIMUMQUEUEDURATIONUNIT
ZLPRO = MINIMUMWAITDURATION
ZEILP = MINIMUMWAITDURATIONUNIT
IPRK1 = NOFURTHERBUSINESSPROCQTYISEXPD
IEDD = OPACTUALEXECUTIONENDDATE
IEDZ = OPACTUALEXECUTIONENDTIME
ISDD = OPACTUALEXECUTIONSTARTDATE
ISDZ = OPACTUALEXECUTIONSTARTTIME
IEBD = OPACTUALPROCESSINGENDDATE
IEBZ = OPACTUALPROCESSINGENDTIME
ISBD = OPACTUALPROCESSINGSTARTDATE
ISBZ = OPACTUALPROCESSINGSTARTTIME
IERD = OPACTUALSETUPENDDATE
IERZ = OPACTUALSETUPENDTIME
ISAD = OPACTUALTEARDOWNSTARTDATE
ISAZ = OPACTUALTEARDOWNSTARTTME
ISM01 = OPCONFIRMEDWORKQUANTITY1
ISM02 = OPCONFIRMEDWORKQUANTITY2
ISM03 = OPCONFIRMEDWORKQUANTITY3
ISM04 = OPCONFIRMEDWORKQUANTITY4
ISM05 = OPCONFIRMEDWORKQUANTITY5
ISM06 = OPCONFIRMEDWORKQUANTITY6
IEAVD = OPERATIONCONFIRMEDENDDATE
RMNGA = OPERATIONCONFIRMEDREWORKQTY
ISAVD = OPERATIONCONFIRMEDSTARTDATE
BMSCH = OPERATIONREFERENCEQUANTITY
DAUNO = OPERATIONSTANDARDDURATION
DAUNE = OPERATIONSTANDARDDURATIONUNIT
MEINH = OPERATIONUNIT
FSEDD = OPERLSTSCHEDLDEXECENDDTE
FSEDZ = OPERLSTSCHEDLDEXECENDTME
FSAVD = OPERLSTSCHEDLDEXECSTRTDTE
FSAVZ = OPERLSTSCHEDLDEXECSTRTTME
FSSBD = OPERLSTSCHEDLDPROCGSTRTDTE
FSSBZ = OPERLSTSCHEDLDPROCGSTRTTME
FSSAD = OPERLSTSCHEDLDTRDWNSTRTDTE
FSSAZ = OPERLSTSCHEDLDTRDWNSTRTTME
SSEDD = OPLTSTSCHEDLDEXECENDDTE
SSEDZ = OPLTSTSCHEDLDEXECENDTME
SSAVD = OPLTSTSCHEDLDEXECSTRTDTE
SSAVZ = OPLTSTSCHEDLDEXECSTRTTME
SSSBD = OPLTSTSCHEDLDPROCGSTRTDTE
SSSBZ = OPLTSTSCHEDLDPROCGSTRTTME
SSSAD = OPLTSTSCHEDLDTRDWNSTRTDTE
SSSAZ = OPLTSTSCHEDLDTRDWNSTRTTME
BEARZ = OPPLANNEDPROCESSINGDURN
BEAZE = OPPLANNEDPROCESSINGDURNUNIT
ASVRG = OPPLANNEDSCRAPQUANTITY
RUEST = OPPLANNEDSETUPDURN
RSTZE = OPPLANNEDSETUPDURNUNIT
ABRUE = OPPLANNEDTEARDOWNDURN
ARUZE = OPPLANNEDTEARDOWNDURNUNIT
MGVRG = OPPLANNEDTOTALQUANTITY
UMREN = OPQTYTOBASEQTYDNMNTR
UMREZ = OPQTYTOBASEQTYNMRTR
XMNGA = OPTOTALCONFIRMEDSCRAPQTY
LMNGA = OPTOTALCONFIRMEDYIELDQTY
GMNGA = OPTOTCONFDYIELDQTYINORDQTYUNIT
ILE01 = OPWORKQUANTITYUNIT1
ILE02 = OPWORKQUANTITYUNIT2
ILE03 = OPWORKQUANTITYUNIT3
ILE04 = OPWORKQUANTITYUNIT4
ILE05 = OPWORKQUANTITYUNIT5
ILE06 = OPWORKQUANTITYUNIT6
ZMINU = OVERLAPMINIMUMDURATION
ZEIMU = OVERLAPMINIMUMDURATIONUNIT
ZMERH = PLANNEDBREAKDURATION
PLIFZ = PLANNEDDELIVERYDURATION
FPEDD = SCHEDLDFCSTDEARLIESTENDDATE
FPEDZ = SCHEDLDFCSTDEARLIESTENDTIME
FPAVD = SCHEDLDFCSTDEARLIESTSTARTDATE
FPAVZ = SCHEDLDFCSTDEARLIESTSTARTTIME
SPEDZ = SCHEDLDFCSTDLATESTENDTIME
SPAVZ = SCHEDLDFCSTDLATESTSTARTTIME
TRANZ = SCHEDULEDMOVEDURATION
TRAZE = SCHEDULEDMOVEDURATIONUNIT
WARTZ = SCHEDULEDQUEUEDURATION
WRTZE = SCHEDULEDQUEUEDURATIONUNIT
LIEGZ = SCHEDULEDWAITDURATION
LIGZE = SCHEDULEDWAITDURATIONUNIT
ZTNOR = STANDARDMOVEDURATION
ZEITN = STANDARDMOVEDURATIONUNIT
ZWNOR = STANDARDQUEUEDURATION
ZEIWN = STANDARDQUEUEDURATIONUNIT
OFFSTB = STARTDATEOFFSETDURATION
EHOFFB = STARTDATEOFFSETDURATIONUNIT
BZOFFB = STARTDATEOFFSETREFERENCECODE
VGW01 = WORKCENTERSTANDARDWORKQTY1
VGW02 = WORKCENTERSTANDARDWORKQTY2
VGW03 = WORKCENTERSTANDARDWORKQTY3
VGW04 = WORKCENTERSTANDARDWORKQTY4
VGW05 = WORKCENTERSTANDARDWORKQTY5
VGW06 = WORKCENTERSTANDARDWORKQTY6
VGE01 = WORKCENTERSTANDARDWORKQTYUNIT1
VGE02 = WORKCENTERSTANDARDWORKQTYUNIT2
VGE03 = WORKCENTERSTANDARDWORKQTYUNIT3
VGE04 = WORKCENTERSTANDARDWORKQTYUNIT4
VGE05 = WORKCENTERSTANDARDWORKQTYUNIT5
VGE06 = WORKCENTERSTANDARDWORKQTYUNIT6
