AUFK = I_ORDER
BUKRS = COMPANYCODE
KOKRS = CONTROLLINGAREA
LOEKZ = ISMARKEDFORDELETION
ASTKZ = ISSTATISTICALORDER
MANDT = MANDT
OBJNR = OBJECTINTERNALID
AUTYP = ORDERCATEGORY
KTEXT = ORDERDESCRIPTION
AUFNR = ORDERID
AUART = ORDERTYPE
WERKS = PLANT
PRCTR = PROFITCENTER
