BNKA = I_BANK_2
ADRNR = ADDRESSID
BNKLZ = BANK
BRNCH = BANKBRANCH
BANKS = BANKCOUNTRY
VERS = BANKDATAFILEFORMAT
BANKL = BANKINTERNALID
BANKA = BANKNAME
BGRUP = BANKNETWORKGROUPING
BRNCH = BRANCH
CHKME = CHECKDIGITCALCULATIONMETHOD
ORT01 = CITYNAME
ERNAM = CREATEDBYUSER
ERDAT = CREATIONDATE
LOEVM = ISMARKEDFORDELETION
XPGRO = ISPOSTBANKACCOUNT
PSKTO = POSTOFFICEBANKACCOUNT
PROVZ = REGION
ORT01 = SHORTCITYNAME
STRAS = SHORTSTREETNAME
STRAS = STREETNAME
SWIFT = SWIFTCODE
