BSEC = I_ONETIMEACCOUNTCUSTOMER
INTAD = ACCOUNTINGCLERKINTERNETADDRESS
BELNR = ACCOUNTINGDOCUMENT
BUZEI = ACCOUNTINGDOCUMENTITEM
ADRNR = ADDRESSID
BEGRU = AUTHORIZATIONGROUP
NAME1 = BUSINESSPARTNERNAME1
NAME2 = BUSINESSPARTNERNAME2
NAME3 = BUSINESSPARTNERNAME3
NAME4 = BUSINESSPARTNERNAME4
ORT01 = CITYNAME
BUKRS = COMPANYCODE
LAND1 = COUNTRY
GJAHR = FISCALYEAR
STKZN = ISNATURALPERSON
MANDT = MANDT
PFACH = POBOX
PSTL2 = POBOXPOSTALCODE
PSTLZ = POSTALCODE
REGIO = REGION
STRAS = STREETADDRESSNAME
STCD1 = TAXID1
STCD2 = TAXID2
STCD3 = TAXID3
STCD4 = TAXID4
STCD5 = TAXID5
STCDT = TAXNUMBERTYPE
