BSED = I_BILLOFEXCHANGE
BELNR = ACCOUNTINGDOCUMENT
BUZEI = ACCOUNTINGDOCUMENTITEM
_DATAAGING = BILLOFEXCHANGEDATAAGINGDATE
WSTAT = BILLOFEXCHANGEDOCUMENTSTATUS
WBANK = BILLOFEXCHANGEDOMICILETEXT
WBZOG = BILLOFEXCHANGEDRAWEE
WORT2 = BILLOFEXCHANGEDRAWEECITYNAME
WNAME = BILLOFEXCHANGEDRAWER
WORT1 = BILLOFEXCHANGEDRAWERCITYNAME
XAKTZ = BILLOFEXCHANGEISACCEPTED
XSIWE = BILLOFEXCHANGEISONDEMAND
WGBKZ = BILLOFEXCHANGEISPROTESTED
WDATE = BILLOFEXCHANGEISSUEDATE
PORTF = BILLOFEXCHANGEPORTFOLIO
WEVWV = BILLOFEXCHANGEUSAGE
WVERD = BILLOFEXCHANGEUSAGEDATE
BUPLA = BUSINESSPLACE
SECCO = BUSINESSSECTIONCODE
BUKRS = COMPANYCODE
GJAHR = FISCALYEAR
WEVWV = PLANNEDBILLOFEXCHANGEUSAGE
REGIO = REGION
