BSEG_ADD = I_ADDLLEDGEROPLACCTGDOCITEM
BELNR = ACCOUNTINGDOCUMENT
BSTAT = ACCOUNTINGDOCUMENTCATEGORY
BUZEI = ACCOUNTINGDOCUMENTITEM
LOKKT = ALTERNATIVEGLACCOUNT
VERTN = ASSETCONTRACT
ANBWA = ASSETTRANSACTIONTYPE
ZUONR = ASSIGNMENTREFERENCE
PSWSL = BALANCETRANSACTIONCURRENCY
MEINS = BASEUNIT
WVERW = BILLOFEXCHANGEUSAGE
BUDGET_PD = BUDGETPERIOD
GSBER = BUSINESSAREA
BUPLA = BUSINESSPLACE
PRZNR = BUSINESSPROCESS
VBEWA = CASHFLOWTYPE
RE_ACCOUNT = CASHLEDGERACCOUNT
RE_BUKRS = CASHLEDGERCOMPANYCODE
AUGBL = CLEARINGACCOUNTINGDOCUMENT
AUGCP = CLEARINGCREATIONDATE
AUGDT = CLEARINGDATE
AUGGJ = CLEARINGDOCFISCALYEAR
XRAGL = CLEARINGISREVERSED
AGZEI = CLEARINGITEM
AUGBL = CLEARINGJOURNALENTRY
AUGGJ = CLEARINGJOURNALENTRYFISCALYEAR
FIPOS = COMMITMENTITEM
FIPOS = COMMITMENTITEMSHORTID
BUKRS = COMPANYCODE
KOKRS = CONTROLLINGAREA
ALTKT = CORPORATEGROUPACCOUNT
KOSTL = COSTCENTER
LSTAR = COSTCTRACTIVITYTYPE
KSTAR = COSTELEMENT
KSTRG = COSTOBJECT
SGTXT = DOCUMENTITEMTEXT
ZFBDT = DUECALCULATIONBASEDATE
KBLNR = EARMARKEDFUNDS
KBLNR = EARMARKEDFUNDSDOCUMENT
KBLPOS = EARMARKEDFUNDSDOCUMENTITEM
KBLPOS = EARMARKEDFUNDSITEM
KOART = FINANCIALACCOUNTTYPE
BEWAR = FINANCIALTRANSACTIONTYPE
GJAHR = FISCALYEAR
ANLN2 = FIXEDASSET
REBZT = FOLLOWONDOCUMENTTYPE
FKBER = FUNCTIONALAREA
RFCCUR = FUNCTIONALCURRENCY
GEBER = FUND
MEASURE = FUNDEDPROGRAM
FISTL = FUNDSCENTER
HKONT = GLACCOUNT
GRANT_NBR = GRANTID
BWTAR = INVENTORYVALUATIONTYPE
REBZZ = INVOICEITEMREFERENCE
REBZG = INVOICEREFERENCE
REBZJ = INVOICEREFERENCEFISCALYEAR
XAUTO = ISAUTOMATICALLYCREATED
XBILK = ISBALANCESHEETACCOUNT
XOPVW = ISOPENITEMMANAGED
VNAME = JOINTVENTURE
RECID = JOINTVENTURECOSTRECOVERYCODE
EGRUP = JOINTVENTUREEQUITYGROUP
MANDT = MANDT
ANLN1 = MASTERFIXEDASSET
MATNR = MATERIAL
NETDT = NETDUEDATE
GKONT = OFFSETTINGACCOUNT
GKART = OFFSETTINGACCOUNTTYPE
AUFNR = ORDERID
APLZL = ORDERINTBILLOFOPERATIONSITEM
AUFPL = ORDERINTERNALBILLOFOPERATIONS
PBUDGET_PD = PARTNERBUDGETPERIOD
PARGB = PARTNERBUSINESSAREA
VBUND = PARTNERCOMPANY
PFKBER = PARTNERFUNCTIONALAREA
PGEBER = PARTNERFUND
PGRANT_NBR = PARTNERGRANT
PPRCT = PARTNERPROFITCENTER
PSEGMENT = PARTNERSEGMENT
RFZEI = PAYMENTCARDITEM
CCBTC = PAYMENTCARDPAYMENTSETTLEMENT
UZAWE = PAYMENTMETHODSUPPLEMENT
WERKS = PLANT
BSCHL = POSTINGKEY
MATNR = PRODUCT
PAOBJNR = PROFITABILITYSEGMENT_2
PRCTR = PROFITCENTER
GVTYP = PROFITLOSSACCOUNTTYPE
PROJN = PROJECT
NPLNR = PROJECTNETWORK
BDGT_ACCOUNT = PUBSECBUDGETACCOUNT
BDGT_ACCOUNT_COCODE = PUBSECBUDGETACCOUNTCOCODE
IMKEY = REALESTATEOBJECT
XREF1 = REFERENCE1IDBYBUSINESSPARTNER
XREF2 = REFERENCE2IDBYBUSINESSPARTNER
XREF3 = REFERENCE3IDBYBUSINESSPARTNER
IMKEY = REINTERNALFINNUMBER
SEGMENT = SEGMENT
DABRZ = SETTLEMENTREFERENCEDATE
MWSKZ = TAXCODE
SECCO = TAXSECTION
KTOSL = TRANSACTIONTYPEDETERMINATION
VERTT = TREASURYCONTRACTTYPE
BWKEY = VALUATIONAREA
VALUT = VALUEDATE
PROJK = WBSELEMENTINTERNALID
QSSKZ = WITHHOLDINGTAXCODE
