BSEG = I_OPERATIONALACCTGDOCITEM
ZEKKN = ACCOUNTASSIGNMENTNUMBER
BELNR = ACCOUNTINGDOCUMENT
H_BSTAT = ACCOUNTINGDOCUMENTCATEGORY
BUZEI = ACCOUNTINGDOCUMENTITEM
POSNR = ACCOUNTINGDOCUMENTITEMREF
BUZID = ACCOUNTINGDOCUMENTITEMTYPE
H_BLART = ACCOUNTINGDOCUMENTTYPE
CESSION_KZ = ACCOUNTSRECEIVABLEISPLEDGED
CESSION_KZ = ACCTSRECEIVABLEPLEDGINGCODE
H_HWAE2 = ADDITIONALCURRENCY1
H_HWAE3 = ADDITIONALCURRENCY2
XCPDD = ADDRESSANDBANKISSETMANUALLY
LOKKT = ALTERNATIVEGLACCOUNT
EMPFB = ALTERNATIVEPAYEEPAYER
VERTN = ASSETCONTRACT
ANBWA = ASSETTRANSACTIONTYPE
BZDAT = ASSETVALUEDATE
ZUONR = ASSIGNMENTREFERENCE
PSWSL = BALANCETRANSACTIONCURRENCY
MEINS = BASEUNIT
VBELN = BILLINGDOCUMENT
WVERW = BILLOFEXCHANGEUSAGE
DISBN = BILLOFEXCHANGEUSAGEDOCUMENT
BVTYP = BPBANKACCOUNTINTERNALID
FILKD = BRANCHACCOUNT
J_1TPBUPL = BRANCHCODE
BUDGET_PD = BUDGETPERIOD
GSBER = BUSINESSAREA
BUPLA = BUSINESSPLACE
PRZNR = BUSINESSPROCESS
ZBD1T = CASHDISCOUNT1DAYS
SK1DT = CASHDISCOUNT1DUEDATE
ZBD1P = CASHDISCOUNT1PERCENT
ZBD2T = CASHDISCOUNT2DAYS
SK2DT = CASHDISCOUNT2DUEDATE
ZBD2P = CASHDISCOUNT2PERCENT
VBEWA = CASHFLOWTYPE
RE_ACCOUNT = CASHLEDGERACCOUNT
RE_BUKRS = CASHLEDGERCOMPANYCODE
AUGBL = CLEARINGACCOUNTINGDOCUMENT
AUGCP = CLEARINGCREATIONDATE
AUGDT = CLEARINGDATE
AUGGJ = CLEARINGDOCFISCALYEAR
XRAGL = CLEARINGISREVERSED
AGZEI = CLEARINGITEM
AUGBL = CLEARINGJOURNALENTRY
AUGGJ = CLEARINGJOURNALENTRYFISCALYEAR
FIPOS = COMMITMENTITEM
FIPOS = COMMITMENTITEMSHORTID
BUKRS = COMPANYCODE
H_HWAER = COMPANYCODECURRENCY
HWMET = COMPANYCODECURRENCYDETNMETHOD
KOKRS = CONTROLLINGAREA
ALTKT = CORPORATEGROUPACCOUNT
KOSTL = COSTCENTER
LSTAR = COSTCTRACTIVITYTYPE
KSTAR = COSTELEMENT
KSTRG = COSTOBJECT
HRKFT = COSTORIGINGROUP
KKBER = CREDITCONTROLAREA
KUNNR = CUSTOMER
KDGRP = CUSTOMERGROUP
GMVKZ = CUSTOMERISINEXECUTION
LAND1 = CUSTOMERSUPPLIERCOUNTRY
BRSCH = CUSTOMERSUPPLIERINDUSTRY
DTWS1 = DATAEXCHANGEINSTRUCTION1
DTWS2 = DATAEXCHANGEINSTRUCTION2
DTWS3 = DATAEXCHANGEINSTRUCTION3
DTWS4 = DATAEXCHANGEINSTRUCTION4
EGBLD = DELIVOFGOODSDESTCOUNTRY
EGLLD = DELIVOFGOODSORIGINCOUNTRY
H_BLDAT = DOCUMENTDATE
SGTXT = DOCUMENTITEMTEXT
XANET = DOWNPAYMENTISNETPROCEDURE
ZFBDT = DUECALCULATIONBASEDATE
MABER = DUNNINGAREA
MANSP = DUNNINGBLOCKINGREASON
MSCHL = DUNNINGKEY
MANST = DUNNINGLEVEL
KBLNR = EARMARKEDFUNDS
KBLNR = EARMARKEDFUNDSDOCUMENT
KBLPOS = EARMARKEDFUNDSDOCUMENTITEM
KBLPOS = EARMARKEDFUNDSITEM
KOART = FINANCIALACCOUNTTYPE
DATASOURCE_ID = FINANCIALDATASOURCE
BRANCH_ID = FINANCIALSERVICESBRANCH
FS_PRODUCT_GROUP = FINANCIALSERVICESPRODUCTGROUP
BEWAR = FINANCIALTRANSACTIONTYPE
GJAHR = FISCALYEAR
ANLN2 = FIXEDASSET
ZBFIX = FIXEDCASHDISCOUNT
REBZT = FOLLOWONDOCUMENTTYPE
FKBER_LONG = FUNCTIONALAREA
RFCCUR = FUNCTIONALCURRENCY
GEBER = FUND
MEASURE = FUNDEDPROGRAM
FISTL = FUNDSCENTER
HKONT = GLACCOUNT
ERFME = GOODSMOVEMENTENTRYUNIT
GRANT_NBR = GRANTID
XPYPR = HASPAYMENTORDER
HBKID = HOUSEBANK
HKTID = HOUSEBANKACCOUNT
BWTAR = INVENTORYVALUATIONTYPE
REBZZ = INVOICEITEMREFERENCE
SAMNR = INVOICELIST
REBZG = INVOICEREFERENCE
REBZJ = INVOICEREFERENCEFISCALYEAR
GST_PART = IN_GSTPARTNER
PLC_SUP = IN_GSTPLACEOFSUPPLY
HSN_SAC = IN_HSNORSACCODE
XAUTO = ISAUTOMATICALLYCREATED
XBILK = ISBALANCESHEETACCOUNT
ELIKZ = ISCOMPLETELYDELIVERED
XEGDR = ISEUTRIANGULARDEAL
XNEGP = ISNEGATIVEPOSTING
XSKRL = ISNOTCASHDISCOUNTLIABLE
XOPVW = ISOPENITEMMANAGED
XUMSW = ISSALESRELATED
XZAHL = ISUSEDINPAYMENTTRANSACTION
VNAME = JOINTVENTURE
BTYPE = JOINTVENTUREBILLINGTYPE
RECID = JOINTVENTURECOSTRECOVERYCODE
EGRUP = JOINTVENTUREEQUITYGROUP
ETYPE = JOINTVENTUREEQUITYTYPE
VPTNR = JOINTVENTUREPARTNER
PRODPER = JOINTVENTUREPRODUCTIONDATE
MADAT = LASTDUNNINGDATE
DOCLN = LEDGERGLLINEITEM
XKRES = LINEITEMDISPLAYISENABLED
MANDT = MANDT
ANLN1 = MASTERFIXEDASSET
MATNR = MATERIAL
VPRSV = MATERIALPRICECONTROL
PEINH = MATERIALPRICEUNITQTY
NETDT = NETDUEDATE
ZBD3T = NETPAYMENTDAYS
GKONT = OFFSETTINGACCOUNT
GKART = OFFSETTINGACCOUNTTYPE
SAKNR = OPERATIONALGLACCOUNT
GLO_REF1 = OPLACCTGDOCITMCNTRYSPCFCREF1
AUFNR = ORDERID
APLZL = ORDERINTBILLOFOPERATIONSITEM
AUFPL = ORDERINTERNALBILLOFOPERATIONS
AWKEY = ORIGINALREFERENCEDOCUMENT
PBUDGET_PD = PARTNERBUDGETPERIOD
PARGB = PARTNERBUSINESSAREA
VBUND = PARTNERCOMPANY
PFKBER = PARTNERFUNCTIONALAREA
PGEBER = PARTNERFUND
PGRANT_NBR = PARTNERGRANT
PPRCT = PARTNERPROFITCENTER
PSEGMENT = PARTNERSEGMENT
ZLSPR = PAYMENTBLOCKINGREASON
RFZEI = PAYMENTCARDITEM
CCBTC = PAYMENTCARDPAYMENTSETTLEMENT
PYCUR = PAYMENTCURRENCY
RSTGR = PAYMENTDIFFERENCEREASON
ZLSCH = PAYMENTMETHOD
UZAWE = PAYMENTMETHODSUPPLEMENT
PAYT_RSN = PAYMENTREASON
PAYS_TRAN = PAYMENTREFBYPAYTSRVCPROVIDER
KIDNO = PAYMENTREFERENCE
PAYS_PROV = PAYMENTSERVICEPROVIDER
ZTERM = PAYMENTTERMS
ESRPZ = PAYTSLIPWTHREFCHECKDIGIT
ESRRE = PAYTSLIPWTHREFREFERENCE
ESRNR = PAYTSLIPWTHREFSUBSCRIBER
PERNR = PERSONNELNUMBER
FDLEV = PLANNINGLEVEL
WERKS = PLANT
H_BUDAT = POSTINGDATE
BSCHL = POSTINGKEY
MATNR = PRODUCT
PAOBJNR = PROFITABILITYSEGMENT_2
PRCTR = PROFITCENTER
GVTYP = PROFITLOSSACCOUNTTYPE
PROJN = PROJECT
NPLNR = PROJECTNETWORK
BDGT_ACCOUNT = PUBSECBUDGETACCOUNT
BDGT_ACCOUNT_COCODE = PUBSECBUDGETACCOUNTCOCODE
EBELN = PURCHASINGDOCUMENT
EBELP = PURCHASINGDOCUMENTITEM
BPRME = PURCHASINGDOCUMENTPRICEUNIT
IMKEY = REALESTATEOBJECT
XREF1 = REFERENCE1IDBYBUSINESSPARTNER
XREF2 = REFERENCE2IDBYBUSINESSPARTNER
XREF3 = REFERENCE3IDBYBUSINESSPARTNER
AWSYS = REFERENCEDOCUMENTLOGICALSYSTEM
AWTYP = REFERENCEDOCUMENTTYPE
GRIRG = REGION
IMKEY = REINTERNALFINNUMBER
VBEL2 = SALESDOCUMENT
POSN2 = SALESDOCUMENTITEM
ETEN2 = SCHEDULELINE
SEGMENT = SEGMENT
MNDID = SEPAMANDATE
SERVICE_DOC_ID = SERVICEDOCUMENT
SERVICE_DOC_ITEM_ID = SERVICEDOCUMENTITEM
SERVICE_DOC_TYPE = SERVICEDOCUMENTTYPE
DABRZ = SETTLEMENTREFERENCEDATE
HZUON = SPECIALGLACCOUNTASSIGNMENT
UMSKZ = SPECIALGLCODE
UMSKS = SPECIALGLTRANSACTIONTYPE
LZBKZ = STATECENTRALBANKPAYMENTREASON
LIFNR = SUPPLIER
LANDL = SUPPLYINGCOUNTRY
MWSKZ = TAXCODE
STBUK = TAXCOMPANYCODE
TAX_COUNTRY = TAXCOUNTRY
TXDAT = TAXDETERMINATIONDATE
MWSK1 = TAXDISTRIBUTIONCODE1
MWSK2 = TAXDISTRIBUTIONCODE2
MWSK3 = TAXDISTRIBUTIONCODE3
TAXPS = TAXITEMACCTGDOCITEMREF
TXGRP = TAXITEMGROUP
TXJCD = TAXJURISDICTION
TXDAT_FROM = TAXRATEVALIDITYSTARTDATE
SECCO = TAXSECTION
MWART = TAXTYPE
H_WAERS = TRANSACTIONCURRENCY
KTOSL = TRANSACTIONTYPEDETERMINATION
VERTT = TREASURYCONTRACTTYPE
BWKEY = VALUATIONAREA
VALUT = VALUEDATE
STCEG = VATREGISTRATION
PROJK = WBSELEMENTINTERNALID
QSZNR = WITHHOLDINGTAXCERTIFICATE
QSSKZ = WITHHOLDINGTAXCODE
