CEPC = I_PROFITCENTER
NAME2 = ADDITIONALNAME
NAME1 = ADDRESSNAME
ORT01 = CITYNAME
BUKRS = COMPANYCODE
KOKRS = CONTROLLINGAREA
LAND1 = COUNTRY
DATLT = DATACOMMUNICATIONPHONENUMBER
ABTEI = DEPARTMENT
ORT02 = DISTRICT
TELFX = FAXNUMBER
ANRED = FORMOFADDRESS
PCA_TEMPLATE = FORMULAPLANNINGTEMPLATE
SPRAS = LANGUAGE
MANDT = MANDT
TELF1 = PHONENUMBER1
TELF2 = PHONENUMBER2
PFACH = POBOX
PSTL2 = POBOXPOSTALCODE
PSTLZ = POSTALCODE
PRCTR = PROFITCENTER
NAME3 = PROFITCENTERADDRNAME3
NAME4 = PROFITCENTERADDRNAME4
USNAM = PROFITCENTERCREATEDBYUSER
ERSDA = PROFITCENTERCREATIONDATE
LOCK_IND = PROFITCENTERISBLOCKED
DRNAM = PROFITCENTERPRINTERNAME
KHINR = PROFITCENTERSTANDARDHIERARCHY
VERAK = PROFITCTRRESPONSIBLEPERSONNAME
VERAK_USER = PROFITCTRRESPONSIBLEUSER
REGIO = REGION
SEGMENT = SEGMENT
STRAS = STREETADDRESSNAME
TXJCD = TAXJURISDICTION
TELBX = TELEBOXNUMBER
TELTX = TELETEXNUMBER
TELX1 = TELEXNUMBER
DATBI = VALIDITYENDDATE
DATAB = VALIDITYSTARTDATE
