CRHD = I_WORKCENTER
PPSKZ = ADVANCEDPLANNINGISSUPPORTED
KAPID = CAPACITYINTERNALID
QUALF = EMPLOYEESUITABILITY
LOGRP = EMPLOYEEWAGEGROUP
LOGRP_REF = EMPLOYEEWAGEGROUPISREFERENCED
LOART = EMPLOYEEWAGETYPE
LOART_REF = EMPLOYEEWAGETYPEISREFERENCED
QUALF_REF = EMPLSUITABILITYISREFERENCED
SLWID = FREEDEFINEDTABLEFIELDSEMANTIC
S_LABOR_TRACK = LABORTRACKINGISREQUIRED
MATYP = MACHINETYPE
MANDT = MANDT
RGEKZ = MATLCOMPISMARKEDFORBACKFLUSH
LOANZ_REF = NMBROFTIMETICKETSISREFERENCED
RSANZ = NUMBEROFCONFIRMATIONSLIPS
RSANZ_REF = NUMBEROFCONFSLIPSISREFERENCED
LOANZ = NUMBEROFTIMETICKETS
STOBJ = OBJECTINTERNALID
STEUS_REF = OPCONTROLPROFILEISREFERENCED
STEUS = OPERATIONCONTROLPROFILE
WERKS = PLANT
HRPLVAR = PLANVERSION
SNTYPE = SHIFTNOTETYPE
SRTYPE = SHIFTREPORTTYPE
KTSCH_REF = STANDARDTEXTIDISREFERENCED
KTSCH = STANDARDTEXTINTERNALID
VGWTS = STANDARDWORKFORMULAPARAMGROUP
VGARB = STANDARDWORKQUANTITYUNIT
PRVBE = SUPPLYAREA
ENDDA = VALIDITYENDDATE
BEGDA = VALIDITYSTARTDATE
ARBPL = WORKCENTER
VERWE = WORKCENTERCATEGORYCODE
PARU1 = WORKCENTERFMLAPARAMUNIT1
PARU2 = WORKCENTERFMLAPARAMUNIT2
PARU3 = WORKCENTERFMLAPARAMUNIT3
PARU4 = WORKCENTERFMLAPARAMUNIT4
PARU5 = WORKCENTERFMLAPARAMUNIT5
PARU6 = WORKCENTERFMLAPARAMUNIT6
PARV1 = WORKCENTERFMLAPARAMVALUE1
PARV2 = WORKCENTERFMLAPARAMVALUE2
PARV3 = WORKCENTERFMLAPARAMVALUE3
PARV4 = WORKCENTERFMLAPARAMVALUE4
PARV5 = WORKCENTERFMLAPARAMVALUE5
PARV6 = WORKCENTERFMLAPARAMVALUE6
PAR01 = WORKCENTERFORMULAPARAM1
PAR02 = WORKCENTERFORMULAPARAM2
PAR03 = WORKCENTERFORMULAPARAM3
PAR04 = WORKCENTERFORMULAPARAM4
PAR05 = WORKCENTERFORMULAPARAM5
PAR06 = WORKCENTERFORMULAPARAM6
OBJID = WORKCENTERINTERNALID
XSPRR = WORKCENTERISLOCKED
XKOST = WORKCENTERISMNTNDFORCOSTING
XTERM = WORKCENTERISMNTNDFORSCHEDULING
LVORM = WORKCENTERISTOBEDELETED
AENAM_GRND = WORKCENTERLASTCHANGEDBY
STAND = WORKCENTERLOCATION
ORTGR = WORKCENTERLOCATIONGROUP
ZWMIN = WORKCENTERMINIMUMQUEUEDURATION
ZEIWM = WORKCENTERMINIMUMQUEUEDURNUNIT
VERAN = WORKCENTERRESPONSIBLE
RASCH_REF = WORKCENTERSETPTYPEISREFERENCED
RASCH = WORKCENTERSETUPTYPE
ZWNOR = WORKCENTERSTANDARDQUEUEDURN
VGE01 = WORKCENTERSTANDARDWORKQTYUNIT1
VGE02 = WORKCENTERSTANDARDWORKQTYUNIT2
VGE03 = WORKCENTERSTANDARDWORKQTYUNIT3
VGE04 = WORKCENTERSTANDARDWORKQTYUNIT4
VGE05 = WORKCENTERSTANDARDWORKQTYUNIT5
VGE06 = WORKCENTERSTANDARDWORKQTYUNIT6
ZEIWN = WORKCENTERSTDQUEUEDURNUNIT
OBJTY = WORKCENTERTYPECODE
PLANV = WORKCENTERUSAGE
HROID = WRKCTRHUMRSCEOBJID
FORTN = WRKCTRINTPROCGSCHEDGFMLA
FORT2 = WRKCTRPROCGSCHEDGFMLA
FORT1 = WRKCTRSETUPSCHEDGFMLA
VGM01 = WRKCTRSTDVALMAINTRULE1
VGM02 = WRKCTRSTDVALMAINTRULE2
VGM03 = WRKCTRSTDVALMAINTRULE3
VGM04 = WRKCTRSTDVALMAINTRULE4
VGM05 = WRKCTRSTDVALMAINTRULE5
VGM06 = WRKCTRSTDVALMAINTRULE6
FORT3 = WRKCTRTEARDOWNSCHEDGFMLA
