CSKS = I_COSTCENTER
SKD_TEMPL = ACTLDEPSTATISTICALKEYFIGURES
SKI_TEMPL = ACTLINDEPSTATISTICALKEYFIGURES
CPD_TEMPL = ACTYDEPDNTFORMULAPLANNINGTMPL
SCD_TEMPL = ACTYDEPENDENTALLOCATIONTMPL
SCI_TEMPL = ACTYINDEPENDENTALLOCATIONTMPL
CPI_TEMPL = ACTYINDEPFORMULAPLANNINGTMPL
NAME2 = ADDRESSADDITIONALNAME
NAME1 = ADDRESSNAME
AVC_ACTIVE = AVAILABILITYCONTROLISACTIVE
AVC_PROFILE = AVAILABILITYCONTROLPROFILE
BUDGET_CARRYING_COST_CTR = BUDGETCARRYINGCOSTCENTER
GSBER = BUSINESSAREA
ORT01 = CITYNAME
BUKRS = COMPANYCODE
KAPPL = CONDITIONAPPLICATION
KVEWE = CONDITIONUSAGE
MGEFL = CONSUMPTIONQTYISRECORDED
KOKRS = CONTROLLINGAREA
KOSTL = COSTCENTER
KOSZSCHL = COSTCENTERACCOUNTINGOVERHEAD
NAME3 = COSTCENTERADDRNAME3
NAME4 = COSTCENTERADDRNAME4
VMETH = COSTCENTERALLOCATIONMETHOD
AFUNK = COSTCENTERALTERNATIVEFUNCTION
KOSAR = COSTCENTERCATEGORY
USNAM = COSTCENTERCREATEDBYUSER
ERSDA = COSTCENTERCREATIONDATE
WAERS = COSTCENTERCURRENCY
FUNKT = COSTCENTERFUNCTION
KOMPL = COSTCENTERISCOMPLETE
DRNAM = COSTCENTERPRINTERDESTINATION
KHINR = COSTCENTERSTANDARDHIERAREA
CCKEY = COSTCOLLECTOR
VERAK = COSTCTRRESPONSIBLEPERSONNAME
VERAK_USER = COSTCTRRESPONSIBLEUSER
KALSM = COSTINGSHEET
LAND1 = COUNTRY
DATLT = DATACOMMUNICATIONPHONENUMBER
ABTEI = DEPARTMENT
ORT02 = DISTRICT
TELFX = FAXNUMBER
ANRED = FORMOFADDRESS
FUNC_AREA = FUNCTIONALAREA
FUNC_AREA_FIX_ASSIGNED = FUNCTIONALAREAISFIXASSIGNED
FUND = FUND
FUND_FIX_ASSIGNED = FUNDISFIXASSIGNED
GRANT_ID = GRANTID
GRANT_FIX_ASSIGNED = GRANTIDISFIXASSIGNED
BKZKP = ISBLKDFORPRIMARYCOSTSPOSTING
BKZKS = ISBLKDFORSECONDARYCOSTSPOSTING
BKZOB = ISBLOCKEDFORCOMMITMENTPOSTING
PKZKP = ISBLOCKEDFORPLANPRIMARYCOSTS
PKZER = ISBLOCKEDFORPLANREVENUES
PKZKS = ISBLOCKEDFORPLANSECONDARYCOSTS
BKZER = ISBLOCKEDFORREVENUEPOSTING
STAKZ = ISSTATISTICALCOSTCENTER
VNAME = JOINTVENTURE
JV_JIBCL = JOINTVENTURECLASS
ETYPE = JOINTVENTUREEQUITYTYPE
JV_OTYPE = JOINTVENTUREOBJECTTYPE
RECID = JOINTVENTURERECOVERYCODE
JV_JIBSA = JOINTVENTURESUBCLASS
SPRAS = LANGUAGE
LOGSYSTEM = LOGICALSYSTEM
MANDT = MANDT
OBJNR = OBJECTINTERNALID
TELF1 = PHONENUMBER1
TELF2 = PHONENUMBER2
WERKS = PLANT
PFACH = POBOX
PSTL2 = POBOXPOSTALCODE
PSTLZ = POSTALCODE
PRCTR = PROFITCENTER
REGIO = REGION
STRAS = STREETADDRESSNAME
NKOST = SUBSEQUENTCOSTCENTER
TXJCD = TAXJURISDICTION
TELBX = TELEBOXNUMBER
TELTX = TELETEXNUMBER
TELX1 = TELEXNUMBER
DATBI = VALIDITYENDDATE
DATAB = VALIDITYSTARTDATE
