CSLA = I_COSTCENTERACTIVITYTYPE
SPRKZ = ACTIVITYTYPEISBLOCKED
LATYPI = ACTLPOSTGCOSTCENTERACTYTYPECAT
TARKZ_I = ACTUALPRICEALLOCATIONMETHOD
MANIST = ACTUALQUANTITYISSETMANUALLY
VKSTA = ALLOCATIONCOSTELEMENT
KOKRS = CONTROLLINGAREA
LSTAR = COSTCTRACTIVITYTYPE
LATYP = COSTCTRACTIVITYTYPECATEGORY
AUSEH = COSTCTRACTIVITYTYPEOUTPQTYUNIT
LEINH = COSTCTRACTIVITYTYPEQTYUNIT
KSTTY = COSTCTRACTIVITYTYPEVALIDCAT
LARK1 = COSTCTRACTYTYPEISCTRLGRLVTCOMP
LARK2 = COSTCTRACTYTYPEISHUMRSCERLVT
HRKFT = COSTORIGINGROUP
ERSDA = CREATIONDATE
USNAM = ENTEREDBYUSER
FIXVO = FIXEDCOSTISPREDISTRIBUTED
MANDT = MANDT
AUSFK = OUTPUTQUANTITYFACTOR
YRATE = PERIODPRICEISAVERAGE
MANPLAN = PLANQUANTITYISSETMANUALLY
TARKZ = PRICEALLOCATIONMETHOD
DATBI = VALIDITYENDDATE
DATAB = VALIDITYSTARTDATE
