CSLT = I_COSTCENTERACTIVITYTYPETEXT
KOKRS = CONTROLLINGAREA
LSTAR = COSTCTRACTIVITYTYPE
LTEXT = COSTCTRACTIVITYTYPEDESC
KTEXT = COSTCTRACTIVITYTYPENAME
MCTXT = COSTCTRACTYTYPETXTSEARCHTERM
SPRAS = LANGUAGE
MANDT = MANDT
DATBI = VALIDITYENDDATE
