DFKKOPK = I_CADOCUMENTGLITEM
ESNUM = BANKSTATEMENTITEM
KUKEY = BANKSTATEMENTSHORTID
MEINS = BASEUNIT
KONTL = CAACCOUNTASSIGNMENT
KONTT = CAACCOUNTASSIGNMENTCATEGORY
XDEXR = CAALTVEXCHANGERATEFORTAXITEM
XDEXR = CAALTVEXCHANGERATESETCODE
BETRH = CAAMOUNTINLOCALCURRENCY
BETR2 = CAAMOUNTINSECONDCURRENCY
BETR3 = CAAMOUNTINTHIRDCURRENCY
BETRW = CAAMOUNTINTRANSACTIONCURRENCY
REACC = CACASHFLOWACCOUNT
REBUK = CACASHFLOWCOMPANYCODE
XNDTX = CACONTAINSNONDEDUCTIBLEINPTTAX
AASTA = CACTRLFIELDFORACCTASSGMTDISTR
OPBEL = CADOCUMENTNUMBER
TXJCO = CAENTEREDTAXJURISDICTIONCODE
OPUPK = CAGLITEMNUMBER
PSWSL = CAGLPOSTINGCURRENCY
TXGRP = CAGROUPINGCODEFORTAXITEMS
INTBU = CAINTERNALPOSTINGREASONCODE
INVGR = CAINVCGGROUPINGKEY
XCSHA = CAISCASHFLOWITEM
XEIPH = CAISSEPARATELINEITEMINGL
XINTB = CAITMISCREATEDBYPOSTGINTERFACE
NEGBU = CANEGATIVEPOSTINGCONTROLCODE
NDTAX = CANONDEDUCTIBLETXAMTINDOCCRCY
NDTXH = CANONDEDUCTIBLETXAMTINLOCLCRCY
STRKZ = CAOTHERTAXCODE
XCOPA = CAPROFITANALYSISUPDTISDIRECT
FIKEY = CARECONCILIATIONKEY
WHGRP = CAREPETITIONGROUP
LNKID = CASHMANAGEMENTLINK
LTYPE = CASHMANAGEMENTLINKTYPE
EUROU = CASTATUSOFEUROCONVERSION
MWSZKZ = CASUPPLEMENTARYTAXCODE
SBASW = CATAXBASEAMOUNT
SBASH = CATAXBASEAMOUNTINLOCALCURRENCY
TXDAT = CATAXDATE
TXEXK = CATAXEXCEPTIONID
XUSTPD = CATAXISCALCULATEDEXTERNALLY
XDEXR = CATAXITEMHASALTVEXCHANGERATE
TXCNT = CATAXJURISDICTIONLEVELCOUNTER
SCTAX = CATAXPORTIONINLOCALCURRENCY
STTAX = CATAXPORTIONINTRANSCURRENCY
STPRZ = CATAXRATE
KTOSL = CATRANSACTIONKEYACCOUNTDETN
FMTYP = CAUPDATEMETHODFORFUNDSMGMT
QSSEW = CAWITHHOLDINGTAXSUPPLEMENT
BUKRS = COMPANYCODE
KSCHL = CONDITIONTYPE
KOSTL = COSTCENTER
KBLNR = EARMARKEDFUNDS
KBLNR = EARMARKEDFUNDSDOCUMENT
GITYP = EMPLOYMENTTAXDISTRIBUTIONTYPE
HKONT = GLACCOUNT
GRICD = GROSSINCOMETAXACTIVITYCODE
HBKID = HOUSEBANK
HKTID = HOUSEBANKACCOUNT
LDGRP = LEDGERGROUP
MANDT = MANDT
ORIGFIKRS = ORIGINALFINANCIALMGMTAREA
BUDGETYEAR = ORIGLYEARFORFINMGMTACCTASSGMT
VBUND = PARTNERCOMPANY
FDLEV = PLANNINGLEVEL
PASUBNR = PROFITABILITYSEGMENTCHANGES
PAOBJNR = PROFITABILITYSEGMENT_2
SQUAN = QUANTITYSIGNCODE
KDAUF = SALESORDER
KDPOS = SALESORDERITEM
MWSKZ = TAXCODE
TXJCD = TAXJURISDICTION
VALUT = VALUEDATE
