DFKKKO = I_CADOCUMENTHEADER
APPLK = CAAPPLICATIONAREA
AGINF = CACLEARINGINFORMATION
XCSHA = CADOCCONTAINSCASHFLOWITEMS
BLTYP = CADOCUMENTCLASS
XDAAG = CADOCUMENTISAGED
OPBEL = CADOCUMENTNUMBER
HERKF = CADOCUMENTORIGINCODE
APPDX = CADOCUMENTSUPPLEMENTS
TATYP = CADOCUMENTTRANSACTIONCLASS
BLART = CADOCUMENTTYPE
HBBLA = CADOCUMENTTYPEFORGLTRANSFER
VERSN = CADOCUMENTVERSION
BUDAT = CAPOSTINGDATE
ABGRD = CAPOSTINGREASON
FIKEY = CARECONCILIATIONKEY
XBLNR = CAREFERENCEDOCUMENT
WNPER = CAREQUESTEDPERIODFORGLTRANSFER
RLGRD = CARETURNREASON
STORB = CAREVERSALDOCUMENTNUMBER
STBEL = CAREVERSEDDOCUMENTNUMBER
XEIBH = CASEPARATEDOCISCREATEDINGL
UTLOC = CASTORAGELOCATIONOFTAXSUPLMNT
XTXCH = CATAXCODEWASEXCHANGED
STBUK = CATAXCOMPANYCODE
C4EYP = CAWORKFLOWCHECKPROCESS
C4EYE = CAWORKFLOWCHECKREASON
ERNAM = CREATEDBYUSER
CPUDT = CREATIONDATE
CPUTM = CREATIONTIME
BLDAT = DOCUMENTDATE
WWERT = EXCHANGERATEDATE
XSING = ISINDIVIDUALPOSTING
AWSYS = LOGICALSYSTEM
MANDT = MANDT
AWKEY = ORIGINALREFERENCEDOCUMENT
AWTYP = REFERENCEDOCUMENTTYPE
VATDATE = TAXREPORTINGDATE
WAERS = TRANSACTIONCURRENCY
