DFKKOP = I_CADOCUMENTBPITEMPHYSICAL
ABWKT = ALTVCONTRACTACCTFORCOLLVBILLS
GSBER = BUSINESSAREA
GPART = BUSINESSPARTNER
BUPLA = BUSINESSPLACE
KONTL = CAACCOUNTASSIGNMENT
KONTT = CAACCOUNTASSIGNMENTCATEGORY
KOFIZ = CAACCOUNTDETERMINATIONCODE
VTRE2 = CAADDITIONALCONTRACT
FDZTG = CAADDITIONALDAYSFORCASHMGMT
EMADR = CAADDRESSOFALTVBPFORPAYMENT
EMGPA = CAALTVBPFORPAYMENT
BETRH = CAAMOUNTINLOCALCURRENCY
BETR2 = CAAMOUNTINSECONDCURRENCY
BETR3 = CAAMOUNTINTHIRDCURRENCY
BETRW = CAAMOUNTINTRANSACTIONCURRENCY
APPLK = CAAPPLICATIONAREA
EMBVT = CABANKOFALTVBPFORPAYMENT
QSSHB = CABASEAMOUNTFORWITHHOLDINGTAX
OPUPK = CABPITEMNUMBER
OPTXT = CABPITEMTEXT
EMCRD = CACARDOFALTVBPFORPAYMENT
AUGSK = CACASHDISCAMOUNTINCLEARINGCRCY
FAEDS = CACASHDISCOUNTDUEDATE
SKTPZ = CACASHDISCOUNTRATE
REACC = CACASHFLOWACCOUNT
REBUK = CACASHFLOWCOMPANYCODE
XAESP = CACHANGEISFORBIDDEN
AUGBT = CACLEARINGAMOUNTINCLEARINGCRCY
AUGWA = CACLEARINGCURRENCY
AUGDT = CACLEARINGDATE
AUGBL = CACLEARINGDOCUMENTNUMBER
XRAGL = CACLEARINGPOSTINGISRESET
AUGRD = CACLEARINGREASON
AUGRS = CACLEARINGRESTRICTIONCODE
AUGST = CACLEARINGSTATUS
VTREF = CACONTRACT
FASTA = CACURRENTFACTORINGSTATUSOFRBL
STUDT = CADEFERRALDATE
ORIOP = CADOCBPITEMTOTALAMOUNTINTC
OPBEL = CADOCUMENTNUMBER
ASBLG = CADOCUMENTNUMBEROFORIGINITEM
HERKF_KK = CADOCUMENTORIGINCODE
BLART = CADOCUMENTTYPE
INFOZ = CADOUBTFULORVALUEADJMTCODE
MWVKO = CADOWNPAYMENTOFFSETTAXACCOUNT
MWSKO = CADOWNPAYMENTTAXACCOUNT
MAHNV = CADUNNINGPROCEDURE
SKFBT = CAELIGIBLEAMOUNTFORCSHDISCOUNT
ABRZO = CAENDDATEOFBILLINGPERIOD
PASTA = CAFACTORINGCHECKSTSFORCLRGINFO
OPUPF = CAFACTORINGITEM
PSWBT = CAGLPOSTINGAMOUNT
PSWSL = CAGLPOSTINGCURRENCY
PSWTX = CAGLPOSTINGTAXAMOUNT
GRKEY = CAGROUPINGCODEFORBPITEMS
TXGRP = CAGROUPINGCODEFORTAXITEMS
PYGRP = CAGROUPINGFORPAYMENT
INKPS = CAGRPGCODEFORTRANSFTOCOLLAGCY
IKEY = CAINTERESTCODE
INTBU = CAINTERNALPOSTINGREASONCODE
XCSHA = CAISCASHFLOWITEM
XANZA = CAISDOWNPAYMENTREQUEST
XCOLC = CAISINCLUDEDINCOLLECTIONCASE
PALIX = CAISPARTOFJOINTLIABILITY
XEIPH = CAISSEPARATELINEITEMINGL
XMANL = CAITEMISEXCLUDEDFROMDUNNING
VERKZ = CAITEMISONLYFORSETTLEMENT
AUGOB = CAITEMISWITHDRAWN
HVORG = CAMAINTRANSACTION
NEGBU = CANEGATIVEPOSTINGCONTROLCODE
FAEDN = CANETDUEDATE
WHANG = CANUMBEROFREPETITIONITEMS
STRKZ = CAOTHERTAXCODE
PTITM = CAPARTNERSETTLEMENTSTATUS
PYBUK = CAPAYMENTCOMPANYCODE
PYMET = CAPAYMENTMETHOD
XPYOR = CAPAYMENTPRENOTIFICATIONCODE
PDTYP = CAPAYMENTSPECIFICATIONCATEGORY
PERSL = CAPERIODCODE
BUDAT = CAPOSTINGDATE
AUGBD = CAPOSTINGDATEOFCLEARINGDOC
VTPOS = CAPROVIDERCONTRACTITEMNUMBER
LANDL = CARECEIVINGCOUNTRY
HKONT = CARECONCILIATIONACCOUNT
XBLNR = CAREFERENCEDOCUMENT
WHGRP = CAREPETITIONGROUP
OPUPW = CAREPETITIONITEMNUMBER
RDSTA = CAREVENUEDISTRCURRENTSTATUS
FINRE = CAREVENUEDISTRFINALRECIPIENT
RDSTB = CAREVENUEDISTRLASTSTATUS
RNDPS = CAROUNDINGITEMCODE
PNEXD = CASEPAPRENOTIFEXECUTIONDATE
PNNUM = CASEPAPRENOTIFICATIONNUMBER
PNCTR = CASEPAPRENOTIFICATIONRQMTCODE
PNHKF = CASEPAPRENOTIFORIGINCODE
FDGRP = CASHPLANNINGGROUP
ABRZU = CASTARTDATEOFBILLINGPERIOD
ASTKZ = CASTATISTICALCODEOFORIGINITEM
STAKZ = CASTATISTICALITEMCODE
SUBAP = CASUBAPPLICATION
OPUPZ = CASUBITEMNUMBER
ABWTP = CASUBSTITUTEDOCUMENTCATEGORY
ABWBL = CASUBSTITUTEDOCUMENTNUMBER
TVORG = CASUBTRANSACTION
MWSZKZ = CASUPPLEMENTARYTAXCODE
AUGBS = CATAXAMOUNTINCLEARINGCRCY
SBETH = CATAXAMOUNTINLOCALCURRENCY
SBET2 = CATAXAMOUNTINSECONDCURRENCY
SBET3 = CATAXAMOUNTINTHIRDCURRENCY
SBETW = CATAXAMOUNTINTRANSCURRENCY
INTTX = CATAXAMOUNTISSETFROMEXTERNAL
TXDAT = CATAXDATE
XUSTPD = CATAXISCALCULATEDEXTERNALLY
SCTAX = CATAXPORTIONINLOCALCURRENCY
STTAX = CATAXPORTIONINTRANSCURRENCY
AUGVD = CAVALUEDATEFORCLEARING
QBSHB = CAWITHHOLDINGTAXAMOUNT
QSPTP = CAWITHHOLDINGTAXCATEGORY
QSPRZ = CAWITHHOLDINGTAXPERCENTAGE
QSSEW = CAWITHHOLDINGTAXSUPPLEMENT
C4EYP = CAWORKFLOWCHECKPROCESS
C4EYE = CAWORKFLOWCHECKREASON
BUKRS = COMPANYCODE
VKONT = CONTRACTACCOUNT
SPART = DIVISION
BLDAT = DOCUMENTDATE
MANDT = MANDT
VBUND = PARTNERCOMPANY
PERNR = PERSONNELNUMBER
FDLEV = PLANNINGLEVEL
PRCTR = PROFITCENTER
SEGMENT = SEGMENT
EMMND = SEPAMANDATECAINTERNALID
MWSKZ = TAXCODE
TXJCD = TAXJURISDICTION
WAERS = TRANSACTIONCURRENCY
QSZNR = WITHHOLDINGTAXCERTIFICATE
QSSKZ = WITHHOLDINGTAXCODE
