EBAN = I_PURCHASEREQUISITIONITEMAPI01
KNTTP = ACCOUNTASSIGNMENTCATEGORY
ADRNR = ADDRESSID
MEINS = BASEUNIT
CHARG = BATCH
KZVBR = CONSUMPTIONPOSTING
ERNAM = CREATEDBYUSER
BADAT = CREATIONDATE
LPEIN = DELIVDATECATEGORY
LFDAT = DELIVERYDATE
EXTCOMPANYCODEFORPURG = EXTCOMPANYCODEFORPURG
EXTCONTRACTFORPURG = EXTCONTRACTFORPURG
EXTCONTRACTITEMFORPURG = EXTCONTRACTITEMFORPURG
EXTDESIREDSUPPLIERFORPURG = EXTDESIREDSUPPLIERFORPURG
EXTFIXEDSUPPLIERFORPURG = EXTFIXEDSUPPLIERFORPURG
EXTINFORECORDFORPURG = EXTINFORECORDFORPURG
EXTMATERIALFORPURG = EXTMATERIALFORPURG
EXTPLANTFORPURG = EXTPLANTFORPURG
EXTPURGORGFORPURG = EXTPURGORGFORPURG
FLIEF = FIXEDSUPPLIER
WEPOS = GOODSRECEIPTISEXPECTED
WEUNB = GOODSRECEIPTISNONVALUATED
REPOS = INVOICEISEXPECTED
EBAKZ = ISCLOSED
LOEKZ = ISDELETED
ISOUTLINE = ISOUTLINE
BLCKD = ISPURREQNBLOCKED
ADRN2 = ITEMDELIVERYADDRESSID
SPRAS = LANGUAGE
LASTCHANGEDATETIME = LASTCHANGEDATETIME
MANDT = MANDT
ADRNR = MANUALDELIVERYADDRESSID
MATNR = MATERIAL
WEBAZ = MATERIALGOODSRECEIPTDURATION
MATKL = MATERIALGROUP
PLIFZ = MATERIALPLANNEDDELIVERYDURN
REVLV = MATERIALREVISIONLEVEL
REVLV = MATERIALREVISIONLEVEL_2
MHDRZ = MINREMAININGSHELFLIFE
BERID = MRPAREA
DISPO = MRPCONTROLLER
VRTKZ = MULTIPLEACCTASSGMTDISTRIBUTION
BSMNG = ORDEREDQUANTITY
ENDDATE = PERFORMANCEPERIODENDDATE
STARTDATE = PERFORMANCEPERIODSTARTDATE
WERKS = PLANT
STATU = PROCESSINGSTATUS
EXT_BE_SOURCE_SYS = PROCUREMENTHUBSOURCESYSTEM
PRODUCTTYPE = PRODUCTTYPE
KONNR = PURCHASECONTRACT
KTPNR = PURCHASECONTRACTITEM
PURCHASEREQNITEMUNIQUEID = PURCHASEREQNITEMUNIQUEID
BANFN = PURCHASEREQUISITION
FIXKZ = PURCHASEREQUISITIONISFIXED
BNFPO = PURCHASEREQUISITIONITEM
TXZ01 = PURCHASEREQUISITIONITEMTEXT
PREIS = PURCHASEREQUISITIONPRICE
FRGDT = PURCHASEREQUISITIONRELEASEDATE
FRGZU = PURCHASEREQUISITIONSTATUS
BSART = PURCHASEREQUISITIONTYPE
EBELN = PURCHASINGDOCUMENT
BSTYP = PURCHASINGDOCUMENTCATEGORY
EBELP = PURCHASINGDOCUMENTITEM
PSTYP = PURCHASINGDOCUMENTITEMCATEGORY
BSAKZ = PURCHASINGDOCUMENTSUBTYPE
EKGRP = PURCHASINGGROUP
INFNR = PURCHASINGINFORECORD
EKORG = PURCHASINGORGANIZATION
PARENT_ITEM_NO = PURCHASINGPARENTITEM
CONTRACT_FOR_LIMIT = PURCONTRACTFOROVERALLLIMIT
EXLIN = PURGCONFIGURABLEITEMNUMBER
EXSNR = PURGEXTERNALSORTNUMBER
BADAT = PURREQCREATIONDATE
WAERS = PURREQNITEMCURRENCY
LIMIT_CONSUMPTION_VALUE = PURREQNLIMITCONSUMPTIONAMT
ESTKZ = PURREQNORIGIN
PEINH = PURREQNPRICEQUANTITY
BANPR = PURREQNRELEASESTATUS
VRTYP = PURREQNSOURCEOFSUPPLYTYPE
SC_AUTHOR = PURREQNSSPAUTHOR
SC_CATALOGID = PURREQNSSPCATALOG
SC_CATALOGITEM = PURREQNSSPCATALOGITEM
SC_SR_ITEM_KEY = PURREQNSSPCROSSCATALOGITEM
SC_REQUESTOR = PURREQNSSPREQUESTOR
FRGKZ = RELEASECODE
FRGRL = RELEASEISNOTCOMPLETED
FRGST = RELEASESTRATEGY
MENGE = REQUESTEDQUANTITY
BEDNR = REQUIREMENTTRACKING
AFNAM = REQUISITIONERNAME
RSNUM = RESERVATION
SERVICEPERFORMER = SERVICEPERFORMER
ZUGBA = SOURCEOFSUPPLYISASSIGNED
LGORT = STORAGELOCATION
LIFNR = SUPPLIER
IDNLF = SUPPLIERMATERIALNUMBER
RESWK = SUPPLYINGPLANT
MWSKZ = TAXCODE
