EBAN = I_PURREQNACCTASSGMTAPI01
GSBER = BUSINESSAREA
PRZNR = BUSINESSPROCESS
FIPOS = COMMITMENTITEM
FIPOS = COMMITMENTITEMSHORTID
KOKRS = CONTROLLINGAREA
KOSTL = COSTCENTER
LSTAR = COSTCTRACTIVITYTYPE
SAKTO = COSTELEMENT
KSTRG = COSTOBJECT
ERDAT = CREATIONDATE
KBLNR = EARMARKEDFUNDSDOCUMENT
ANLN2 = FIXEDASSET
FKBER = FUNCTIONALAREA
GEBER = FUND
FISTL = FUNDSCENTER
SAKTO = GLACCOUNT
WEMPF = GOODSRECIPIENTNAME
GRANT_NBR = GRANTID
LOEKZ = ISDELETED
RECID = JOINTVENTURERECOVERYCODE
MANDT = MANDT
ANLN1 = MASTERFIXEDASSET
VPROZ = MULTIPLEACCTASSGMTDISTRPERCENT
APLZL = NETWORKACTIVITYINTERNALID
AUFNR = ORDERID
APLZL_ORD = ORDERINTBILLOFOPERATIONSITEM
AUFPL_ORD = ORDERINTERNALID
VPTNR = PARTNERACCOUNTNUMBER
AUFNR = PROCESSORDER
EXTWBSELEMENT = PROCMTHUBWBSELEMENTEXTERNALID
PAOBJNR = PROFITABILITYSEGMENT
PAOBJNR = PROFITABILITYSEGMENT_2
PRCTR = PROFITCENTER
NPLNR = PROJECTNETWORK
AUFPL = PROJECTNETWORKINTERNALID
ZEBKN = PURCHASEREQNACCTASSGMTNUMBER
BANFN = PURCHASEREQUISITION
BNFPO = PURCHASEREQUISITIONITEM
NETWR = PURREQNNETAMOUNT
MENGE = QUANTITY
IMKEY = REALESTATEOBJECT
IMKEY = REINTERNALFINNUMBER
VBELP = SALESDOCUMENTITEM
VBELN = SALESORDER
VBELP = SALESORDERITEM
VETEN = SALESORDERSCHEDULELINE
VETEN = SCHEDULELINE
VBELN = SDDOCUMENT
SERVICE_DOC_ID = SERVICEDOCID
SERVICE_DOC_ITEM_ID = SERVICEDOCITEMID
SERVICE_DOC_TYPE = SERVICEDOCUMENTTYPE
DABRZ = SETTLEMENTREFERENCEDATE
ABLAD = UNLOADINGPOINTNAME
PS_PSP_PNR = WBSELEMENTINTERNALID
PS_PSP_PNR = WBSELEMENTINTERNALID_2
