EINA = I_PURCHASINGINFORECORDAPI01
LMEIN = BASEUNIT
ERDAT = CREATIONDATE
LOEKZ = ISDELETED
RELIF = ISREGULARSUPPLIER
MANDT = MANDT
MFRNR = MANUFACTURER
MATNR = MATERIAL
MATKL = MATERIALGROUP
MAHN1 = NODAYSREMINDER1
MAHN2 = NODAYSREMINDER2
MAHN3 = NODAYSREMINDER3
UMREN = ORDERITEMQTYTOBASEQTYDNMNTR
UMREZ = ORDERITEMQTYTOBASEQTYNMRTR
KOLIF = PRIORSUPPLIER
ANZPU = PRODUCTPURCHASEPOINTSQTY
PUNEI = PRODUCTPURCHASEPOINTSQTYUNIT
INFNR = PURCHASINGINFORECORD
TXZ01 = PURCHASINGINFORECORDDESC
MEINS = PURGDOCORDERQUANTITYUNIT
RUECK = RETURNAGREEMENT
URZZT = SUPLRCERTORIGINCLASSFCTNNUMBER
LIFNR = SUPPLIER
URZTP = SUPPLIERCERTORIGINCAT
URZLA = SUPPLIERCERTORIGINCOUNTRY
URZNR = SUPPLIERCERTORIGINNUMBER
REGIO = SUPPLIERCERTORIGINREGION
URZDT = SUPPLIERCERTVALIDITYENDDATE
WGLIF = SUPPLIERMATERIALGROUP
IDNLF = SUPPLIERMATERIALNUMBER
TELF1 = SUPPLIERPHONENUMBER
VERKF = SUPPLIERRESPSALESPERSONNAME
LTSNR = SUPPLIERSUBRANGE
LTSSF = SUPPLIERSUBRANGESORTNUMBER
VABME = VARBLPURORDUNITISACTIVE
