EKBE = I_PURCHASEORDERHISTORYAPI01
ZEKKN = ACCOUNTASSIGNMENTNUMBER
CPUDT = ACCOUNTINGDOCUMENTCREATIONDATE
CHARG = BATCH
WAERS = CURRENCY
SHKZG = DEBITCREDITCODE
VBELN_ST = DELIVERYDOCUMENT
VBELP_ST = DELIVERYDOCUMENTITEM
LSMEH = DELIVERYQUANTITYUNIT
BLDAT = DOCUMENTDATE
XBLNR = DOCUMENTREFERENCEID
WKURS = EXCHANGERATE
KUDIF = EXCHANGERATEDIFFERENCEAMOUNT
BPWES = GDSRCPTBLKDSTKQTYINORDPRCUNIT
WESBS = GDSRCPTBLKDSTKQTYINORDQTYUNIT
BWART = GOODSMOVEMENTTYPE
AREWR = GRIRACCTCLRGAMTINCOCODECRCY
AREWB = GRIRACCTCLRGAMTINORDTRNSACCRCY
AREWW = GRIRACCTCLRGAMTINTRANSACCRCY
BWTAR = INVENTORYVALUATIONTYPE
REFWR = INVOICEAMOUNTINFRGNCURRENCY
REEWR = INVOICEAMTINCOCODECRCY
REWRB = INVOICEAMTINPURORDTRANSACCRCY
ELIKZ = ISCOMPLETELYDELIVERED
WEORA = ISTOBEACCEPTEDATORIGIN
MANDT = MANDT
EMATN = MANUFACTURERMATERIAL
MATNR = MATERIAL
WERKS = PLANT
BUDAT = POSTINGDATE
KNUMV = PRICINGDOCUMENT
EBELN = PURCHASEORDER
WRBTR = PURCHASEORDERAMOUNT
EBELP = PURCHASEORDERITEM
BEWTP = PURCHASINGHISTORYCATEGORY
BELNR = PURCHASINGHISTORYDOCUMENT
BUZEI = PURCHASINGHISTORYDOCUMENTITEM
VGABE = PURCHASINGHISTORYDOCUMENTTYPE
GJAHR = PURCHASINGHISTORYDOCUMENTYEAR
CPUTM = PURGHISTDOCUMENTCREATIONTIME
DMBTR = PURORDAMOUNTINCOMPANYCODECRCY
BPMNG = QTYINPURCHASEORDERPRICEUNIT
MENGE = QUANTITY
BAMNG = QUANTITYINBASEUNIT
LSMNG = QUANTITYINDELIVERYQTYUNIT
LFBNR = REFERENCEDOCUMENT
LFGJA = REFERENCEDOCUMENTFISCALYEAR
LFPOS = REFERENCEDOCUMENTITEM
XWSBR = RVSLOFGOODSRECEIPTISALLOWED
EVERE = SHIPGINSTRNSUPPLIERCOMPLIANCE
MWSKZ = TAXCODE
BPWEB = VLTDGDSRCPTBLKDQTYINORDPRCUNIT
WESBB = VLTDGDSRCPTBLKDSTKQTYINORDUNIT
