EKES = I_POSUPPLIERCONFIRMATIONAPI01
CHARG = BATCH
MENGE = CONFIRMEDQUANTITY
KZDIS = CONFISRELEVANTTOMRP
ERDAT = CREATIONDATE
EZEIT = CREATIONTIME
LPEIN = DELIVDATECATEGORY
EINDT = DELIVERYDATE
VBELN = DELIVERYDOCUMENT
VBELP = DELIVERYDOCUMENTITEM
IMWRK = DELIVERYISINPLANT
UZEIT = DELIVERYTIME
HANDOVERDATE = HANDOVERDATE
HANDOVERTIME = HANDOVERTIME
LOEKZ = ISDELETED
MANDT = MANDT
EMATN = MANUFACTURERMATERIAL
MPROF = MANUFACTURERPARTPROFILE
DABMG = MRPRELEVANTQUANTITY
MAHNZ = NUMBEROFREMINDERS
ENDDATE = PERFORMANCEPERIODENDDATE
STARTDATE = PERFORMANCEPERIODSTARTDATE
EBELN = PURCHASEORDER
EBELP = PURCHASEORDERITEM
ETENS = SEQUENTIALNMBROFSUPLRCONF
SERVICEPERFORMER = SERVICEPERFORMER
ESTKZ = SUPLRCONFCREATIONCATEGORY
SUPPLIER_CONF_NO = SUPPLIERCONFIRMATION
EBTYP = SUPPLIERCONFIRMATIONCATEGORY
XBLNR = SUPPLIERCONFIRMATIONEXTNUMBER
SUPPLIER_CONF_ITEM = SUPPLIERCONFIRMATIONITEM
