EKET = I_PURORDSCHEDULELINEAPI01
CHARG = BATCH
LPEIN = DELIVDATECATEGORY
WADAT = GOODSISSUEDATE
WAUHR = GOODSISSUETIME
LDDAT = LOADINGDATE
LDUHR = LOADINGTIME
MANDT = MANDT
MBUHR = MATERIALSTAGINGTIME
MAHNZ = NOOFREMINDERSOFSCHEDULELINE
ENDDATE = PERFORMANCEPERIODENDDATE
STARTDATE = PERFORMANCEPERIODSTARTDATE
AMENG = PREVDELIVQTYOFSCHEDULELINE
MBDAT = PRODUCTAVAILABILITYDATE
EBELN = PURCHASEORDER
EBELP = PURCHASEORDERITEM
ETENR = PURCHASEORDERSCHEDULELINE
BANFN = PURCHASEREQUISITION
BNFPO = PURCHASEREQUISITIONITEM
RSNUM = RESERVATION
WEMNG = ROUGHGOODSRECEIPTQTY
MNG02 = SCHEDULELINECOMMITTEDQUANTITY
EINDT = SCHEDULELINEDELIVERYDATE
UZEIT = SCHEDULELINEDELIVERYTIME
FIXKZ = SCHEDULELINEISFIXED
WAMNG = SCHEDULELINEISSUEDQUANTITY
MENGE = SCHEDULELINEORDERQUANTITY
ESTKZ = SOURCEOFCREATION
GLMNG = STOCKTRANSFERDELIVEREDQUANTITY
ELDAT = STOLATESTPOSSIBLEGRDATE
ELUHR = STOLATESTPOSSIBLEGRTIME
TDDAT = TRANSPORTATIONPLANNINGDATE
TDUHR = TRANSPORTATIONPLANNINGTIME
