EKKN = I_PURORDACCOUNTASSIGNMENTAPI01
ZEKKN = ACCOUNTASSIGNMENTNUMBER
BUDGET_PD = BUDGETPERIOD
GSBER = BUSINESSAREA
PRZNR = BUSINESSPROCESS
FIPOS = COMMITMENTITEM
FIPOS = COMMITMENTITEMSHORTID
KOKRS = CONTROLLINGAREA
KOSTL = COSTCENTER
LSTAR = COSTCTRACTIVITYTYPE
KSTRG = COSTOBJECT
KBLNR = EARMARKEDFUNDSDOCUMENT
KBLPOS = EARMARKEDFUNDSDOCUMENTITEM
KBLPOS = EARMARKEDFUNDSITEM
ANLN2 = FIXEDASSET
FKBER = FUNCTIONALAREA
GEBER = FUND
FISTL = FUNDSCENTER
SAKTO = GLACCOUNT
WEMPF = GOODSRECIPIENTNAME
GRANT_NBR = GRANTID
LOEKZ = ISDELETED
EREKZ = ISFINALLYINVOICED
RECID = JOINTVENTURERECOVERYCODE
MANDT = MANDT
ANLN1 = MASTERFIXEDASSET
VPROZ = MULTIPLEACCTASSGMTDISTRPERCENT
APLZL = NETWORKACTIVITYINTERNALID
NAVNW = NONDEDUCTIBLEINPUTTAXAMOUNT
AUFNR = ORDERID
APLZL_ORD = ORDERINTBILLOFOPERATIONSITEM
AUFPL_ORD = ORDERINTERNALID
VPTNR = PARTNERACCOUNTNUMBER
PAOBJNR = PROFITABILITYSEGMENT_2
PRCTR = PROFITCENTER
NPLNR = PROJECTNETWORK
AUFPL = PROJECTNETWORKINTERNALID
EBELN = PURCHASEORDER
EBELP = PURCHASEORDERITEM
NETWR = PURGDOCNETAMOUNT
MENGE = QUANTITY
IMKEY = REALESTATEOBJECT
IMKEY = REINTERNALFINNUMBER
VBELN = SALESORDER
VBELP = SALESORDERITEM
VETEN = SALESORDERSCHEDULELINE
SERVICE_DOC_ID = SERVICEDOCUMENT
SERVICE_DOC_ITEM_ID = SERVICEDOCUMENTITEM
SERVICE_DOC_TYPE = SERVICEDOCUMENTTYPE
DABRZ = SETTLEMENTREFERENCEDATE
MWSKZ = TAXCODE
TXJCD = TAXJURISDICTION
ABLAD = UNLOADINGPOINTNAME
PS_PSP_PNR = WBSELEMENTINTERNALID
PS_PSP_PNR = WBSELEMENTINTERNALID_2
