EKKO = I_PURCHASEORDERAPI01
ZBD1T = CASHDISCOUNT1DAYS
ZBD1P = CASHDISCOUNT1PERCENT
ZBD2T = CASHDISCOUNT2DAYS
ZBD2P = CASHDISCOUNT2PERCENT
BUKRS = COMPANYCODE
IHREZ = CORRESPNCEXTERNALREFERENCE
UNSEZ = CORRESPNCINTERNALREFERENCE
ERNAM = CREATEDBYUSER
AEDAT = CREATIONDATE
KUNNR = CUSTOMER
WAERS = DOCUMENTCURRENCY
DPAMT = DOWNPAYMENTAMOUNT
DPDAT = DOWNPAYMENTDUEDATE
DPPCT = DOWNPAYMENTPERCENTAGEOFTOTAMT
DPTYP = DOWNPAYMENTTYPE
WKURS = EXCHANGERATE
KUFIX = EXCHANGERATEISFIXED
INCO1 = INCOTERMSCLASSIFICATION
INCO2_L = INCOTERMSLOCATION1
INCO3_L = INCOTERMSLOCATION2
INCO2 = INCOTERMSTRANSFERLOCATION
INCOV = INCOTERMSVERSION
LIFRE = INVOICINGPARTY
INTRA_EXCL = ISINTRASTATREPORTINGEXCLUDED
INTRA_REL = ISINTRASTATREPORTINGRELEVANT
SPRAS = LANGUAGE
LASTCHANGEDATETIME = LASTCHANGEDATETIME
MANDT = MANDT
ADRNR = MANUALSUPPLIERADDRESSID
ZBD3T = NETPAYMENTDAYS
ZTERM = PAYMENTTERMS
KNUMV = PRICINGDOCUMENT
KALSM = PRICINGPROCEDURE
EBELN = PURCHASEORDER
BEDAT = PURCHASEORDERDATE
BSAKZ = PURCHASEORDERSUBTYPE
BSART = PURCHASEORDERTYPE
MEMORY = PURCHASINGCOMPLETENESSSTATUS
LOEKZ = PURCHASINGDOCUMENTDELETIONCODE
STATU = PURCHASINGDOCUMENTORIGIN
EKGRP = PURCHASINGGROUP
EKORG = PURCHASINGORGANIZATION
PROCSTAT = PURCHASINGPROCESSINGSTATUS
TOTAL_STATUS_PCS = PURGAGGRGDPRODCMPLNCSUPLRSTS
TOTAL_STATUS_PMA = PURGAGGRGDPRODMARKETABILITYSTS
TOTAL_STATUS_SDS = PURGAGGRGDSFTYDATASHEETSTATUS
TOTAL_STATUS_DG = PURGPRODCMPLNCTOTDNGRSGOODSSTS
ABSGR = PURGREASONFORDOCCANCELLATION
FRGZU = PURGRELEASESEQUENCESTATUS
RLWRT = PURGRELEASETIMETOTALAMOUNT
FRGKE = RELEASECODE
FRGRL = RELEASEISNOTCOMPLETED
LIFNR = SUPPLIER
TELF1 = SUPPLIERPHONENUMBER
ANGNR = SUPPLIERQUOTATIONEXTERNALID
VERKF = SUPPLIERRESPSALESPERSONNAME
RESWK = SUPPLYINGPLANT
LLIEF = SUPPLYINGSUPPLIER
LANDS = TAXRETURNCOUNTRY
KDATE = VALIDITYENDDATE
KDATB = VALIDITYSTARTDATE
STCEG_L = VATREGISTRATIONCOUNTRY
