EKPA = I_PURCHASEORDERPARTNERAPI01
ERNAM = CREATEDBYUSER
ERDAT = CREATIONDATE
DEFPA = DEFAULTPARTNER
PERNR = EMPLOYMENTINTERNALID
MANDT = MANDT
PARZA = PARTNERCOUNTER
PARVW = PARTNERFUNCTION
WERKS = PLANT
EBELN = PURCHASEORDER
EKORG = PURCHASINGORGANIZATION
LIFN2 = SUPPLIER
PARNR = SUPPLIERCONTACT
HITYP = SUPPLIERHIERARCHYCATEGORY
LTSNR = SUPPLIERSUBRANGE
