EKPO = I_PURCHASEORDERITEMAPI01
KNTTP = ACCOUNTASSIGNMENTCATEGORY
ABELN = ALLOCATIONTABLE
ABELP = ALLOCATIONTABLEITEM
ATTYP = ARTICLECATEGORY
LMEIN = BASEUNIT
J_1BINDUST = BR_CFOPCATEGORY
J_1BOWNPRO = BR_ISPRODUCEDINHOUSE
J_1BMATORG = BR_MATERIALORIGIN
J_1BMATUSE = BR_MATERIALUSAGE
J_1BNBM = BR_NCM
STAWN = COMMODITYCODE
BUKRS = COMPANYCODE
KZVBR = CONSUMPTIONPOSTING
SATNR = CROSSPLANTCONFIGURABLEPRODUCT
KUNNR = CUSTOMER
LFRET = DELIVERYDOCUMENTTYPE
NRFHG = DISCOUNTINKINDELIGIBILITY
DPAMT = DOWNPAYMENTAMOUNT
DPDAT = DOWNPAYMENTDUEDATE
DPPCT = DOWNPAYMENTPERCENTAGEOFTOTAMT
DPTYP = DOWNPAYMENTTYPE
KBLNR = EARMARKEDFUNDS
KBLNR = EARMARKEDFUNDSDOCUMENT
KBLPOS = EARMARKEDFUNDSDOCUMENTITEM
KBLPOS = EARMARKEDFUNDSITEM
EFFWR = EFFECTIVEAMOUNT
XERSY = EVALDRCPTSETTLMTISALLOWED
EXPECTED_VALUE = EXPECTEDOVERALLLIMITAMOUNT
WEBAZ = GOODSRECEIPTDURATIONINDAYS
WEPOS = GOODSRECEIPTISEXPECTED
WEUNB = GOODSRECEIPTISNONVALUATED
LEWED = GOODSRECEIPTLATESTCREATIONDATE
BRTWR = GROSSAMOUNT
INCO1 = INCOTERMSCLASSIFICATION
INCO2_L = INCOTERMSLOCATION1
INCO3_L = INCOTERMSLOCATION2
INCO2 = INCOTERMSTRANSFERLOCATION
EAN11 = INTERNATIONALARTICLENUMBER
ISVCO = INTRASTATSERVICECODE
SOBKZ = INVENTORYSPECIALSTOCKTYPE
REPOS = INVOICEISEXPECTED
WEBRE = INVOICEISGOODSRECEIPTBASED
ELIKZ = ISCOMPLETELYDELIVERED
EREKZ = ISFINALLYINVOICED
RETPO = ISRETURNSITEM
STAPO = ISSTATISTICALITEM
RESLO = ISSUINGSTORAGELOCATION
BRGEW = ITEMGROSSWEIGHT
ABSKZ = ITEMISREJECTEDBYSUPPLIER
NTGEW = ITEMNETWEIGHT
VOLUM = ITEMVOLUME
VOLEH = ITEMVOLUMEUNIT
GEWEI = ITEMWEIGHTUNIT
MANDT = MANDT
ADRNR = MANUALDELIVERYADDRESSID
MFRNR = MANUFACTURER
EMATN = MANUFACTURERMATERIAL
MFRPN = MANUFACTURERPARTNMBR
MATNR = MATERIAL
MFRGR = MATERIALFREIGHTGROUP
MATKL = MATERIALGROUP
MTART = MATERIALTYPE
VRTKZ = MULTIPLEACCTASSGMTDISTRIBUTION
NETWR = NETAMOUNT
NETPR = NETPRICEAMOUNT
PEINH = NETPRICEQUANTITY
NAVNW = NONDEDUCTIBLEINPUTTAXAMOUNT
UMREN = ORDERITEMQTYTOBASEQTYDNMNTR
UMREZ = ORDERITEMQTYTOBASEQTYNMRTR
BPRME = ORDERPRICEUNIT
BPUMZ = ORDERPRICEUNITTOORDERUNITNMRTR
MENGE = ORDERQUANTITY
BPUMN = ORDPRICEUNITTOORDERUNITDNMNTR
LIMIT_AMOUNT = OVERALLLIMITAMOUNT
UEBTO = OVERDELIVTOLRTDLMTRATIOINPCT
KZTLF = PARTIALDELIVERYISALLOWED
TWRKZ = PARTIALINVOICEDISTRIBUTION
KO_GSBER = PARTNERREPORTEDBUSINESSAREA
PLIFZ = PLANNEDDELIVERYDURATIONINDAYS
WERKS = PLANT
KANBA = PLNDORDERREPLNMTELMNTTYPE
PRSDR = PRICEISTOBEPRINTED
MEPRF = PRICINGDATECONTROL
KOLIF = PRIORSUPPLIER
ANZPU = PRODUCTPURCHASEPOINTSQTY
PUNEI = PRODUCTPURCHASEPOINTSQTYUNIT
PRODUCTTYPE = PRODUCTTYPE
KO_PRCTR = PROFITCENTER
KONNR = PURCHASECONTRACT
KTPNR = PURCHASECONTRACTITEM
EBELN = PURCHASEORDER
BSTYP = PURCHASEORDERCATEGORY
EBELP = PURCHASEORDERITEM
PSTYP = PURCHASEORDERITEMCATEGORY
TXZ01 = PURCHASEORDERITEMTEXT
UNIQUEID = PURCHASEORDERITEMUNIQUEID
MEINS = PURCHASEORDERQUANTITYUNIT
BANFN = PURCHASEREQUISITION
BNFPO = PURCHASEREQUISITIONITEM
LOEKZ = PURCHASINGDOCUMENTDELETIONCODE
STATU = PURCHASINGDOCUMENTITEMORIGIN
INFNR = PURCHASINGINFORECORD
BSGRU = PURCHASINGORDERREASON
UEBPO = PURCHASINGPARENTITEM
PRDAT = PURGDOCPRICEDATE
ABMNG = PURGDOCRELEASEORDERQUANTITY
NOVET = PURGITEMISBLOCKEDFORDELIVERY
STATUS_DG = PURGPRODCMPLNCDNGRSGOODSSTATUS
STATUS_PCS = PURGPRODCMPLNCSUPPLIERSTATUS
STATUS_PMA = PURGPRODUCTMARKETABILITYSTATUS
STATUS_SDS = PURGSAFETYDATASHEETSTATUS
ADRN2 = REFERENCEDELIVERYADDRESSID
SGT_RCAT = REQUIREMENTSEGMENT
BEDNR = REQUIREMENTTRACKING
AFNAM = REQUISITIONERNAME
AKTNR = RETAILPROMOTION
SERVICEPERFORMER = SERVICEPERFORMER
EVERS = SHIPPINGINSTRUCTION
VSART = SHIPPINGTYPE
INSMK = STOCKTYPE
LGORT = STORAGELOCATION
EMLIF = SUBCONTRACTOR
ITCONS = SUBCONTRGCOMPISREALTMECNSMD
KZWI1 = SUBTOTAL1AMOUNT
KZWI2 = SUBTOTAL2AMOUNT
KZWI3 = SUBTOTAL3AMOUNT
KZWI4 = SUBTOTAL4AMOUNT
KZWI5 = SUBTOTAL5AMOUNT
KZWI6 = SUBTOTAL6AMOUNT
BSTAE = SUPPLIERCONFIRMATIONCONTROLKEY
LBLKZ = SUPPLIERISSUBCONTRACTOR
IDNLF = SUPPLIERMATERIALNUMBER
LTSNR = SUPPLIERSUBRANGE
MWSKZ = TAXCODE
TXJCD = TAXJURISDICTION
UNTTO = UNDERDELIVTOLRTDLMTRATIOINPCT
UEBTK = UNLIMITEDOVERDELIVERYISALLOWED
BWTTY = VALUATIONCATEGORY
BWTAR = VALUATIONTYPE
