EORD = I_MPPURCHASINGSOURCEITEM
ERNAM = CREATEDBYUSERNAME
ERDAT = CREATIONDATE
SOBKZ = INVENTORYSPECIALSTOCKTYPE
FRESW = ISSGPLANTISFIXED
LASTCHANGEDATETIME = LASTCHANGEDATETIME
MANDT = MANDT
EMATN = MANUFACTURERMATERIAL
MATNR = MATERIAL
AUTET = MRPSOURCINGCONTROL
MEINS = ORDERQUANTITYUNIT
LOGSY = ORIGINSYSTEM
WERKS = PLANT
EBELN = PURCHASEOUTLINEAGREEMENT
EBELP = PURCHASEOUTLINEAGREEMENTITEM
VRTYP = PURCHASINGDOCUMENTCATEGORY
EKORG = PURCHASINGORGANIZATION
FEBEL = PUROUTLINEAGREEMENTISFIXED
ZEORD = SOURCELISTRECORD
EORTP = SOURCELISTRECORDCATEGORY
NOTKZ = SOURCEOFSUPPLYISBLOCKED
LIFNR = SUPPLIER
FLIFN = SUPPLIERISFIXED
RESWK = SUPPLYINGPLANT
BDATU = VALIDITYENDDATE
VDATU = VALIDITYSTARTDATE
