EQUK = I_PURGQUOTAARRGMTAPI01
ERNAM = CREATEDBYUSER
ERDAT = CREATIONDATE
CHANGEDON = LASTCHANGEDATETIME
MANDT = MANDT
MATNR = MATERIAL
SCMNG = MINQTYFORSPLTQUOTA
WERKS = PLANT
QUNUM = QUOTAARRANGEMENT
BDATU = VALIDITYENDDATE
VDATU = VALIDITYSTARTDATE
