LFA1 = I_PURGQUOTAARRGMTITEMAPI01
MANDT = MANDT
EMATN = MANUFACTURERMATERIAL
MAXLS = MATERIALMAXLOTSIZEQUANTITY
MINLS = MATERIALMINLOTSIZEQUANTITY
BESKZ = MATERIALPROCUREMENTCATEGORY
SOBES = MATERIALPROCUREMENTTYPE
RDPRF = MATERIALROUNDINGPROFILE
ABRMG = MAXIMUMRELEASEQUANTITY
ABANZ = NUMBEROFPERIODSPERRELQUANTITY
PLIFZ = PLANNEDDELIVERYDURATIONINDAYS
VERID = PRODUCTIONVERSION
QUOTE = PURCHASINGSOURCEQUOTA
QUMNG = QUOTAALLOCATEDQUANTITY
QUNUM = QUOTAARRANGEMENT
QUPOS = QUOTAARRANGEMENTITEM
QUBMG = QUOTABASEQUANTITY
PREIH = QUOTADETERMINATIONPRIORITY
MAXMG = QUOTAMAXIMUMQUANTITY
ABPER = QUOTARELEASEPERIODTYPE
KZEIN = SOURCEOFSUPPLYISASSIGNEDONCE
LIFNR = SUPPLIER
BEWRK = SUPPLYINGPLANT
