FKKVKP = I_CONTRACTACCOUNTPARTNER
ADRNB = ADDRESSID
ABWVK = ALTVCONTRACTACCTFORCOLLVBILLS
GSBER = BUSINESSAREA
GPART = BUSINESSPARTNER
BUPLA = BUSINESSPLACE
KOFIZ_SD = CAACCOUNTDETERMINATIONCODE
FDZTG = CAADDITIONALDAYSFORCASHMGMT
ADRRA = CAADDRESSIDOFALTERNATIVEPAYEE
ADRRE = CAADDRESSIDOFALTERNATIVEPAYER
ADRMA = CAADDRESSIDOFALTVDUNRECIPIENT
ADRRH = CAADDRESSIDOFALTVINVOICERCPNT
ADRJDC = CAADDRESSIDOFJURISDICTIONCODE
DEF_REC = CAALTERNATIVECORRESPNCRCPNT
ABWMA = CAALTERNATIVEDUNNINGRECIPIENT
ABWRH = CAALTERNATIVEINVOICERECIPIENT
ABWRA = CAALTERNATIVEPAYEE
ABWRE = CAALTERNATIVEPAYER
BEGRU = CAAUTHORIZATIONGROUP
EBVTY = CABANKIDFORINCOMINGPAYMENTS
ABVTY = CABANKIDFOROUTGOINGPAYMENTS
INV_CYCLE = CABILLGCYCLE
EXVKO = CABPREFERENCENUMBER
GPART_INVLIST = CABUSINESSPARTNERFORINVCGLIST
GPARV = CABUSINESSPARTNERFORPAYMENT
GPART_INV = CABUSINESSPARTNERFORPOSTING
BPL_XPOCL = CABUSINESSPARTNERLOCK
BPL_TDATE = CABUSINESSPARTNERLOCKENDDATE
BPL_FDATE = CABUSINESSPARTNERLOCKSTARTDATE
BPL_XADDL = CABUSPARTNERADDLLOCKEXSTCCODE
BPL_XPOCL = CABUSPARTNERPOSTGLOCKEXSTCCODE
VERTYP = CACLEARINGCATEGORY
AUGRS_DEF = CACLEARINGRESTRICTION
PERSR = CACOLLECTIONSCLERK
CPERS = CACOLLECTIONSCONTACTPERSON
CMGRP = CACOLLECTIONSMASTERDATAGROUP
STRAT = CACOLLECTIONSTRATEGY
OPBUK = CACOMPANYCODEGROUP
DEF_REC_IND = CACORRESPONDENCEACTIVITYCODE
CORR_MAHNV = CACORRESPONDENCEDUNNINGPROCED
COPRC = CACORRESPONDENCEVARIANT
DDLCU = CACURRENCYFORDIRECTDEBITLIMIT
AUGRS_DEF = CADEFAULTCLEARINGRSTRCNCODE
INV_FORM_DET_KEY = CADETNCODEFORALTVINVOICEFORM
DDLAM = CADIRECTDEBITLIMIT
DDLXG = CADIRECTDEBITLIMITCALCMODE
MGRUP = CADUNNINGNOTICEGROUP
MAHNV = CADUNNINGPROCEDURE
EIGBV = CAHOUSEBANKREFERENCE
IKEY = CAINTERESTCODE
INV_CATEGORY = CAINVCGCATEGORY
INV_SCHEDULE = CAINVCGSCHEDULE
INV_CYCLE_DAY = CALASTDAYOFBILLINGPERIOD
MAKEY = CAMASTERAGREEMENT
DDLNM = CANMBRMNTHSFORDIRECTDEBITLIMIT
PTSRL = CAPARTNERSETTLEMENTRULE
CCARD_ID = CAPAYMENTCARDIDFORINCOMINGPAYT
CCARD_OUT = CAPAYMENTCARDIDFOROUTGOINGPAYT
EZAWE = CAPAYMENTMETHODFORINCGPAYMENT
AZAWE = CAPAYMENTMETHODFOROUTGPAYMENT
VKPBZ = CARELATIONSHIPOFBPTOCONTRACCT
FDGRP = CASHPLANNINGGROUP
STDBK = CASTANDARDCOMPANYCODE
INV_CYCLE_START = CASTARTDATEFORBILLINGPERIOD
INV_CURR = CATARGETCURRENCYFORINVOICING
TOGRU = CATOLERANCEGROUP
QSSKZ_E = CAWHLDGTAXCODEINCOMINGPAYT
QSSKZ_A = CAWHLDGTAXCODEOUTGOINGPAYT
VKONT = CONTRACTACCOUNT
VKONT_INVLIST = CONTRACTACCOUNTFORINVCGLIST
VKONV = CONTRACTACCOUNTFORPAYMENT
VKONT_INV = CONTRACTACCOUNTFORPOSTING
VKBEZ = CONTRACTACCOUNTNAME
ERNAM = CREATEDBYUSER
ERDAT = CREATIONDATE
ERTIM = CREATIONTIME
LOEVM = ISMARKEDFORDELETION
AEDATP = LASTCHANGEDATE
AENAMP = LASTCHANGEDBYUSER
AETIMP = LASTCHANGETIME
MANDT = MANDT
VBUND = PARTNERCOMPANY
ZAHLKOND = PAYMENTCONDITION
MNDID = SEPAMANDATE
LANDL = SUPPLYINGCOUNTRY
TXJCD = TAXJURISDICTION
QSZDT = VALDTYDATEFORWHLDGTAXEXMPCERT
QSZNR = WITHHOLDINGTAXCERTIFICATE
