FKKVK = I_CONTRACTACCOUNTHEADER
APPLK = CAAPPLICATIONAREA
VKONT = CONTRACTACCOUNT
VKTYP = CONTRACTACCOUNTCATEGORY
VKONA = CONTRACTACCOUNTEXTREFERENCE
VKBEZ = CONTRACTACCOUNTNAME
ERNAM = CREATEDBYUSER
ERDAT = CREATIONDATE
ERTIM = CREATIONTIME
LOEVM = ISMARKEDFORDELETION
AEDAT = LASTCHANGEDATE
AENAM = LASTCHANGEDBYUSER
AETIM = LASTCHANGETIME
MANDT = MANDT
