KNA1 = I_CUSTOMER
ADRNR = ADDRESSID
XZEMP = ALTERNATIVEPAYEEISALLOWED
KNRZA = ALTERNATIVEPAYERACCOUNT
BEGRU = AUTHORIZATIONGROUP
FAKSD = BILLINGISBLOCKEDFORCUSTOMER
SUFRAMA = BR_SUFRAMACODE
J_1KFTBUS = BUSINESSTYPE
CITYC = CITYCODE
ORT01 = CITYNAME
LAND1 = COUNTRY
COUNC = COUNTY
ERNAM = CREATEDBYUSER
ERDAT = CREATIONDATE
KUNNR = CUSTOMER
KTOKD = CUSTOMERACCOUNTGROUP
KUKLA = CUSTOMERCLASSIFICATION
KDKG1 = CUSTOMERCONDITIONGROUP1
KDKG2 = CUSTOMERCONDITIONGROUP2
KDKG3 = CUSTOMERCONDITIONGROUP3
KDKG4 = CUSTOMERCONDITIONGROUP4
KDKG5 = CUSTOMERCONDITIONGROUP5
KONZS = CUSTOMERCORPORATEGROUP
EXABL = CUSTOMERHASUNLOADINGPOINT
KNAZK = CUSTOMERWORKINGTIMECALENDAR
DATA_CTRLR1 = DATACONTROLLER1
DATA_CTRLR10 = DATACONTROLLER10
DATA_CTRLR2 = DATACONTROLLER2
DATA_CTRLR3 = DATACONTROLLER3
DATA_CTRLR4 = DATACONTROLLER4
DATA_CTRLR5 = DATACONTROLLER5
DATA_CTRLR6 = DATACONTROLLER6
DATA_CTRLR7 = DATACONTROLLER7
DATA_CTRLR8 = DATACONTROLLER8
DATA_CTRLR9 = DATACONTROLLER9
XDCSET = DATACONTROLLERSET
DTAMS = DATAMEDIUMEXCHANGEINDICATOR
LOEVM = DELETIONINDICATOR
DELIVERY_DATE_RULE = DELIVERYDATETYPERULE
LIFSD = DELIVERYISBLOCKED
BAHNE = EXPRESSTRAINSTATIONNAME
TELFX = FAXNUMBER
FISKN = FISCALADDRESS
KATR1 = FREEDEFINEDATTRIBUTE01
KATR2 = FREEDEFINEDATTRIBUTE02
KATR3 = FREEDEFINEDATTRIBUTE03
KATR4 = FREEDEFINEDATTRIBUTE04
KATR5 = FREEDEFINEDATTRIBUTE05
KATR6 = FREEDEFINEDATTRIBUTE06
KATR7 = FREEDEFINEDATTRIBUTE07
KATR8 = FREEDEFINEDATTRIBUTE08
KATR9 = FREEDEFINEDATTRIBUTE09
KATR10 = FREEDEFINEDATTRIBUTE10
BRSCH = INDUSTRY
BRAN1 = INDUSTRYCODE1
BRAN2 = INDUSTRYCODE2
BRAN3 = INDUSTRYCODE3
BRAN4 = INDUSTRYCODE4
BRAN5 = INDUSTRYCODE5
J_1KFTIND = INDUSTRYTYPE
BBBNR = INTERNATIONALLOCATIONNUMBER1
BBSNR = INTERNATIONALLOCATIONNUMBER2
BUBKZ = INTERNATIONALLOCATIONNUMBER3
CVP_XBLCK = ISBUSINESSPURPOSECOMPLETED
DEAR1 = ISCOMPETITOR
DEAR6 = ISCONSUMER
XCPDK = ISONETIMEACCOUNT
DEAR3 = ISSALESPROSPECT
SPRAS = LANGUAGE
MANDT = MANDT
STKZN = NFPARTNERISNATURALPERSON
NIELS = NIELSENREGION
AUFSD = ORDERISBLOCKEDFORCUSTOMER
NAME1 = ORGANIZATIONBPNAME1
NAME2 = ORGANIZATIONBPNAME2
SPERZ = PAYMENTISBLOCKEDFORCUSTOMER
PAYTRSN = PAYMENTREASON
PSTLZ = POSTALCODE
SPERR = POSTINGISBLOCKED
REGIO = REGION
FITYP = RESPONSIBLETYPE
SORTL = SORTFIELD
STRAS = STREETNAME
LIFNR = SUPPLIER
J_1KFREPRE = TAXINVOICEREPRESENTATIVENAME
TXJCD = TAXJURISDICTION
STCD1 = TAXNUMBER1
STCD2 = TAXNUMBER2
STCD3 = TAXNUMBER3
STCD4 = TAXNUMBER4
STCD5 = TAXNUMBER5
STCD6 = TAXNUMBER6
STCDT = TAXNUMBERTYPE
TELF1 = TELEPHONENUMBER1
TELF2 = TELEPHONENUMBER2
VBUND = TRADINGPARTNER
BAHNS = TRAINSTATIONNAME
CONSOLIDATE_INVOICE = TW_COLLVBILLINGISSUPPORTED
STKZU = VATLIABILITY
STCEG = VATREGISTRATION
