KNB1 = I_CUSTOMERCOMPANY
EIKTO = ACCOUNTBYCUSTOMER
BUSAB = ACCOUNTINGCLERK
TLFXS = ACCOUNTINGCLERKFAXNUMBER
INTAD = ACCOUNTINGCLERKINTERNETADDRESS
TLFNS = ACCOUNTINGCLERKPHONENUMBER
CESSION_KZ = ACCTSRECEIVABLEPLEDGINGCODE
KNRZB = ALTERNATIVEPAYERACCOUNT
TOGRU = APARTOLERANCEGROUP
BEGRU = AUTHORIZATIONGROUP
WAKON = BILLEXCHCHARGEPAYMENTTERMS
XAUSZ = BPPERIODICACCOUNTSTATEMENT
EKVBD = BUYINGGROUPACCOUNTNUMBER
FDGRV = CASHPLANNINGGROUP
KULTG = CHECKPAIDDURATIONINDAYS
PERKZ = COLLECTIVEINVOICEVARIANT
BUKRS = COMPANYCODE
GUZTE = CREDITMEMOPAYMENTTERMS
KUNNR = CUSTOMER
KVERM = CUSTOMERACCOUNTNOTE
KNRZE = CUSTOMERHEADOFFICE
ZAHLS = CUSTOMERPAYMENTBLOCKINGREASON
XVERR = CUSTOMERSUPPLIERCLEARINGISUSED
ALTKN = CUSTPREVIOUSMASTERRECORDNUMBER
LOEVM = DELETIONINDICATOR
NODEL = DELETIONISBLOCKED
MGRUP = DUNNINGNOTICEGROUP
HBKID = HOUSEBANK
VZSKZ = INTERESTCALCULATIONCODE
ZINDT = INTERESTCALCULATIONDATE
ZINRT = INTRSTCALCFREQUENCYINMONTHS
CVP_XBLCK_B = ISBUSINESSPURPOSECOMPLETED
XDEZV = ISTOBELOCALLYPROCESSED
XPORE = ITEMISTOBEPAIDSEPARATELY
URLID = KNOWNORNEGOTIATEDLEAVE
DATLZ = LASTINTERESTCALCRUNDATE
ZUAWA = LAYOUTSORTINGRULE
LOCKB = LOCKBOXINTERNALID
MANDT = MANDT
ZAHLS = PAYMENTBLOCKINGREASON
PAYMENTCLEARINGGRPID = PAYMENTCLEARINGGROUP
ZWELS = PAYMENTMETHODSLIST
UZAWE = PAYMENTMETHODSUPPLEMENT
PAYTRSN = PAYMENTREASON
ZTERM = PAYMENTTERMS
XEDIP = PAYTADVICEISSENTBYEDI
PERNR = PERSONNELNUMBER
SPERR = PHYSICALINVENTORYBLOCKIND
AKONT = RECONCILIATIONACCOUNT
XZVER = RECORDPAYMENTHISTORYINDICATOR
FRGRP = SUPPLIERRELEASEGROUP
ZSABE = USERATCUSTOMER
US_CHAP4_STATUS_CODE = US_CHAPTER4STATUSCODE
US_FATCA_IND = US_FRGNACCTTAXFILINGISREQUIRED
US_REC_COUNTRY = US_FRGNACCTTAXRCPNTCNTRY
US_PARTNERSHIP_IND = US_FRGNRECIPIENTHASPARTNERSHIP
US_W8_RECVDATE = US_FW8BENRECEIVEDATE
US_W9_RECVDATE = US_FW9RECEIVEDATE
US_GIIN = US_GLOBINTERMEDIARYIDNNUMBER
US_LOB_CODE = US_LOBTREATYCODE
US_FTID = US_RECIPIENTFOREIGNTAXID
US_TIN_NOTICE = US_SECONDTINNOTICEISISSUED
WBRSL = VALUEADJUSTMENTKEY
QLAND = WITHHOLDINGTAXCOUNTRY
