KNB5 = I_CUSTOMERDUNNING
BUKRS = COMPANYCODE
KUNNR = CUSTOMER
MABER = DUNNINGAREA
MANSP = DUNNINGBLOCK
BUSAB = DUNNINGCLERK
MAHNS = DUNNINGLEVEL
MAHNA = DUNNINGPROCEDURE
KNRMA = DUNNINGRECIPIENT
MADAT = LASTDUNNEDON
GMVDT = LEGDUNNINGPROCEDUREON
MANDT = MANDT
