KNBK = I_BUSINESSPARTNERBANK
BANKN = BANKACCOUNT
KOINH = BANKACCOUNTHOLDERNAME
ACCNAME = BANKACCOUNTNAME
BKREF = BANKACCOUNTREFERENCETEXT
BKONT = BANKCONTROLKEY
BANKS = BANKCOUNTRYKEY
BKVID = BANKIDENTIFICATION
BANKL = BANKNUMBER
BK_MOVE_DATE = BPBANKDETAILSCHANGEDATE
MOVE_BKVID = BPBANKDETAILSCHANGETARGETID
PROTECT = BPBANKISPROTECTED
BP_BANK_GUID = BPBANKUUID
PARTNER = BUSINESSPARTNER
BKEXT = BUSINESSPARTNEREXTERNALBANKID
XEZER = COLLECTIONAUTHIND
MANDT = MANDT
BK_VALID_TO = VALIDITYENDDATE
BK_VALID_FROM = VALIDITYSTARTDATE