KNVK = I_CONTACTPERSON
PARNR = CONTACTPERSON
ABTNR = CONTACTPERSONDEPARTMENT
PAFKT = CONTACTPERSONFUNCTION
KUNNR = CUSTOMER
CVP_XBLCK_K = ISBUSINESSPURPOSECOMPLETED
MANDT = MANDT
PRSNR = PERSONNUMBER
SORTL = SEARCHTERM
SORTL = SEARCHTERM1
LIFNR = SUPPLIER
