KNVP = I_CUSTSALESPARTNERFUNC
ADRNR = ADDRESSID
PARNR = CONTACTPERSON
KUNNR = CUSTOMER
KNREF = CUSTOMERPARTNERDESCRIPTION
DEFPA = DEFAULTPARTNER
VTWEG = DISTRIBUTIONCHANNEL
SPART = DIVISION
MANDT = MANDT
PARZA = PARTNERCOUNTER
PARVW = PARTNERFUNCTION
PERNR = PERSONNELNUMBER
VKORG = SALESORGANIZATION
LIFNR = SUPPLIER
