KNVV = I_CUSTOMERSALESAREA
EIKTO = ACCOUNTBYCUSTOMER
KVGR1 = ADDITIONALCUSTOMERGROUP1
KVGR2 = ADDITIONALCUSTOMERGROUP2
KVGR3 = ADDITIONALCUSTOMERGROUP3
KVGR4 = ADDITIONALCUSTOMERGROUP4
KVGR5 = ADDITIONALCUSTOMERGROUP5
BEGRU = AUTHORIZATIONGROUP
FAKSD = BILLINGISBLOCKEDFORCUSTOMER
AUTLF = COMPLETEDELIVERYISDEFINED
KKBER = CREDITCONTROLAREA
WAERS = CURRENCY
AGREL = CUSTISRLVTFORSETTLMTMGMT
KUNNR = CUSTOMER
KLABC = CUSTOMERABCCLASSIFICATION
KTGRD = CUSTOMERACCOUNTASSIGNMENTGROUP
KDGRP = CUSTOMERGROUP
BOKRE = CUSTOMERISREBATERELEVANT
ZTERM = CUSTOMERPAYMENTTERMS
KONDA = CUSTOMERPRICEGROUP
KALKS = CUSTOMERPRICINGPROCEDURE
VERSG = CUSTOMERSTATISTICSGROUP
PVKSM = CUSTPRODPROPOSALPROCEDURE
LOEVM = DELETIONINDICATOR
LIFSD = DELIVERYISBLOCKEDFORCUSTOMER
LPRIO = DELIVERYPRIORITY
VTWEG = DISTRIBUTIONCHANNEL
SPART = DIVISION
KURST = EXCHANGERATETYPE
INCO1 = INCOTERMSCLASSIFICATION
INCO2_L = INCOTERMSLOCATION1
INCO3_L = INCOTERMSLOCATION2
INCO4_KEY = INCOTERMSSUPCHNDVTGLOCADDLUUID
INCO2_KEY = INCOTERMSSUPCHNLOC1ADDLUUID
INCO3_KEY = INCOTERMSSUPCHNLOC2ADDLUUID
INCO2 = INCOTERMSTRANSFERLOCATION
INCOV = INCOTERMSVERSION
PRFRE = INSPSBSTHASNOTIMEORQUANTITY
PERFK = INVOICEDATE
PERRL = INVOICELISTSCHEDULE
CVP_XBLCK_V = ISBUSINESSPURPOSECOMPLETED
AWAHR = ITEMORDERPROBABILITYINPERCENT
MANDT = MANDT
MRNKZ = MANUALINVOICEMAINTISRELEVANT
ANTLF = MAXNMBROFPARTIALDELIVERY
KZAZU = ORDERCOMBINATIONISALLOWED
AUFSD = ORDERISBLOCKEDFORCUSTOMER
UEBTO = OVERDELIVTOLRTDLMTRATIOINPCT
KZTLF = PARTIALDELIVERYISALLOWED
KABSS = PAYMENTGUARANTEEPROCEDURE
ZTERM = PAYMENTTERMS
PLTYP = PRICELISTTYPE
MEGRU = PRODUCTUNITGROUP
FSH_KVGR10 = RETAILADDITIONALCUSTOMERGRP10
FSH_KVGR6 = RETAILADDITIONALCUSTOMERGRP6
FSH_KVGR7 = RETAILADDITIONALCUSTOMERGRP7
FSH_KVGR8 = RETAILADDITIONALCUSTOMERGRP8
FSH_KVGR9 = RETAILADDITIONALCUSTOMERGRP9
CASSD = SALESBLOCKFORCUSTOMER
BZIRK = SALESDISTRICT
VKGRP = SALESGROUP
VSORT = SALESITEMPROPOSAL
VKBUR = SALESOFFICE
VKORG = SALESORGANIZATION
VSBED = SHIPPINGCONDITION
PODKZ = SLSDOCISRLVTFORPROOFOFDELIV
UEBTK = SLSUNLMTDOVRDELIVISALLWD
AGREL = SUPLRISRLVTFORSETTLMTMGMT
VWERK = SUPPLYINGPLANT
UNTTO = UNDERDELIVTOLRTDLMTRATIOINPCT
