KONH = I_SLSPRCGCONDITIONRECORD
VALTG = ADDITIONALVALUEDAYS
MEINS = BASEUNIT
ANZAUF = CNDNMAXNUMBEROFSALESORDERS
KWAEH = CONDITIONALTERNATIVECURRENCY
KAPPL = CONDITIONAPPLICATION
KRECH = CONDITIONCALCULATIONTYPE
CNDN_CHGREASON = CONDITIONCHANGEREASON
KZNEP = CONDITIONEXCLUSION
LOEVM_KO = CONDITIONISDELETED
KPEIN = CONDITIONQUANTITY
KMEIN = CONDITIONQUANTITYUNIT
KONWA = CONDITIONRATEVALUEUNIT
KNUMH = CONDITIONRECORD
KFRST = CONDITIONRELEASESTATUS
KSTBW = CONDITIONSCALEAMOUNT
KONWS = CONDITIONSCALEAMOUNTCURRENCY
KSTBM = CONDITIONSCALEQUANTITY
KONMS = CONDITIONSCALEQUANTITYUNIT
KOPOS = CONDITIONSEQUENTIALNUMBER
KOTABNR = CONDITIONTABLE
MWSK1 = CONDITIONTAXCODE
KNUMT = CONDITIONTEXTID
KUMNE = CONDITIONTOBASEQTYDNMNTR
KUMZA = CONDITIONTOBASEQTYNMRTR
KSCHL = CONDITIONTYPE
DATBI = CONDITIONVALIDITYENDDATE
DATAB = CONDITIONVALIDITYSTARTDATE
MWSK2 = CONDITIONWITHHOLDINGTAXCODE
ERNAM = CREATEDBYUSER
ERDAT = CREATIONDATE
KLF_STG = INCREMENTALSCALE
UPD_TMSTMP = LASTCHANGEDATETIME
LICDT = LICENSEGRANTDATE
MANDT = MANDT
KOMXWRT = MAXIMUMCONDITIONAMOUNT
MXKBAS = MAXIMUMCONDITIONBASISVALUE
MIKBAS = MINIMUMCONDITIONBASISVALUE
ZTERM = PAYMENTTERMS
KNUMH_PREV_APRVD = PREVAPPROVEDCONDITIONRECORD
KZBZG = PRICINGSCALEBASIS
KLF_KAL = PRICINGSCALELINE
STFKZ = PRICINGSCALETYPE
PRICEAPPROVALREQUEST = SALESPRICEAPPROVALREQUEST
LICNO = TAXEXEMPTIONLICENSE