LFA1 = I_SUPPLIER
SPERR = ACCOUNTISBLOCKEDFORPOSTING
ADRNR = ADDRESSID
LNRZA = ALTERNATIVEPAYEEACCOUNTNUMBER
XZEMP = ALTERNATIVEPAYEEISALLOWED
BEGRU = AUTHORIZATIONGROUP
AU_IND_UNDER_18 = AU_INDIVIDUALISUNDER18
AU_PARTNER_WITHOUT_GAIN = AU_PARTNERISSUPPLYWITHOUTGAIN
AU_CARRYING_ENT = AU_PAYERISPAYINGTOCARRYONENT
AU_PAYMENT_NOT_EXCEED_75 = AU_PAYMENTISEXCEEDING75
AU_PAYMENT_EXEMPT = AU_PAYMENTISINCOMEEXEMPTED
AU_WHOLLY_INP_TAXED = AU_PAYMENTISWHOLLYINPUTTAXED
AU_NOT_ENTITLED_ABN = AU_SUPPLIERISENTITLEDTOABN
AU_PRIVATE_HOBBY = AU_SUPPLYISMADEASPRIVATEHOBBY
AU_DOMESTIC_NATURE = AU_SUPPLYMADEISOFDMSTCNATURE
GBDAT = BIRTHDATE
STKZA = BPISEQUALIZATIONTAXSUBJECT
J_1IPANREF = BPPANREFERENCENUMBER
J_1IPANVALDT = BPPANVALIDFROMDATE
TAXBS = BRSPCFCTAXBASEPERCENTAGECODE
IPISP = BR_TAXISSPLIT
J_1IPANNO = BUSINESSPARTNERPANNUMBER
J_1KFTBUS = BUSINESSTYPE
ORT01 = CITYNAME
SUBMI_RELEVANT = COLLECTIVENUMBERINGISRELEVANT
LAND1 = COUNTRY
ERNAM = CREATEDBYUSER
ERDAT = CREATIONDATE
KUNNR = CUSTOMER
DATA_CTRLR1 = DATACONTROLLER1
DATA_CTRLR10 = DATACONTROLLER10
DATA_CTRLR2 = DATACONTROLLER2
DATA_CTRLR3 = DATACONTROLLER3
DATA_CTRLR4 = DATACONTROLLER4
DATA_CTRLR5 = DATACONTROLLER5
DATA_CTRLR6 = DATACONTROLLER6
DATA_CTRLR7 = DATACONTROLLER7
DATA_CTRLR8 = DATACONTROLLER8
DATA_CTRLR9 = DATACONTROLLER9
XDCSET = DATACONTROLLERSET
DTAWS = DATAEXCHANGEINSTRUCTIONKEY
DTAMS = DATAMEDIUMEXCHANGEINDICATOR
LOEVM = DELETIONINDICATOR
PLKAL = FACTORYCALENDAR
TELFX = FAXNUMBER
FISKN = FISCALADDRESS
ANRED = FORMOFADDRESS
BRSCH = INDUSTRY
J_1KFTIND = INDUSTRYTYPE
BBBNR = INTERNATIONALLOCATIONNUMBER1
BBSNR = INTERNATIONALLOCATIONNUMBER2
BUBKZ = INTERNATIONALLOCATIONNUMBER3
VEN_CLASS = IN_GSTSUPPLIERCLASSIFICATION
CVP_XBLCK = ISBUSINESSPURPOSECOMPLETED
STKZN = ISNATURALPERSON
XCPDK = ISONETIMEACCOUNT
WEORA = ISTOBEACCEPTEDATORIGIN
MANDT = MANDT
NAME1 = ORGANIZATIONBPNAME1
NAME2 = ORGANIZATIONBPNAME2
SPERZ = PAYMENTISBLOCKEDFORSUPPLIER
PAYTRSN = PAYMENTREASON
ESRNR = PAYTSLIPWTHREFSUBSCRIBER
TELF1 = PHONENUMBER1
TELF2 = PHONENUMBER2
PSTLZ = POSTALCODE
SPERR = POSTINGISBLOCKED
SPERM = PURCHASINGISBLOCKED
KTOCK = REFERENCEACCOUNTGROUP
REGIO = REGION
FITYP = RESPONSIBLETYPE
ACTSS = SOCIALINSURANCEACTIVITYCODE
SORTL = SORTFIELD
STRAS = STREETNAME
CARRIER_CONF = SUPLRCARRIERCONFIRMISEXPECTED
EMNFR = SUPLRMANUFACTUREREXTERNALNAME
PODKZB = SUPLRPROOFOFDELIVRLVTCODE
QSSYSDAT = SUPLRQLTYINPROCMTCERTFNVALIDTO
QSSYS = SUPLRQUALITYMANAGEMENTSYSTEM
FISKU = SUPLRTAXAUTHORITYACCOUNTNUMBER
LIFNR = SUPPLIER
KTOKK = SUPPLIERACCOUNTGROUP
DLGRP = SUPPLIERAGENTPROCEDUREGROUP
NODEL = SUPPLIERCENTRALDELETIONISBLOCK
KONZS = SUPPLIERCORPORATEGROUP
SFRGR = SUPPLIERFWDAGENTFREIGHTGROUP
WERKR = SUPPLIERISPLANTRELEVANT
LTSNA = SUPPLIERISSUBRANGERELEVANT
SPRAS = SUPPLIERLANGUAGE
WERKS = SUPPLIERPLANT
SPERQ = SUPPLIERPROCUREMENTBLOCK
PROFS = SUPPLIERPROFESSION
SCHEDULING_TYPE = SUPPLIERSCHEDULINGPROCEDURE
STAGING_TIME = SUPPLIERSTAGINGTIMEINDAYS
SCACD = SUPPLIERSTANDARDCARRIERACCESS
TRANSPORT_CHAIN = SUPPLIERTRANSPORTATIONCHAIN
REGSS = SUPPLISSOCIALINSURANCEREGTRD
J_1KFREPRE = TAXINVOICEREPRESENTATIVENAME
TXJCD = TAXJURISDICTION
STCD1 = TAXNUMBER1
STCD2 = TAXNUMBER2
STCD3 = TAXNUMBER3
STCD4 = TAXNUMBER4
STCD5 = TAXNUMBER5
STCD6 = TAXNUMBER6
STENR = TAXNUMBERRESPONSIBLE
STCDT = TAXNUMBERTYPE
VBUND = TRADINGPARTNER
BAHNS = TRAINSTATIONNAME
STGDL = TRANSPSERVICEAGENTSTSTCGRP
CRN = UK_COMPANYREGISTRATIONNUMBER
CATEG = UK_CONTRACTORBUSINESSTYPE
PARTNER_UTR = UK_PARTNERTAXREFERENCE
PARTNER_NAME = UK_PARTNERTRADINGNAME
VFNUM = UK_VERIFICATIONNUMBER
STATUS = UK_VERIFICATIONSTATUS
VFNID = UK_VERIFIEDTAXSTATUS
STKZU = VATLIABILITY
STCEG = VATREGISTRATION
