LFB1 = I_SUPPLIERCOMPANY
BUSAB = ACCOUNTINGCLERK
TLFXS = ACCOUNTINGCLERKFAXNUMBER
INTAD = ACCOUNTINGCLERKINTERNETADDRESS
TLFNS = ACCOUNTINGCLERKPHONENUMBER
LNRZB = ALTERNATIVEPAYEE
TOGRU = APARTOLERANCEGROUP
BEGRU = AUTHORIZATIONGROUP
WEBTR = BILLOFEXCHLMTAMTINCOCODECRCY
FDGRV = CASHPLANNINGGROUP
KULTG = CHECKPAIDDURATIONINDAYS
XVERR = CLEARCUSTOMERSUPPLIER
BUKRS = COMPANYCODE
GUZTE = CREDITMEMOPAYMENTTERMS
XVERR = CUSTOMERSUPPLIERCLEARINGISUSED
LOEVM = DELETIONINDICATOR
NODEL = DELETIONISBLOCKED
HBKID = HOUSEBANK
VZSKZ = INTERESTCALCULATIONCODE
ZINDT = INTERESTCALCULATIONDATE
ZINRT = INTRSTCALCFREQUENCYINMONTHS
CVP_XBLCK_B = ISBUSINESSPURPOSECOMPLETED
REPRF = ISDOUBLEINVOICE
REPRF = ISTOBECHECKEDFORDUPLICATES
XDEZV = ISTOBELOCALLYPROCESSED
XPORE = ITEMISTOBEPAIDSEPARATELY
DATLZ = LASTINTERESTCALCRUNDATE
ZUAWA = LAYOUTSORTINGRULE
MANDT = MANDT
MINDK = MINORITYGROUP
ZAHLS = PAYMENTBLOCKINGREASON
PAYMENTCLEARINGGRPID = PAYMENTCLEARINGGROUP
XEDIP = PAYMENTISTOBESENTBYEDI
ZWELS = PAYMENTMETHODSLIST
UZAWE = PAYMENTMETHODSUPPLEMENT
PAYTRSN = PAYMENTREASON
ZTERM = PAYMENTTERMS
PERNR = PERSONNELNUMBER
ALTKN = PREVIOUSACCOUNTNUMBER
AKONT = RECONCILIATIONACCOUNT
TOGRR = SUPLRINVCVERIFICATTOLGROUP
LIFNR = SUPPLIER
KVERM = SUPPLIERACCOUNTNOTE
CERDT = SUPPLIERCERTIFICATIONDATE
ZSABE = SUPPLIERCLERK
EIKTO = SUPPLIERCLERKIDBYSUPPLIER
INTAD = SUPPLIERCLERKURL
LNRZE = SUPPLIERHEADOFFICE
SPERR = SUPPLIERISBLOCKEDFORPOSTING
FRGRP = SUPPLIERRELEASEGROUP
CRN = UK_COMPANYREGISTRATIONNUMBER
CATEG = UK_CONTRACTORBUSINESSTYPE
PARTNER_UTR = UK_PARTNERTAXREFERENCE
PARTNER_NAME = UK_PARTNERTRADINGNAME
VFNUM = UK_VERIFICATIONNUMBER
STATUS = UK_VERIFICATIONSTATUS
VFNID = UK_VERIFIEDTAXSTATUS
US_CHAP4_STATUS_CODE = US_CHAPTER4STATUSCODE
US_PARTNERSHIP_IND = US_FOREIGNSUPLRHASPARTNERSHIP
US_LOB_CODE = US_FOREIGNSUPLRLMTNONBNFTCODE
US_FATCA_IND = US_FRGNACCTTAXFILINGISREQUIRED
US_REC_COUNTRY = US_FRGNACCTTAXRCPNTCNTRY
US_W8_RECVDATE = US_FW8BENRECEIVEDATE
US_W9_RECVDATE = US_FW9RECEIVEDATE
US_GIIN = US_GLOBINTERMEDIARYIDNNUMBER
US_LOB_CODE = US_LOBTREATYCODE
US_FTID = US_RECIPIENTFOREIGNTAXID
US_TIN_NOTICE = US_SECONDTINNOTICEISISSUED
QLAND = WITHHOLDINGTAXCOUNTRY
