LFM1 = I_SUPPLIERPURCHASINGORG
HSCABS = ABSOLUTEHANDLINGSURCHARGEAMT
XERSR = AUTOMATICEVALUATEDRCPTSETTLMT
AUBEL = AUTOMDEBITCRTNISENBLDONGI
KALSK = CALCULATIONSCHEMAGROUPCODE
TELF1 = CONTACTPERSONPHONENUMBER
LOEVM = DELETIONINDICATOR
VALID_PRO = EVALDRCPTSETTLEMENTPROFILE
XERSY = EVALDRECEIPTSETTLEMENTISACTIVE
INCO1 = INCOTERMSCLASSIFICATION
INCO2_L = INCOTERMSLOCATION1
INCO3_L = INCOTERMSLOCATION2
INCO4_KEY = INCOTERMSSUPCHNDVTGLOCADDLUUID
INCO2_KEY = INCOTERMSSUPCHNLOC1ADDLUUID
INCO3_KEY = INCOTERMSSUPCHNLOC2ADDLUUID
INCO2 = INCOTERMSTRANSFERLOCATION
INCOV = INCOTERMSVERSION
EXPVZ = INTRASTATCRSBORDERTRMODE
WEBRE = INVOICEISGOODSRECEIPTBASED
LEBRE = INVOICEISMMSERVICEENTRYBASED
KZABS = ISORDERACKNRQD
MANDT = MANDT
PLIFZ = MATERIALPLANNEDDELIVERYDURN
HSCMAX = MAXIMUMHANDLINGSURCHARGEAMT
HSCMIN = MINIMUMHANDLINGSURCHARGEAMT
MINBW = MINIMUMORDERAMOUNT
ZTERM = PAYMENTTERMS
HSCPE = PERCENTAGEHANDLINGSURCHARGEAMT
PLIFZ = PLANNEDDELIVERYDURATIONINDAYS
LFRHY = PLANNINGCYCLE
MEPRF = PRICINGDATECONTROL
PAPRF = PRODSTOCKANDSLSDATATRANSFPRFL
MEGRU = PRODUCTUNITGROUP
WAERS = PURCHASEORDERCURRENCY
EKGRP = PURCHASINGGROUP
SPERM = PURCHASINGISBLOCKEDFORSUPPLIER
EKORG = PURCHASINGORGANIZATION
KZAUT = PURORDAUTOGENERATIONISALLOWED
RDPRF = ROUNDINGPROFILE
VSBED = SHIPPINGCONDITION
NRGEW = SUPLRDISCOUNTINKINDISGRANTED
XNBWY = SUPLRINVCREVALISALLOWED
AGREL = SUPLRISRLVTFORSETTLMTMGMT
BOLRE = SUPLRISSUBJTOSUBSQNTSETTLEMENT
UMSAE = SUPLRPURGORGAGRMTOFBUSVOLISRQD
PRFRE = SUPLRPURGORGISRLVTFORPRICEDETN
LIFNR = SUPPLIER
LFABC = SUPPLIERABCCLASSIFICATIONCODE
EIKTO = SUPPLIERACCOUNTNUMBER
BSTAE = SUPPLIERCONFIRMATIONCONTROLKEY
KZRET = SUPPLIERISRETURNSSUPPLIER
TELF1 = SUPPLIERPHONENUMBER
VERKF = SUPPLIERRESPSALESPERSONNAME
