LIKP = I_DELIVERYDOCUMENT
ROUTA = ACTUALDELIVERYROUTE
WADAT_IST = ACTUALGOODSMOVEMENTDATE
SPE_WAUHR_IST = ACTUALGOODSMOVEMENTTIME
FKDAT = BILLINGDOCUMENTDATE
BOLNR = BILLOFLADING
CMPS_CM = CENTRALCREDITCHECKSTATUS
CMPS_TE = CENTRALCREDITCHKTECHERRSTS
AUTLF = COMPLETEDELIVERYISDEFINED
POTIM = CONFIRMATIONTIME
CMWAE = CONTROLLINGAREACURRENCY
ERNAM = CREATEDBYUSER
ERDAT = CREATIONDATE
ERZET = CREATIONTIME
CMFRE = CREDITBLOCKRELEASEDATE
KNKLI = CUSTOMERCREDITACCOUNT
KDGRP = CUSTOMERGROUP
SPE_LOEKZ = DELETIONINDICATOR
TM_ADV_SHIP_RECV = DELIVADVNCDSHIPGRCVGRLVNCE
LIFSK = DELIVERYBLOCKREASON
LFDAT = DELIVERYDATE
VBELN = DELIVERYDOCUMENT
LIFEX = DELIVERYDOCUMENTBYSUPPLIER
KNUMP = DELIVERYDOCUMENTCONDITION
LFART = DELIVERYDOCUMENTTYPE
IMWRK = DELIVERYISINPLANT
LPRIO = DELIVERYPRIORITY
LFUHR = DELIVERYTIME
DLV_VERSION = DELIVERYVERSION
CORR_IND = DELIVISQTYCRRTNADVNCSHIPGRCVG
AKPRZ = DEPRECIATIONPERCENTAGE
VTWIV = DISTRCHNLFORINTCOBILLING
VLSTK = DISTRSTATUSBYDECENTRALIZEDWRHS
SPAIV = DIVISIONFORINTCOBILLING
BLDAT = DOCUMENTDATE
TOTAL_ARC_STATUS = EU_DELIVERYARCSTATUS
CMPSJ = EXPRTINSURCREDITCHECKSTATUS
SPE_LIFEX_TYPE = EXTERNALIDENTIFICATIONTYPE
TPSID = EXTERNALTRANSPORTSYSTEM
KNFAK = FACTORYCALENDARBYCUSTOMER
PIOIV = FACTORYCALENDARFORINTCOBILLING
CMPSI = FINDOCCREDITCHECKSTATUS
XABLN = GOODSISSUEORRECEIPTSLIPNUMBER
WAUHR = GOODSISSUETIME
VESTK = HANDLINGUNITINSTOCK
UVALL = HDRGENERALINCOMPLETIONSTATUS
UVWAK = HDRGOODSMVTINCOMPLETIONSTATUS
UVFAK = HEADERBILLGINCOMPLETIONSTATUS
FAKSK = HEADERBILLINGBLOCKREASON
UVVLK = HEADERDELIVINCOMPLETIONSTATUS
BTGEW = HEADERGROSSWEIGHT
NTGEW = HEADERNETWEIGHT
UVPAK = HEADERPACKINGINCOMPLETIONSTS
UVPIK = HEADERPICKGINCOMPLETIONSTATUS
VOLUM = HEADERVOLUME
VOLEH = HEADERVOLUMEUNIT
GEWEI = HEADERWEIGHTUNIT
INCO1 = INCOTERMSCLASSIFICATION
INCO2 = INCOTERMSTRANSFERLOCATION
EXT_ACT_DATE_TOCD = INTCOEXTACTLTRANSFOFCTRLDTETME
EXT_PLAN_DATE_TOCD = INTCOEXTPLNDTRANSFOFCTRLDTETME
EXT_TZONE_TOCD = INTCOEXTTRANSFOFCTRLDTETMETMZN
INT_ACT_DATE_TOCD = INTCOINTACTLTRANSFOFCTRLDTETME
INT_PLAN_DATE_TOCD = INTCOINTPLNDTRANSFOFCTRLDTETME
INT_TZONE_TOCD = INTCOINTTRANSFOFCTRLDTETMETMZN
KUNIV = INTERCOMPANYBILLINGCUSTOMER
FKDIV = INTERCOMPANYBILLINGDATE
FKAIV = INTERCOMPANYBILLINGTYPE
LCNUM = INTERNALFINANCIALDOCUMENT
KLIEF = ISCORRECTIONDELIVERY
LISPL = ISDELIVERYFORSINGLEWAREHOUSE
EXPKZ = ISEXPORTDELIVERY
AEDAT = LASTCHANGEDATE
AENAM = LASTCHANGEDBYUSER
LDDAT = LOADINGDATE
LSTEL = LOADINGPOINT
LDUHR = LOADINGTIME
SPE_LE_SCENARIO = LOGISTICSEXECUTIONSCENARIO
MANDT = MANDT
CMPSC = MAXDOCVALUECREDITCHECKSTATUS
TRAID = MEANSOFTRANSPORT
TRMTYP = MEANSOFTRANSPORTREFMATERIAL
TRATY = MEANSOFTRANSPORTTYPE
CMNGV = NEXTSHIPPINGDATE
KZAZU = ORDERCOMBINATIONISALLOWED
TERNR = ORDERID
TOTAL_PCSTA = OVERALLCHMLCMPLNCSTATUS
TOTAL_DGSTA = OVERALLDANGEROUSGOODSSTATUS
BESTK = OVERALLDELIVCONFSTATUS
FKSTK = OVERALLDELIVRELTDBILLGSTATUS
WBSTK = OVERALLGOODSMOVEMENTSTATUS
PKSTK = OVERALLPACKINGSTATUS
KOQUK = OVERALLPICKINGCONFSTATUS
KOSTK = OVERALLPICKINGSTATUS
PDSTK = OVERALLPROOFOFDELIVERYSTATUS
TOTAL_SDSSTA = OVERALLSAFETYDATASHEETSTATUS
GBSTK = OVERALLSDPROCESSSTATUS
TOTAL_EMCST = OVERALLTRDCMPLNCEMBARGOSTS
LVSTK = OVERALLWAREHOUSEACTIVITYSTATUS
UVVLS = OVRLITMDELIVINCOMPLETIONSTS
UVWAS = OVRLITMGDSMVTINCOMPLETIONSTS
UVALS = OVRLITMGENERALINCOMPLETIONSTS
UVPAS = OVRLITMPACKINGINCOMPLETIONSTS
UVPIS = OVRLITMPICKINGINCOMPLETIONSTS
TOTAL_LCCST = OVRLTRDCMPLNCLEGALCTRLCHKSTS
TOTAL_SLCST = OVRLTRDCMPLNCSNCTNDLISTCHKSTS
ABSSC = PAYMENTGUARANTEEPROCEDURE
CMPSD = PAYMENTTERMCREDITCHECKSTATUS
CMPSK = PAYTAUTHSNCREDITCHECKSTS
BEROT = PICKEDITEMSLOCATION
KODAT = PICKINGDATE
KOUHR = PICKINGTIME
WADAT = PLANNEDGOODSISSUEDATE
KNUMV = PRICINGDOCUMENT
PODAT = PROOFOFDELIVERYDATE
ROUTE = PROPOSEDDELIVERYROUTE
TM_WHSE_EXEC = READYFORWAREHOUSEEXECSTATUS
TZONRC = RECEIVINGLOCATIONTIMEZONE
WERKS = RECEIVINGPLANT
XBLNR = REFERENCEDOCUMENTNUMBER
AMTBL = RELEASEDCREDITAMOUNT
AULWE = ROUTESCHEDULE
BZIRK = SALESDISTRICT
VKBUR = SALESOFFICE
VKORG = SALESORGANIZATION
VKOIV = SALESORGFORINTCOBILLING
VBTYP = SDDOCUMENTCATEGORY
TRSPG = SHIPMENTBLOCKREASON
VSBED = SHIPPINGCONDITION
RFM_PSST_GROUP = SHIPPINGGROUPNUMBER
TZONIS = SHIPPINGLOCATIONTIMEZONE
VSTEL = SHIPPINGPOINT
VSART = SHIPPINGTYPE
KUNNR = SHIPTOPARTY
KUNAG = SOLDTOPARTY
SDABW = SPECIALPROCESSINGCODE
STWAE = STATISTICSCURRENCY
LIFNR = SUPPLIER
SPSTG = TOTALBLOCKSTATUS
CMGST = TOTALCREDITCHECKSTATUS
NETWR = TOTALNETAMOUNT
ANZPK = TOTALNUMBEROFPACKAGE
WAERK = TRANSACTIONCURRENCY
TRAGR = TRANSPORTATIONGROUP
TDDAT = TRANSPORTATIONPLANNINGDATE
TRSTA = TRANSPORTATIONPLANNINGSTATUS
TDUHR = TRANSPORTATIONPLANNINGTIME
ABLAD = UNLOADINGPOINTNAME
LGNUM = WAREHOUSE
LGTOR = WAREHOUSEGATE
LGBZO = WAREHOUSESTAGINGAREA
