LIPS = I_DELIVERYDOCUMENTITEM
LGMNG = ACTUALDELIVEREDQTYINBASEUNIT
LFIMG = ACTUALDELIVERYQUANTITY
KVGR1 = ADDITIONALCUSTOMERGROUP1
KVGR2 = ADDITIONALCUSTOMERGROUP2
KVGR3 = ADDITIONALCUSTOMERGROUP3
KVGR4 = ADDITIONALCUSTOMERGROUP4
KVGR5 = ADDITIONALCUSTOMERGROUP5
MVGR1 = ADDITIONALMATERIALGROUP1
MVGR2 = ADDITIONALMATERIALGROUP2
MVGR3 = ADDITIONALMATERIALGROUP3
MVGR4 = ADDITIONALMATERIALGROUP4
MVGR5 = ADDITIONALMATERIALGROUP5
SPE_ALTERNATE = ALTERNATEPRODUCTNUMBER
MEINS = BASEUNIT
CHARG = BATCH
LICHN = BATCHBYSUPPLIER
CUOBJ_CH = BATCHCLASSIFICATION
KNUMH_CH = BATCHSEARCHSTRATEGY
SERNR = BOMEXPLOSION
GSBER = BUSINESSAREA
PCSTA = CHMLCMPLNCSTATUS
KMEIN = CONDITIONUNIT
KZVBR = CONSUMPTIONPOSTING
KOKRS = CONTROLLINGAREA
UMREF = CONVERSIONFACTOR
KOSTL = COSTCENTER
WAVWR = COSTINDOCUMENTCURRENCY
ERNAM = CREATEDBYUSER
ERDAT = CREATIONDATE
ERZET = CREATIONTIME
CMPRE_FLT = CREDITRELATEDPRICE
KCMENG = CUMULATIVEBATCHQTYINBASEUNIT
AESKD = CUSTENGINEERINGCHGSTATUS
DGSTA = DANGEROUSGOODSSTATUS
VBELN = DELIVERYDOCUMENT
POSNR = DELIVERYDOCUMENTITEM
LIFEXPOS = DELIVERYDOCUMENTITEMBYSUPPLIER
PSTYV = DELIVERYDOCUMENTITEMCATEGORY
ARKTX = DELIVERYDOCUMENTITEMTEXT
GRKOR = DELIVERYGROUP
RESOURCE_ID = DELIVERYITEMRESOURCEID
VRKME = DELIVERYQUANTITYUNIT
FKSTA = DELIVERYRELATEDBILLINGSTATUS
UMVKN = DELIVERYTOBASEQUANTITYDNMNTR
UMVKZ = DELIVERYTOBASEQUANTITYNMRTR
UMREV = DELIVERYTOBASEUNITCNVRSNFCTR
ABTNR = DEPARTMENTCLASSIFICATIONBYCUST
VTWEG = DISTRIBUTIONCHANNEL
SPART = DIVISION
ARC_STATUS = EU_DELIVERYITEMARCSTATUS
VBEAF = FIXEDSHIPGPROCGDURATIONINDAYS
FLPKZ = FLDLOGSSTATUS
FKBER = FUNCTIONALAREA
KONTO = GLACCOUNT
GRUND = GOODSMOVEMENTREASONCODE
WBSTA = GOODSMOVEMENTSTATUS
BWART = GOODSMOVEMENTTYPE
UEPOS = HIGHERLEVELITEM
UEPVW = HIGHERLEVELITEMUSAGE
UECHA = HIGHERLVLITMOFBATSPLTITM
QPLOS = INSPECTIONLOT
QTLOS = INSPECTIONPARTIALLOT
ICO_VGBEL = INTCOREFSDDOCUMENT
ICO_VGTYP = INTCOREFSDDOCUMENTCATEGORY
ICO_VGPOS = INTCOREFSDDOCUMENTITEM
ABRLI = INTDELIVERYSCHEDULENUMBER
EAN11 = INTERNATIONALARTICLENUMBER
SOBKZ = INVENTORYSPECIALSTOCKTYPE
BWTAR = INVENTORYVALUATIONTYPE
SPE_GEN_ELIKZ = ISCOMPLETELYDELIVERED
NOWAB = ISNOTGOODSMOVEMENTSRELEVANT
BWTEX = ISSEPARATEVALUATION
UMCHA = ISSGORRCVGBATCH
UMMAT = ISSGORRCVGMATERIAL
UMRESOURCE_ID = ISSGORRCVGRESOURCEID
UMSOK = ISSGORRCVGSPCLSTOCKIND
UMBSQ = ISSGORRCVGSTOCKCATEGORY
UMBAR = ISSGORRCVGVALUATIONTYPE
UMWRK = ISSUINGORRECEIVINGPLANT
UMLGO = ISSUINGORRECEIVINGSTORAGELOC
FAKSP = ITEMBILLINGBLOCKREASON
UVFAK = ITEMBILLINGINCOMPLETIONSTATUS
UVVLK = ITEMDELIVERYINCOMPLETIONSTATUS
UVWAK = ITEMGDSMVTINCOMPLETIONSTS
UVALL = ITEMGENERALINCOMPLETIONSTATUS
BRGEW = ITEMGROSSWEIGHT
FSH_VAS_REL = ITEMHASVALUEADDEDSERVICE
FKREL = ITEMISBILLINGRELEVANT
NTGEW = ITEMNETWEIGHT
UVPAK = ITEMPACKINGINCOMPLETIONSTATUS
UVPIK = ITEMPICKINGINCOMPLETIONSTATUS
VOLUM = ITEMVOLUME
VOLEH = ITEMVOLUMEUNIT
GEWEI = ITEMWEIGHTUNIT
AEDAT = LASTCHANGEDATE
LADGR = LOADINGGROUP
LOADING_POINT = LOADINGPOINTFORDELIVERY
MANDT = MANDT
HSDAT = MANUFACTUREDATE
MATNR = MATERIAL
KDMAT = MATERIALBYCUSTOMER
MFRGR = MATERIALFREIGHTGROUP
MATKL = MATERIALGROUP
XCHPF = MATERIALISBATCHMANAGED
XCHAR = MATERIALISINTBATCHMANAGED
MTART = MATERIALTYPEPRIMARY
NETPR = NETPRICEAMOUNT
ANZSN = NUMBEROFSERIALNUMBERS
KDAUF = ORDERDOCUMENT
AUFNR = ORDERID
POSNR_PP = ORDERITEM
ORMNG = ORIGINALDELIVERYQUANTITY
MATWA = ORIGINALLYREQUESTEDMATERIAL
VBELV = ORIGINSDDOCUMENT
UEBTO = OVERDELIVTOLRTDLMTRATIOINPCT
PKSTA = PACKINGSTATUS
KZTLF = PARTIALDELIVERYISALLOWED
ABFOR = PAYMENTGUARANTEEFORM
KOQUA = PICKINGCONFIRMATIONSTATUS
KOMKZ = PICKINGCONTROL
KOSTA = PICKINGSTATUS
VPMAT = PLANNINGMATERIAL
VPWRK = PLANNINGPLANT
WERKS = PLANT
SHKZG_UM = PRIMARYPOSTINGSWITCH
MATNR = PRODUCT
MBDAT = PRODUCTAVAILABILITYDATE
MBUHR = PRODUCTAVAILABILITYTIME
WRF_CHARSTC1 = PRODUCTCHARACTERISTIC1
WRF_CHARSTC2 = PRODUCTCHARACTERISTIC2
WRF_CHARSTC3 = PRODUCTCHARACTERISTIC3
FSH_COLLECTION = PRODUCTCOLLECTION
CUOBJ = PRODUCTCONFIGURATION
MATKL = PRODUCTGROUP
PRBME = PRODUCTGROUPBASEUNIT
PRODH = PRODUCTHIERARCHYNODE
FSH_SEASON = PRODUCTSEASON
FSH_SEASON_YEAR = PRODUCTSEASONYEAR
FSH_THEME = PRODUCTTHEME
PAOBJNR = PROFITABILITYSEGMENT_2
PRCTR = PROFITCENTER
PODREL = PROOFOFDELIVERYRELEVANCECODE
PDSTA = PROOFOFDELIVERYSTATUS
BPMNG = QTYINPURCHASEORDERPRICEUNIT
FMENG = QUANTITYISFIXED
EMPST = RECEIVINGPOINT
VGSYS = REFERENCEDOCUMENTLOGICALSYSTEM
VGBEL = REFERENCESDDOCUMENT
VGTYP = REFERENCESDDOCUMENTCATEGORY
VGPOS = REFERENCESDDOCUMENTITEM
SGT_RCAT = REQUIREMENTSEGMENT
RSNUM = RESERVATION
RSPOS = RESERVATIONITEM
RSART = RESERVATIONRECORDTYPE
AKTNR = RETAILPROMOTION
SHKZG = RETURNSDELIVERYITEMCODE
FSH_RSNUM = RFMRESERVATION
FSH_RSPOS = RFMRESERVATIONITEM
SDSSTA = SAFETYDATASHEETSTATUS
POSAR = SALESDOCUMENTITEMTYPE
VKGRP = SALESGROUP
VKBUR = SALESOFFICE
VBTYV = SALESSDDOCUMENTCATEGORY
ABART = SCHEDULINGAGREEMENTRELEASETYPE
POSNV = SDDOCUMENTITEM
GBSTA = SDPROCESSSTATUS
SERVICE_DOC_ID = SERVICEDOCUMENT
SERVICE_DOC_ITEM_ID = SERVICEDOCUMENTITEM
SERVICE_DOC_TYPE = SERVICEDOCUMENTTYPE
VFDAT = SHELFLIFEEXPIRATIONDATE
STADAT = STATISTICSDATE
SGT_SCAT = STOCKSEGMENT
INSMK = STOCKTYPE
LGPLA = STORAGEBIN
LGORT = STORAGELOCATION
LGTYP = STORAGETYPE
FOBWA = SUBSEQUENTMOVEMENTTYPE
KZWI1 = SUBTOTAL1AMOUNT
KZWI2 = SUBTOTAL2AMOUNT
KZWI3 = SUBTOTAL3AMOUNT
KZWI4 = SUBTOTAL4AMOUNT
KZWI5 = SUBTOTAL5AMOUNT
KZWI6 = SUBTOTAL6AMOUNT
NETWR = TOTALNETAMOUNT
TRAGR = TRANSPORTATIONGROUP
EMCST = TRDCMPLNCEMBARGOSTS
LCCST = TRDCMPLNCLEGALCONTROLSTS
SLCST = TRDCMPLNCSNCTNDLISTCHKSTS
UNTTO = UNDERDELIVTOLRTDLMTRATIOINPCT
UEBTK = UNLIMITEDOVERDELIVERYISALLOWED
FSH_ITEM_GROUP = VALADDEDSRVCITEMGROUP
FSH_ITEM = VALADDEDSRVCITEMNUMBER
FSH_VAS_PRNT_ID = VALADDEDSRVCPARENTITMNUMBER
FSH_TRANSACTION = VALADDEDSRVCTRANSACTIONNUMBER
VCM_CHAIN_CATEGORY = VALUECHAINCATEGORY
VCM_CHAIN_UUID = VALUECHAININSTANCECHAR32UUID
VBEAV = VARBLSHIPGPROCGDURATIONINDAYS
LGNUM = WAREHOUSE
LVSTA = WAREHOUSEACTIVITYSTATUS
LGBZO = WAREHOUSESTAGINGAREA
BESTQ = WAREHOUSESTOCKCATEGORY
LGPBE = WAREHOUSESTORAGEBIN
PS_PSP_PNR = WBSELEMENTINTERNALID
