MARA = I_PRODUCTPROCUREMENT
BEGRU = AUTHORIZATIONGROUP
MANDT = MANDT
BWVOR = PROCUREMENTRULE
MATNR = PRODUCT
BSTME = PURCHASEORDERQUANTITYUNIT
EKWSL = PURCHASINGACKNPROFILE
BWSCL = SOURCEOFSUPPLYCATEGORY
VABME = VARBLPURORDUNITSTATUS
