MARA = I_PRODUCT
ADPROF = ADJUSTMENTPROFILE
ANP = ANPCODE
ATTYP = ARTICLECATEGORY
BBTYP = ASSORTMENTLISTTYPE
BEGRU = AUTHORIZATIONGROUP
MEINS = BASEUNIT
HOEHE = BASEUNITSPECIFICPRODUCTHEIGHT
LAENG = BASEUNITSPECIFICPRODUCTLENGTH
BREIT = BASEUNITSPECIFICPRODUCTWIDTH
WRKST = BASICMATERIAL
BRAND_ID = BRAND
VPREH = COMPARISONPRICEQUANTITY
KUNNR = COMPETITORID
INHME = CONTENTUNIT
HERKL = COUNTRYOFORIGIN
ERNAM = CREATEDBYUSER
ERSDA = CREATIONDATE
CREATED_AT_TIME = CREATIONTIME
SATNR = CROSSPLANTCONFIGURABLEPRODUCT
MSTAE = CROSSPLANTSTATUS
MSTDE = CROSSPLANTSTATUSVALIDITYDATE
PROFL = DANGEROUSGOODSINDPROFILE
ICFA = DFSAMMUNITIONGROUPCODE
LOGLEV_RETO = DFSLOGISTICSLEVEL
DFS_MFRP2 = DFSMANUFACTURERPARTLONGNUMBER
MCOND = DFSMATLCONDITIONMGMT
NSNID = DFSNATIONALITEMIDNNUMBER
DFS_SENSITIVITY_KEY = DFSPRODUCTSENSITIVITY
RETDELC = DFSRETURNDELIVERY
RIC_ID = DFSRICIDENTIFIER
NRFHG = DISCOUNTINKINDELIGIBILITY
SPART = DIVISION
CADKZ = DOCUMENTISCREATEDBYCAD
EXTWG = EXTERNALPRODUCTGROUP
FSH_MG_AT1 = FASHIONPRODINFORMATIONFIELD1
FSH_MG_AT2 = FASHIONPRODINFORMATIONFIELD2
FSH_MG_AT3 = FASHIONPRODINFORMATIONFIELD3
GTIN_VARIANT = GLOBALTRADEITEMNUMBERVARIANT
INHBR = GROSSCONTENT
BRGEW = GROSSWEIGHT
HNDLCODE = HANDLINGINDICATOR
HUTYP = HANDLINGUNITTYPE
MLGUT = HASEMPTIESBOM
ANIMAL_ORIGIN = HASTEXTILEPARTSWTHANIMALORIGIN
TARE_VAR = HASVARIABLETAREWEIGHT
MBRSH = INDUSTRYSECTOR
NORMT = INDUSTRYSTANDARDNAME
NUMTP = INTERNATIONALARTICLENUMBERCAT
XGCHP = ISAPPROVEDBATCHRECORDREQD
XCHPF = ISBATCHMANAGEMENTREQUIRED
CHML_CMPLNC_RLVNCE_IND = ISCHEMICALCOMPLIANCERELEVANT
LVORM = ISMARKEDFORDELETION
PILFERABLE = ISPILFERABLE
HAZMAT = ISRELEVANTFORHZDSSUBSTANCES
MTPOS_MARA = ITEMCATEGORYGROUP
LABOR = LABORATORYORDESIGNOFFICE
LAEDA = LASTCHANGEDATE
LAST_CHANGED_TIME = LASTCHANGETIME
LOGISTICAL_MAT_CATEGORY = LOGISTICALPRODUCTCATEGORY
DISST = LOWLEVELCODE
PSTAT = MAINTENANCESTATUS
MANDT = MANDT
MSBOOKPARTNO = MANUFACTURERBOOKPARTNUMBER
MFRNR = MANUFACTURERNUMBER
MPROF = MANUFACTURERPARTPROFILE
VOLUM = MATERIALVOLUME
MAXC = MAXIMUMCAPACITY
MAXH = MAXIMUMPACKAGINGHEIGHT
MAXL = MAXIMUMPACKAGINGLENGTH
MAXB = MAXIMUMPACKAGINGWIDTH
INHAL = NETCONTENT
NTGEW = NETWEIGHT
MAXC_TOL = OVERCAPACITYTOLERANCE
BMATN = OWNINVENTORYMANAGEDPRODUCT
MAGRV = PACKAGINGMATERIALGROUP
RMATP = PACKINGREFERENCEPRODUCT
SCM_PUOM = PREFERREDUNITOFMEASURE
BWVOR = PROCUREMENTRULE
KOSCH = PRODALLOCDETNPROCEDURE
COLOR_ATINN = PRODCHARC1INTERNALNUMBER
SIZE1_ATINN = PRODCHARC2INTERNALNUMBER
SIZE2_ATINN = PRODCHARC3INTERNALNUMBER
KZEFF = PRODEFFCTYPARAMVALSAREASSIGNED
KZUMW = PRODISENVIRONMENTALLYRELEVANT
GENNR = PRODNOINGENPRODINPREPACKPROD
SCM_MATID_GUID22 = PRODSUPCHNMGMTUUID22
MATNR = PRODUCT
ATTYP = PRODUCTCATEGORY
COLOR = PRODUCTCHARACTERISTIC1
SIZE1 = PRODUCTCHARACTERISTIC2
SIZE2 = PRODUCTCHARACTERISTIC3
PRZUS = PRODUCTCOMPOSITIONISRELEVANT
CUOBF = PRODUCTCONFIGURATION
AESZN = PRODUCTDOCUMENTCHANGENUMBER
ZEINR = PRODUCTDOCUMENTNUMBER
BLANZ = PRODUCTDOCUMENTPAGECOUNT
ZEIFO = PRODUCTDOCUMENTPAGEFORMAT
BLATT = PRODUCTDOCUMENTPAGENUMBER
ZEIAR = PRODUCTDOCUMENTTYPE
ZEIVR = PRODUCTDOCUMENTVERSION
MATNR_EXTERNAL = PRODUCTEXTERNALID
MATKL = PRODUCTGROUP
PRDHA = PRODUCTHIERARCHY
FORMT = PRODUCTIONMEMOPAGEFORMAT
FERTH = PRODUCTIONORINSPECTIONMEMOTXT
KZKFG = PRODUCTISCONFIGURABLE
IHIVI = PRODUCTISHIGHLYVISCOUS
MATFI = PRODUCTISLOCKED
MFRPN = PRODUCTMANUFACTURERNUMBER
MEABM = PRODUCTMEASUREMENTUNIT
PRODUCTOID = PRODUCTOID
BISMT = PRODUCTOLDID
FSH_SEALV = PRODUCTSEASONUSAGECATEGORY
EAN11 = PRODUCTSTANDARDID
MTART = PRODUCTTYPE
SCM_MATID_GUID16 = PRODUCTUUID
LIQDT = PRODUCTVALIDENDDATE
DATAB = PRODUCTVALIDSTARTDATE
BSTME = PURCHASEORDERQUANTITYUNIT
QMPUR = QLTYMGMTINPROCMTISACTIVE
QGRP = QUALITYINSPECTIONGROUP
QQTIME = QUARANTINEPERIOD
SALES_MATERIAL = SALESPRODUCT
MSTAV = SALESSTATUS
MSTDV = SALESSTATUSVALIDITYDATE
SGT_REL = SEGMENTATIONISRELEVANT
SGT_COVSA = SEGMENTATIONSTRATEGY
SERIAL = SERIALIDENTIFIERASSGMTPROFILE
SERLV = SERIALNOEXPLICITNESSLEVEL
SERIAL = SERIALNUMBERPROFILE
GROES = SIZEORDIMENSIONTEXT
PS_SMARTFORM = SMARTFORMNAME
BWSCL = SOURCEOFSUPPLY
HUTYP_DFLT = STANDARDHANDLINGUNITTYPE
QQTIMEUOM = TIMEUNITFORQUARANTINEPERIOD
TRAGR = TRANSPORTATIONGROUP
ILOOS = TRANSPORTISINBULK
MAXDIM_UOM = UNITFORMAXPACKAGINGDIMENSIONS
DATAB = VALIDITYSTARTDATE
VABME = VARBLPURORDUNITISACTIVE
VOLEH = VOLUMEUNIT
WHMATGR = WAREHOUSEPRODUCTGROUP
WHSTC = WAREHOUSESTORAGECONDITION
GEWEI = WEIGHTUNIT