MARA = I_PRODUCTSALES
ERVOL = ALLOWEDPACKAGINGVOLUMEQTY
ERVOE = ALLOWEDPACKAGINGVOLUMEQTYUNIT
ERGEW = ALLOWEDPACKAGINGWEIGHTQTY
ERGEI = ALLOWEDPACKAGINGWEIGHTQTYUNIT
BEGRU = AUTHORIZATIONGROUP
SOM_CYCLE = CABILLGCYCLE
SOM_CTR_AUTORENEWAL = CONTRACTAUTORENEWALTYPE
VOLTO = EXCESSVOLUMETOLERANCE
GEWTO = EXCESSWEIGHTTOLERANCE
KZGVH = ISCLOSEDPACKAGINGMATERIAL
ALLOW_PMAT_IGNO = ISVARIANTPRICEALLOWED
MANDT = MANDT
MFRGR = MATERIALFREIGHTGROUP
VHART = PACKAGINGMATERIALTYPE
PMATA = PRICINGREFERENCEPRODUCT
MATNR = PRODUCT
SRV_ESCAL = RESPONSEPROFILE
MSTAV = SALESSTATUS
MSTDV = SALESSTATUSVALIDITYDATE
SRV_DURA = SERVICEDURATION
SRV_DURA_UOM = SERVICEDURATIONUNIT
SRV_SERWI = SERVICEPROFILE
STFAK = STACKINGFACTOR
SOM_CYCLE_RULE = SUBSCRPNPRODBILLGCYCDETN
SOM_TC_SCHEMA = SUBSCRPNPRODTECHRSCESCHEMA
TAKLV = TAXCLASSIFICATION
TRAGR = TRANSPORTATIONGROUP
SPROF = VARIANTSPRICINGPROFILE
FUELG = VOLUMEMAXIMUMLEVEL
