MARA = I_PRODUCTSTORAGE_2
BEGRU = AUTHORIZATIONGROUP
MEINS = BASEUNIT
STOFF = HAZARDOUSMATERIALNUMBER
ETIFO = LABELFORM
ETIAR = LABELTYPE
MANDT = MANDT
MHDRZ = MINREMAININGSHELFLIFE
WESCH = NMBROFGRORGISLIPSTOPRINTQTY
MATNR = PRODUCT
SLED_BBD = PRODUCTEXPIRATIONDATECODE
IPRKZ = SHELFLIFEEXPIRATIONDATEPERIOD
RDMHD = SHELFLIFEEXPRTNDATERNDNGRULE
BEHVO = STORAGEBININSTRUCTION
RAUBE = STORAGECONDITIONS
TEMPB = TEMPERATURECONDITIONIND
MHDHB = TOTALSHELFLIFE
MHDLP = TOTALSHELFLIFESTORAGEPERCENT
