MARC = I_PRODUCTPLANTFORECAST
VRBFK = CONSUMPTIONQTYMULTIPLIER
VRBWK = CONSUMPTIONREFERENCEPLANT
VRBMT = CONSUMPTIONREFERENCEPRODUCT
VRBDT = CONSUMPTIONREFUSAGEENDDATE
KZKFK = CORRECTIONFACTORISREQUIRED
AUTRU = FORECASTMODELISRESET
MANDT = MANDT
WERKS = PLANT
MATNR = PRODUCT
