MARC = I_PRODUCTPLANTQTMANAGEMENT
INSMK = HASPOSTTOINSPECTIONSTOCK
KZDKZ = INSPLOTDOCUMENTATIONISREQUIRED
MANDT = MANDT
QMATA = MATLQUALITYAUTHORIZATIONGROUP
MAXLZ = MAXIMUMSTORAGEPERIOD
WERKS = PLANT
MATNR = PRODUCT
QMATV = PRODUCTPLANTHASINSPECTIONSETUP
QZGTP = PRODUCTQUALITYCERTIFICATETYPE
SSQSS = QUALITYMGMTCTRLKEY
PRFRQ = RECRRGINSPINTERVALTIMEINDAYS
QSSYS = SUPLRQUALITYMANAGEMENTSYSTEM
