MARC = I_PRODUCTPLANTINTLTRD
EXPME = COMMODITIYCODENUMBERUNIT
STEUC = CONSUMPTIONTAXCTRLCODE
HERKL = COUNTRYOFORIGIN
MTVER = EXPORTANDIMPORTPRODUCTGROUP
MANDT = MANDT
WERKS = PLANT
GPNUM = PRODINTLTRADECLASSIFICATION
MATNR = PRODUCT
CASNR = PRODUCTCASNUMBER
HERKR = REGIONOFORIGIN
