MARC = I_PRODUCTPLANTBASIC
MAABC = ABCINDICATOR
MTVFP = AVAILABILITYCHECKTYPE
STDPD = CONFIGURABLEPRODUCT
CONS_PROCG = CONSIGNMENTCONTROL
VRBFK = CONSUMPTIONQTYMULTIPLIER
VRBWK = CONSUMPTIONREFERENCEPLANT
VRBMT = CONSUMPTIONREFERENCEPRODUCT
VRBDT = CONSUMPTIONREFUSAGEENDDATE
STEUC = CONSUMPTIONTAXCTRLCODE
HERKL = COUNTRYOFORIGIN
FPRFM = DISTRCNTRDISTRIBUTIONPROFILE
UID_IEA = EXTALLOCOFITMUNQIDTISRELEVANT
PERIV = FISCALYEARVARIANT
BSTFE = FIXEDLOTSIZEQUANTITY
GI_PR_TIME = GOODISSUEPROCESSINGDAYS
AUSME = GOODSISSUEUNIT
WEBAZ = GOODSRECEIPTDURATION
CONS_PROCG = HASCONSIGNMENTCTRL
INSMK = HASPOSTTOINSPECTIONSTOCK
XCHPF = ISBATCHMANAGEMENTREQUIRED
KZKUP = ISCOPRODUCT
XCHAR = ISINTERNALBATCHMANAGED
LVORM = ISMARKEDFORDELETION
XMCNG = ISNEGATIVESTOCKALLOWED
MULTIPLE_EKGRP = ISPURGACROSSPURGGROUP
IUID_RELEVANT = ITEMUNIQUEIDENTIFIERISRELEVANT
IUID_TYPE = ITEMUNIQUEIDENTIFIERTYPE
PSTAT = MAINTENANCESTATUSNAME
MANDT = MANDT
MFRGR = MATERIALFREIGHTGROUP
BSTMA = MAXIMUMLOTSIZEQUANTITY
BSTMI = MINIMUMLOTSIZEQUANTITY
DISPO = MRPRESPONSIBLE
DISMM = MRPTYPE
UCMAT = ORIGINALBATCHREFERENCEMATERIAL
UCHKZ = ORIGLBATCHMANAGEMENTISREQUIRED
UEETO = OVERDELIVTOLERANCELIMIT
PERKZ = PERIODTYPE
PLIFZ = PLANNEDDELIVERYDURATIONINDAYS
WERKS = PLANT
BESKZ = PROCUREMENTTYPE
MATNR = PRODUCT
INDUS = PRODUCTCFOPCATEGORY
CUOBJ = PRODUCTCONFIGURATION
TEMP_UOM = PRODUCTCONTROLTEMPERATUREUNIT
LGPRO = PRODUCTIONINVTRYMANAGEDLOC
SFCPF = PRODUCTIONSCHEDULINGPROFILE
FEVOR = PRODUCTIONSUPERVISOR
KZKRI = PRODUCTISCRITICALPRT
EXCISE_TAX_RLVNCE = PRODUCTISEXCISETAXRELEVANT
LOGGR = PRODUCTLOGISTICSHANDLINGGROUP
TEMP_CTRL_MAX = PRODUCTMAXCONTROLTEMPERATURE
TEMP_CTRL_MIN = PRODUCTMINCONTROLTEMPERATURE
MEGRU = PRODUCTUNITGROUP
MMSTA = PROFILECODE
MMSTD = PROFILEVALIDITYSTARTDATE
PRCTR = PROFITCENTER
EKGRP = PURCHASINGGROUP
HERKR = REGIONOFORIGIN
EISBE = SAFETYSTOCKQUANTITY
SERNP = SERIALNUMBERPROFILE
BWSCL = SOURCEOFSUPPLYCATEGORY
SOBSL = SPECIALPROCUREMENTTYPE
EPRIO = STOCKDETERMINATIONGROUP
UNETO = UNDERDELIVTOLERANCELIMIT
BWTTY = VALUATIONCATEGORY
