MARC = I_PRODUCTPLANTPROCUREMENT
KAUTB = ISAUTOPURORDCREATIONALLOWED
MULTIPLE_EKGRP = ISPURGACROSSPURGGROUP
KORDB = ISSOURCELISTREQUIRED
FABKZ = ITMISRLVTTOJITDELIVSCHEDULES
MANDT = MANDT
WERKS = PLANT
MATNR = PRODUCT
VSPVB = PROPOSEDPRODUCTSUPPLYAREA
EKGRP = PURCHASINGGROUP
BWSCL = SOURCEOFSUPPLYCATEGORY
