MARC = I_PRODUCTPLANTCOSTING
LOSGR = COSTINGLOTSIZE
FVIDK = COSTINGPRODUCTIONVERSION
SOBSK = COSTINGSPECIALPROCUREMENTTYPE
KZKUP = ISCOPRODUCT
FXPRU = ISFIXEDPRICECOPRODUCT
MANDT = MANDT
WERKS = PLANT
MATNR = PRODUCT
STLAN = PRODUCTBOMUSAGE
NCOST = PRODUCTISCOSTINGRELEVANT
STLAL = SOURCEBOMALTERNATIVE
PLNNR = TASKLISTGROUP
APLAL = TASKLISTGROUPCOUNTER
PLNTY = TASKLISTTYPE
AWSLS = VARIANCEKEY
