MARC = I_PRODUCTSUPPLYPLANNING
MAABC = ABCINDICATOR
AUSSS = ASSEMBLYSCRAPPERCENT
MTVFP = AVAILABILITYCHECKTYPE
VINT1 = BACKWARDCNSMPNPERIODINWORKDAYS
KAUSF = COMPONENTSCRAPINPERCENT
CONS_PROCG = CONSIGNMENTCONTROL
SBDKZ = DEPENDENTREQUIREMENTSTYPE
LGFSB = DFLTSTORAGELOCATIONEXTPROCMT
AUSDT = EFFECTIVEOUTDATE
BSTFE = FIXEDLOTSIZEQUANTITY
NFMAT = FOLLOWUPPRODUCT
AUFTL = FORECASTREQUIREMENTSARESPLIT
VINT2 = FWDCONSUMPTIONPERIODINWORKDAYS
GI_PR_TIME = GOODISSUEPROCESSINGDAYS
WEBAZ = GOODSRECEIPTDURATION
DZEIT = INHOUSEPRODUCTIONTIME
SCHGT = ISBULKMATERIALCOMPONENT
AHDIS = ISMRPDEPENDENTRQMT
SHFLG = ISSAFETYTIME
LAGPR = ISSTORAGECOSTS
JITPRODNCONFPROFILE = JITPRODNCONFPROFILE
LOSFX = LOTSIZEINDEPENDENTCOSTS
BSTRF = LOTSIZEROUNDINGQUANTITY
DISLS = LOTSIZINGPROCEDURE
MANDT = MANDT
RGEKZ = MATLCOMPISMARKEDFORBACKFLUSH
BSTMA = MAXIMUMLOTSIZEQUANTITY
MABST = MAXIMUMSTOCKQUANTITY
BSTMI = MINIMUMLOTSIZEQUANTITY
EISLO = MINIMUMSAFETYSTOCKQUANTITY
MISKZ = MRPAVAILABILITYTYPE
DISGR = MRPGROUP
MRPPP = MRPPLANNINGCALENDAR
DISPR = MRPPROFILE
DISPO = MRPRESPONSIBLE
SFTY_STK_METH = MRPSAFETYSTOCKMETHOD
DISMM = MRPTYPE
SHPRO = PERDPRFLFORSFTYTME
LFRHY = PLANANDORDERDAYDETERMINATION
PLIFZ = PLANNEDDELIVERYDURATIONINDAYS
MDACH = PLANNEDORDERACTIONCONTROL
STRGR = PLANNINGSTRATEGYGROUP
FXHOR = PLANNINGTIMEFENCE
WERKS = PLANT
SOBSL = PROCUREMENTSUBTYPE
BESKZ = PROCUREMENTTYPE
MRPPP = PRODNPLNGANDCONTROLCALENDAR
KZBED = PRODRQMTSARECONSOLIDATED
VRMOD = PRODRQMTSCONSUMPTIONMODE
MATNR = PRODUCT
LGPRO = PRODUCTIONINVTRYMANAGEDLOC
KZPSP = PRODUCTISFORCROSSPROJECT
KZAUS = PRODUCTISTOBEDISCONTINUED
MEGRU = PRODUCTUNITGROUP
VSPVB = PROPOSEDPRODUCTSUPPLYAREA
RWPRO = RANGEOFCVRGPRFLCODE
MINBE = REORDERTHRESHOLDQUANTITY
SAUFT = REPETITIVEMANUFACTURINGISALLWD
SFEPR = REPETITIVEMANUFACTURINGPROFILE
RDPRF = ROUNDINGPROFILE
TAKZT = RQMTQTYRCPTTAKTTMEINWRKGDAYS
SHZET = SAFETYDURATION
EISBE = SAFETYSTOCKQUANTITY
FHORI = SCHEDULINGMARGINKEY
LGRAD = SRVCLVL
LAGPR = STORAGECOSTSPERCENTAGECODE
WZEIT = TOTALREPLENISHMENTLEADTIME
