MARC = I_PRODUCTWORKSCHEDULING
VERKZ = HASPRODUCTIONVERSION
MANDT = MANDT
BASMG = MATERIALBASEQUANTITY
RGEKZ = MATLCOMPISMARKEDFORBACKFLUSH
OCMPF = ORDERCHANGEMANAGEMENTPROFILE
UEETO = OVERDELIVTOLERANCELIMIT
WERKS = PLANT
BEARZ = PROCESSINGTIMEINDAYS
KZPRO = PRODISWITHDRAWNFRMPRODNBIN
KZECH = PRODNORDERISBATCHREQUIRED
MATNR = PRODUCT
LGPRO = PRODUCTIONINVTRYMANAGEDLOC
SFCPF = PRODUCTIONSCHEDULINGPROFILE
FEVOR = PRODUCTIONSUPERVISOR
FRTME = PRODUCTPRODUCTIONQUANTITYUNIT
RUEZT = SETUPANDTEARDOWNTIME
MATGR = TRANSITIONMATRIXPRODUCTSGROUP
TRANZ = TRANSITIONTIME
UNETO = UNDERDELIVTOLERANCELIMIT
UEETK = UNLIMITEDOVERDELIVISALLOWED
