MARC = I_PRODUCTPLANTSALES
MTVFP = AVAILABILITYCHECKTYPE
VBAMG = CAPPLANNINGQUANTITYINBASEUOM
LADGR = LOADINGGROUP
MANDT = MANDT
WERKS = PLANT
MATNR = PRODUCT
VBEAZ = PRODUCTSHIPPINGPROCESSINGTIME
ATPKZ = REPLACEMENTPARTTYPE
VRVEZ = WRKCENTERSSHIPGSETUPTIMEINDAYS
