MARD = I_PRODUCTSTORAGELOCATIONBASIC
ERSDA = CREATIONDATE
DLINL = DATEOFLASTPOSTEDCNTUNRSTRCDSTK
MDJIN = FISCALYEARCURRENTINVTRYPERIOD
KZVLS = HASINVTRYBLOCKSTOCKPREVPERIOD
KZILS = INVENTORYBLOCKSTOCKIND
BSKRF = INVENTORYCORRECTIONFACTOR
KZVLL = INVENTORYSTOCKPREVPERIOD
KZILL = INVTRYCURRENTYEARSTOCKIND
KZILQ = INVTRYQUALINSPCURRENTYRSTKIND
KZILE = INVTRYRESTRICTEDUSESTOCKIND
KZVLE = INVTRYRESTSTOCKPREVPERIODIND
KZVLQ = INVTRYSTOCKQLTYINSPPREVPERIOD
LVORM = ISMARKEDFORDELETION
LWMKB = LEANWRHSMANAGEMENTPICKINGAREA
PSTAT = MAINTENANCESTATUS
MANDT = MANDT
SPERR = PHYSICALINVENTORYBLOCKIND
WERKS = PLANT
MATNR = PRODUCT
LGORT = STORAGELOCATION
LGPBE = WAREHOUSESTORAGEBIN
