MARM = I_PRODUCTUNITSOFMEASURE
MEINH = ALTERNATIVEUNIT
CAPAUSE = CAPACITYUSAGE
EAN11 = GLOBALTRADEITEMNUMBER
NUMTP = GLOBALTRADEITEMNUMBERCATEGORY
BRGEW = GROSSWEIGHT
MESUB = LOWERLEVELPACKAGINGUNIT
MANDT = MANDT
VOLUM = MATERIALVOLUME
MAX_STACK = MAXIMUMSTACKINGFACTOR
MATNR = PRODUCT
GTIN_VARIANT = PRODUCTGTINVARIANT
MEABM = PRODUCTMEASUREMENTUNIT
UMREN = QUANTITYDENOMINATOR
UMREZ = QUANTITYNUMERATOR
NEST_FTR = REMAININGVOLUMEAFTERNESTING
TY2TQ = UNITOFMEASURECATEGORY
HOEHE = UNITSPECIFICPRODUCTHEIGHT
LAENG = UNITSPECIFICPRODUCTLENGTH
BREIT = UNITSPECIFICPRODUCTWIDTH
VOLEH = VOLUMEUNIT
GEWEI = WEIGHTUNIT
