MCH1 = I_BATCH
CHARG = BATCH
LICHA = BATCHBYSUPPLIER
ZFDAT = BATCHCERTIFICATIONDATE
BATCH_ID = BATCHEXTWHSEMGMTINTERNALID
LVORM = BATCHISMARKEDFORDELETION
CUOBJ_BM = CLFNOBJECTINTERNALID
HERKL = COUNTRYOFORIGIN
MTVER = EXPORTANDIMPORTPRODUCTGROUP
FVDT1 = FREEDEFINEDDATE1
FVDT2 = FREEDEFINEDDATE2
FVDT3 = FREEDEFINEDDATE3
FVDT4 = FREEDEFINEDDATE4
FVDT5 = FREEDEFINEDDATE5
FVDT6 = FREEDEFINEDDATE6
LWEDT = LASTGOODSRECEIPTDATE
MANDT = MANDT
HSDAT = MANUFACTUREDATE
MATNR = MATERIAL
VERAB = MATLBATCHAVAILABILITYDATE
ZUSTD = MATLBATCHISINRSTRCDUSESTOCK
QNDAT = NEXTINSPECTIONDATE
HERKR = REGIONOFORIGIN
VFDAT = SHELFLIFEEXPIRATIONDATE
SGT_SCAT = STOCKSEGMENT
LIFNR = SUPPLIER
