MKAL = I_PRODUCTIONVERSION
STLAL = BILLOFMATERIALVARIANT
STLAN = BILLOFMATERIALVARIANTUSAGE
PLNNR = BILLOFOPERATIONSGROUP
PLNTY = BILLOFOPERATIONSTYPE
ALNAL = BILLOFOPERATIONSVARIANT
PRFG_S = BOMCHECKSTATUS
CONFIGBLPRODPRODNVERS = CONFIGBLPRODPRODUCTIONVERSION
LOSGR = COSTINGLOTSIZE
EWM_LGPLA = DESTINATIONSTORAGEBIN
VERTO = DISTRIBUTIONKEY
EXE_STLAL = EXECBILLOFMATERIALVARIANT
EXE_STLAN = EXECBILLOFMATERIALVARIANTUSAGE
EXE_PLNNR = EXECBILLOFOPERATIONSGROUP
EXE_PLNTY = EXECBILLOFOPERATIONSTYPE
EXE_ALNAL = EXECBILLOFOPERATIONSVARIANT
VERSIND = HASVERSIONCTRLDBOMANDROUTING
ELPRO = ISSUINGSTORAGELOCATION
MATKO = MAINPRODUCT
MATNR = MATERIAL
CSPLT = MATERIALCOSTAPPORTIONMENTSTRUC
BSTMA = MATERIALMAXLOTSIZEQUANTITY
BSTMI = MATERIALMINLOTSIZEQUANTITY
SOBSL = MATERIALPROCUREMENTPROFILE
UCMAT = ORIGINALBATCHREFERENCEMATERIAL
DIFFPLANEXEMSTR = PLANNINGANDEXECUTIONBOMISDIFF
WERKS = PLANT
PRFG_G = PRELIMINARYPLANNINGSTATUS
BESKZ = PROCUREMENTTYPE
SERKZ = PRODNVERSISALLOWEDFORRPTVMFG
MDV01 = PRODUCTIONLINE
PRVBE = PRODUCTIONSUPPLYAREA
VERID = PRODUCTIONVERSION
MDV02 = PRODUCTIONVERSIONGROUP
MKSP = PRODUCTIONVERSIONISLOCKED
PRDAT = PRODUCTIONVERSIONLASTCHECKDATE
PRFG_F = PRODUCTIONVERSIONSTATUS
TEXT1 = PRODUCTIONVERSIONTEXT
VERTO = QUANTITYDISTRIBUTIONKEY
PRFG_R = RATEBASEDPLANNINGSTATUS
ALORT = RECEIVINGSTORAGELOCATION
TSA_PRVBE = TARGETPRODUCTIONSUPPLYAREA
EWAHR = USGEPROBLTYWTHVERSCTRLINPCT
BDATU = VALIDITYENDDATE
ADATU = VALIDITYSTARTDATE
EWM_LGNUM = WAREHOUSE
