MKPF = I_MATERIALDOCUMENTHEADER_2
BLART = ACCOUNTINGDOCUMENTTYPE
FRBNR = BILLOFLADING
USNAM = CREATEDBYUSER
CPUDT = CREATIONDATE
CPUTM = CREATIONTIME
LE_VBELN = DELIVERYDOCUMENT
BLDAT = DOCUMENTDATE
VGART = INVENTORYTRANSACTIONTYPE
UMWRK = ISSUINGORRECEIVINGPLANT
UMLGO = ISSUINGORRECEIVINGSTORAGELOC
MANDT = MANDT
MBLNR = MATERIALDOCUMENT
BKTXT = MATERIALDOCUMENTHEADERTEXT
MJAHR = MATERIALDOCUMENTYEAR
WERKS = PLANT
BUDAT = POSTINGDATE
XBLNR = REFERENCEDOCUMENT
LGORT = STORAGELOCATION