MSEG = I_MATERIALDOCUMENTITEM_2
KNTTP_GR = ACCOUNTASSIGNMENTCATEGORY
CHARG = BATCH
GSBER = BUSINESSAREA
BUKRS = COMPANYCODE
WAERS = COMPANYCODECURRENCY
KZVBR = CONSUMPTIONPOSTING
KOKRS = CONTROLLINGAREA
KOSTL = COSTCENTER
KUNNR = CUSTOMER
SHKZG = DEBITCREDITCODE
VBELN_IM = DELIVERYDOCUMENT
VBELP_IM = DELIVERYDOCUMENTITEM
BLDAT = DOCUMENTDATE
ERFME = ENTRYUNIT
GJPER = FISCALYEARPERIOD
PERIV = FISCALYEARVARIANT
SAKTO = GLACCOUNT
CANCELLED = GOODSMOVEMENTISCANCELLED
KZBEW = GOODSMOVEMENTREFDOCTYPE
BWART = GOODSMOVEMENTTYPE
KZZUG = GOODSRECEIPTTYPE
WEMPF = GOODSRECIPIENTNAME
SOBKZ = INVENTORYSPECIALSTOCKTYPE
LBBSA_SID = INVENTORYSTOCKTYPE
INSMK = INVENTORYUSABILITYCODE
BWTAR = INVENTORYVALUATIONTYPE
XAUTO = ISAUTOMATICALLYCREATED
ELIKZ = ISCOMPLETELYDELIVERED
UMCHA = ISSGORRCVGBATCH
UMMAT = ISSGORRCVGMATERIAL
UMSOK = ISSGORRCVGSPCLSTOCKIND
UMWRK = ISSUINGORRECEIVINGPLANT
LBBSA_CID = ISSUINGORRECEIVINGSTOCKTYPE
UMLGO = ISSUINGORRECEIVINGSTORAGELOC
APLZL = MAINTORDEROPERATIONCOUNTER
AUFPL = MAINTORDERROUTINGNUMBER
MANDT = MANDT
HSDAT = MANUFACTUREDATE
MATNR = MATERIAL
MEINS = MATERIALBASEUNIT
MBLNR = MATERIALDOCUMENT
ZEILE = MATERIALDOCUMENTITEM
SGTXT = MATERIALDOCUMENTITEMTEXT
MJAHR = MATERIALDOCUMENTYEAR
MAA_URZEI = MULTIACCTASSGMTORIGLMATLDOCITM
XMACC = MULTIPLEACCOUNTASSIGNMENTCODE
AUFNR = ORDERID
AUFPS = ORDERITEM
PERNR = PERSONWORKAGREEMENT
WERKS = PLANT
BUDAT = POSTINGDATE
NPLNR = PROJECTNETWORK
EBELN = PURCHASEORDER
EBELP = PURCHASEORDERITEM
MENGE = QUANTITYINBASEUNIT
ERFMG = QUANTITYINENTRYUNIT
RSNUM = RESERVATION
KZEAR = RESERVATIONISFINALLYISSUED
RSPOS = RESERVATIONITEM
SMBLN = REVERSEDMATERIALDOCUMENT
SMBLP = REVERSEDMATERIALDOCUMENTITEM
SJAHR = REVERSEDMATERIALDOCUMENTYEAR
XWSBR = RVSLOFGOODSRECEIPTISALLOWED
KDAUF = SALESORDER
KDPOS = SALESORDERITEM
KDEIN = SALESORDERSCHEDULELINE
SERVICEPERFORMER = SERVICEPERFORMER
FBUDA = SERVICESRENDEREDDATE
VFDAT = SHELFLIFEEXPIRATIONDATE
DISUB_OWNER = STOCKOWNER
LGPLA = STORAGEBIN
LGORT = STORAGELOCATION
LGTYP = STORAGETYPE
LIFNR = SUPPLIER
DMBTR = TOTALGOODSMVTAMTINCCCRCY
ABLAD = UNLOADINGPOINTNAME
PS_PSP_PNR = WBSELEMENTINTERNALID
WORK_ITEM_ID = WORKITEM