MSPR = I_MATERIALSTOCK
CHARG_SID = BATCH
BUKRS = COMPANYCODE
KALNR = COSTESTIMATE
KUNNR_SID = CUSTOMER
PERIV = FISCALYEARVARIANT
SOBKZ = INVENTORYSPECIALSTOCKTYPE
LBBSA_SID = INVENTORYSTOCKTYPE
MANDT = MANDT
MATBF = MATERIAL
MEINS = MATERIALBASEUNIT
BUDAT = MATLDOCLATESTPOSTGDATE
WERKS = PLANT
MAT_KDAUF = SDDOCUMENT
MAT_KDPOS = SDDOCUMENTITEM
DISUB_OWNER_SID = SPECIALSTOCKIDFGSTOCKOWNER
LGORT_SID = STORAGELOCATION
LIFNR_SID = SUPPLIER
MAT_PSPNR = WBSELEMENTINTERNALID