PACKKP = I_PACKINGINSTRUCTIONHEADER
CRNAM = CREATEDBYUSER
CRDAT = CREATIONDATE
TOLEVOL = EXCESSVOLUMETOLERANCEVALUE
TOLEWEI = EXCESSWEIGHTTOLERANCEVALUE
ALLOVOL = HANDLINGUNITALLOWEDLOADVOLUME
ALLOWEI = HANDLINGUNITALLOWEDLOADWEIGHT
TOTLVOL = HANDLINGUNITGROSSVOLUME
TOTLWEI = HANDLINGUNITGROSSWEIGHT
HEIGHT = HANDLINGUNITHEIGHT
IHEIGHT = HANDLINGUNITINNERHEIGHT
ILENGTH = HANDLINGUNITINNERLENGTH
IWIDTH = HANDLINGUNITINNERWIDTH
INDCLOPA = HANDLINGUNITISCLOSED
LENGTH = HANDLINGUNITLENGTH
LOADVOL = HANDLINGUNITLOADVOLUME
LOADWEI = HANDLINGUNITLOADWEIGHT
SIZEFIX = HANDLINGUNITMEASURESAREFIXED
TAREVOL = HANDLINGUNITTAREVOLUME
UNITVOL = HANDLINGUNITTAREVOLUMEUNIT
TAREWEI = HANDLINGUNITTAREWEIGHT
UNITWEI = HANDLINGUNITTAREWEIGHTUNIT
HU_TYPE = HANDLINGUNITTYPE
UNITDIM = HANDLINGUNITUOMDIMENSION
VOLUMFIX = HANDLINGUNITVOLUMESAREFIXED
UNITVOL_MAX = HANDLINGUNITVOLUMEUNIT
WEIGHTFIX = HANDLINGUNITWEIGHTSAREFIXED
UNITWEI_MAX = HANDLINGUNITWEIGHTUNIT
WIDTH = HANDLINGUNITWIDTH
CHDAT = LASTCHANGEDATE
LASTCHANGEDDATETIME = LASTCHANGEDATETIME
CHNAM = LASTCHANGEDBYUSER
CHTIM = LASTCHANGETIME
MAPACO_ITEM = LOADCARRIERSYSTUUID
MANDT = MANDT
MAXSTWE = PACKINGINSTRUCTIONALLWDLOADQTY
CHECKPROF = PACKINGINSTRUCTIONCHECKPROFSTS
PARTID = PACKINGINSTRUCTIONEXTERNALNAME
INDDEL = PACKINGINSTRUCTIONISDELETED
POBJID = PACKINGINSTRUCTIONNUMBER
PACKNR = PACKINGINSTRUCTIONSYSTEMUUID
STFAC = STACKINGFACTOR
