PACKPO = I_PACKINGINSTRUCTIONCOMPONENT
BASEUNIT = BASEUNITOFMEASURE
INDCHMIX = BATCHMIXISALLOWED
SUBPACKNR = ITEMPACKINGINSTRUCTIONSYSTUUID
MANDT = MANDT
MATNR = MATERIAL
INDNOHU = MATERIALISNOTHANDLINGUNITREL
MATMIXAWD = MATERIALMIXISALLOWED
PACKITEM = PACKINGINSTRUCTIONITEM
PAITEMTYPE = PACKINGINSTRUCTIONITEMCATEGORY
INDDEL = PACKINGINSTRUCTIONITEMISDEL
MINQTY = PACKINGINSTRUCTIONITEMMINQTY
RNDQTY = PACKINGINSTRUCTIONITEMRNDQTY
PACKITEMID = PACKINGINSTRUCTIONITEMSYSTUUID
TRGQTY = PACKINGINSTRUCTIONITMTARGETQTY
PACKNR = PACKINGINSTRUCTIONSYSTEMUUID
UNITQTY = UNITOFMEASURE
