PKHD = I_KANBANCONTROLCYCLE
ZPUNKT = BACKFLUSHREPORTINGPOINT
MEINS = BASEUNIT
CC_PRINT_FORM = CONTROLCYCLEPRINTFORMTEMPLATE
CC_PRINT_QUEUE = CONTROLCYCLEPRINTQUEUE
RKFORM = CONTROLCYCLESAPSCRIPTFORM
KOSTL = COSTCENTER
CRE_DATE = CREATIONDATE
NKDYN = DESTINATIONBINISDYNAMIC
NLPLA = DESTINATIONSTORAGEBIN
LGNUM_EWM = EWMWAREHOUSE
PKSTF = EXTPROCUREMENTREPLNMTSTRGY
PKFMG = FIXEDKANBANCONTAINERQTYINBSUNT
PKSTE = INHOUSEPRODUCTIONREPLNMTSTRGY
PABPRF = JITCALLPROFILE
KBFORM = KANBANCARDFORMTEMPLATE
PKDRS = KANBANCARDPRINTCONTROL
VBQUE = KANBANCARDPRINTQUEUE
KCPRF = KANBANCONTAINERCALCPROFILE
KCART = KANBANCONTAINERCALCULATIONTYPE
PKADR = KANBANCONTAINERDELIVERYADDRESS
PKBHT = KANBANCONTAINERPACKGGPRODUCT
BEHMG = KANBANCONTAINERQUANTITYINBSUNT
PKSFG = KANBANCONTAINERSTATUSSEQUENCE
PKNUM = KANBANCONTROLCYCLE
RKSTA = KANBANCONTROLCYCLECATEGORY
KCSAF = KANBANCTNCALCSAFETYFACTOR
KCCON = KANBANCTNCALCULATIONCONSTANT
KNFZD = KANBANCTNREFILLTIMEINDAYS
KNFZM = KANBANCTNREFILLTMEINHRSANDMINS
PKLOG = KANBANCTNREPLNMTTRIGGERLOGIC
PKRMG = KANBANCTNROUNDINGQTYINBSUNT
KITZD = KANBANCTNTRANSPORTTIMEINDAYS
KWTZD = KANBANCTNWAITTIMEINDAYS
KWTZM = KANBANCTNWAITTIMEINHRSANDMINS
LCM_STATUS = KANBANCTRLCYCLELIFECYCLESTATUS
TRIGGR = KANBANCTRLCYCREPLNMTTRIGGERGRP
KDMBUF = KNBNCTNCALCRQMTBUFFERINPERCENT
KSPBUF = KNBNCTNCALCSUPPLYSRCEBUFINPCT
ALSMG = KNBNCTNREPLNMTTRGGRQTYINBSUNT
KITZM = KNBNCTNTRANSPTTMEINHRSANDMINS
LASTCHANGE_DATETIME = LASTCHANGEDATETIME
OBS_DATE = LOCKDATE
MANDT = MANDT
BERKZ = MATERIALSTAGING
SIGAZ = MAXNROFEMPTYKANBANCONTAINERS
NTREL = NROFKANBANCTNSFLAGGEDTOUNLOCK
TRIGAZ = NROFWAITINGKNBNCTNSBFRREPLNMT
BEHAZ = NUMBEROFKANBANCONTAINERS
ANZLT = NUMBEROFLOADCARRIERS
PACKV = PACKINGINSTRUCTION
CAPA_WRKCT = PLANNINGWORKCENTER
WERKS = PLANT
VBPRN = PRODNSUPPLYSPOOLOUTPUTDEVICE
MATNR = PRODUCT
PKOSA = PRODUCTCOSTCOLLECTOR
FAZUS = PRODUCTIONORDERSARECOMBINED
PRVBE = PRODUCTIONSUPPLYAREA
VERID = PRODUCTIONVERSION
PINTVM = PULLINTERVALINHOURSANDMINUTES
PINTVD = PULLINTERVALINWORKDAYS
EBELN = PURCHASEOUTLINEAGREEMENT
EBELP = PURCHASEOUTLINEAGREEMENTITEM
EKORG = PURCHASINGORGANIZATION
RLS_DATE = RELEASEDATE
ANSWB = REPLNMTISCTRLDBYSUPPLYSOURCE
KWBZM = REPLNMTLEADTIMEINHOURSANDMINS
KWBZD = REPLNMTLEADTIMEINWORKDAYS
VBELN = SALESSCHEDULINGAGREEMENT
VBELP = SALESSCHEDULINGAGREEMENTITEM
QUFKT = SEPARATEGRISNEEDEDIFSETTOFULL
QUPVB = SOURCEPRODUCTIONSUPPLYAREA
VLPLA = SOURCESTORAGEBIN
PKSTU = STOCKTRANSFERREPLNMTSTRATEGY
LGPLA = STORAGEBIN
UMLGO = STORAGELOCATION
LGTYP = STORAGETYPE
ABLAD = STORINGPOSITIONNAME
LIFNR = SUPPLIER
PKUMW = SUPPLYSOURCEPLANT
RGVER = SUPPLYSOURCERESPONSIBLEPERSON
LGNUM = WAREHOUSE
PRCTY = WAREHOUSEPROCESSTYPE
