PLFH = I_MFGBOOOPPRODNRSCETOOLCHGST
PLNNR = BILLOFOPERATIONSGROUP
PLNFL = BILLOFOPERATIONSSEQUENCE
PLNTY = BILLOFOPERATIONSTYPE
PLNAL = BILLOFOPERATIONSVARIANT
PLNKN = BOOOPERATIONINTERNALID
PZLFH = BOOOPERATIONPRTINTERNALID
ZAEHL = BOOOPERATIONPRTINTVERSCOUNTER
AENNR = CHANGENUMBER
USERI = CREATEDBYUSER
DATUI = CREATIONDATE
OFFSTE = ENDDATEOFFSETDURATION
EHOFFE = ENDDATEOFFSETDURATIONUNIT
BZOFFE = ENDDATEOFFSETREFERENCECODE
LOEKZ = ISDELETED
LOEKZ_INHERITED = ISIMPLICITLYDELETED
DATUC = LASTCHANGEDATE
USERC = LASTCHANGEDBYUSER
MANDT = MANDT
STEUF = PRODNRSCETOOLCONTROLPROFILE
PSNFH = PRODNRSCETOOLITEMNUMBER
KTSCH = PRODNRSCETOOLSTANDARDTEXTCODE
MGVGW = PRODNRSCETOOLSTANDARDWORKQTY
MGEINH = PRODNRSCETOOLSTDWORKQTYUNIT
TXTZ1 = PRODNRSCETOOLTEXT
MGFORM = PRODNRSCETOOLTOTQTYCALCFORMULA
EWFORM = PRODNRSCETOOLUSAGEQTYCALCFMLA
EWVGW = PRODNRSCETOOLUSAGEQUANTITY
EWEINH = PRODNRSCETOOLUSAGEQUANTITYUNIT
OBJID = PRODUCTIONRESOURCEINTERNALID
OBJTY = PRODUCTIONRESOURCETYPE
OFFSTB = STARTDATEOFFSETDURATION
EHOFFB = STARTDATEOFFSETDURATIONUNIT
BZOFFB = STARTDATEOFFSETREFERENCECODE
VALID_TO = VALIDITYENDDATE
DATUV = VALIDITYSTARTDATE
