PRCD_ELEMENTS = I_SLSPRCGCONDITIONRECORD
KWAEH = CONDITIONALTERNATIVECURRENCY
KAPPL = CONDITIONAPPLICATION
KRECH = CONDITIONCALCULATIONTYPE
KPEIN = CONDITIONQUANTITY
KMEIN = CONDITIONQUANTITYUNIT
KNUMH = CONDITIONRECORD
KONWS = CONDITIONSCALEAMOUNTCURRENCY
KONMS = CONDITIONSCALEQUANTITYUNIT
KOPOS = CONDITIONSEQUENTIALNUMBER
MWSK1 = CONDITIONTAXCODE
KUMNE = CONDITIONTOBASEQTYDNMNTR
KUMZA = CONDITIONTOBASEQTYNMRTR
KSCHL = CONDITIONTYPE
MWSK2 = CONDITIONWITHHOLDINGTAXCODE
KZBZG = PRICINGSCALEBASIS