QALS = I_INSPECTIONLOT
KNTTP = ACCOUNTASSIGNMENTCATEGORY
BLART = ACCOUNTINGDOCUMENTTYPE
CHARG = BATCH
LICHN = BATCHBYSUPPLIER
LAGORTCHRG = BATCHSTORAGELOCATION
ZAEHL = BILLOFOPERATIONSCHANGESTATEID
PLNNR = BILLOFOPERATIONSGROUP
PLNTY = BILLOFOPERATIONSTYPE
PPLVERW = BILLOFOPERATIONSUSAGE
PLNAL = BILLOFOPERATIONSVARIANT
LS_LLAND = BILLTOPARTYCOUNTRY
GSBER = BUSINESSAREA
BUKRS = COMPANYCODE
KZVBR = CONSUMPTIONPOSTING
KOKRS = CONTROLLINGAREA
KOSTL = COSTCENTER
KUNNR = CUSTOMER
LS_ABRVW = DELIVERYCATEGORY
LS_VBELN = DELIVERYDOCUMENT
LS_POSNR = DELIVERYDOCUMENTITEM
LS_EQUNR = EQUIPMENT
ANLN2 = FIXEDASSET
LS_TPLNR = FUNCTIONALLOCATION
KONTO = GLACCOUNT
BWART = GOODSMOVEMENTTYPE
STAT11 = GOODSRECEIPTISMOVEDTOBLKDSTOCK
LS_ABRVW = INSPECTIONDELIVERYCATEGORY
PRSTUFE = INSPECTIONDYNAMICSTAGE
PRUEFLOS = INSPECTIONLOT
LMENGEIST = INSPECTIONLOTACTUALQUANTITY
QPMATLOS = INSPECTIONLOTALLOWEDSCRAPRATIO
STAT23 = INSPECTIONLOTAPPROVAL
AENDERDAT = INSPECTIONLOTCHANGEDATE
AENDERER = INSPECTIONLOTCHANGEDBY
AENDERZEIT = INSPECTIONLOTCHANGETIME
ANZGEB = INSPECTIONLOTCONTAINER
GEBEH = INSPECTIONLOTCONTAINERUNIT
ERSTELLER = INSPECTIONLOTCREATEDBY
ERSTELDAT = INSPECTIONLOTCREATEDON
ERSTELZEIT = INSPECTIONLOTCREATEDONTIME
LMENGESCH = INSPECTIONLOTDEFECTIVEQUANTITY
DYNHEAD = INSPECTIONLOTDYNAMICLEVEL
PAENDTERM = INSPECTIONLOTENDDATE
PAENDZEIT = INSPECTIONLOTENDTIME
STAT06 = INSPECTIONLOTHASAPPRAISALCOSTS
STAT02 = INSPECTIONLOTHASPARTIALLOTS
INSMK = INSPECTIONLOTHASQUANTITY
STAT35 = INSPECTIONLOTHASUSAGEDECISION
HPZ = INSPECTIONLOTISFULLINSPECTION
KZSKIPLOT = INSPECTIONLOTISSKIPPED
KTEXTMAT = INSPECTIONLOTOBJECTTEXT
HERKUNFT = INSPECTIONLOTORIGIN
WERKVORG = INSPECTIONLOTPLANT
PRIO_PUNKTE = INSPECTIONLOTPRIORITYPOINTS
LOSMENGE = INSPECTIONLOTQUANTITY
MENGENEINH = INSPECTIONLOTQUANTITYUNIT
GESSTICHPR = INSPECTIONLOTSAMPLEQUANTITY
EINHPROBE = INSPECTIONLOTSAMPLEUNIT
ANTEIL = INSPECTIONLOTSCRAPRATIO
PASTRTERM = INSPECTIONLOTSTARTDATE
PASTRZEIT = INSPECTIONLOTSTARTTIME
LAGORTVORG = INSPECTIONLOTSTORAGELOCATION
KTEXTLOS = INSPECTIONLOTTEXT
ART = INSPECTIONLOTTYPE
LOT_GUID = INSPECTIONLOTUUID
PRSCHAERFE = INSPECTIONSEVERITY
STAT13 = INSPECTIONSUBSETTYPE
STAT05 = INSPLOTACCTASSGMTKEY
CHARGNEU = INSPLOTBATCHTRANSFERREDTO
KONT_KDAUF = INSPLOTCOSTCOLLECTORSALESORDER
KONT_KDPOS = INSPLOTCOSTCOLLECTORSLSORDITEM
KONT_PSPNR = INSPLOTCOSTCOLLECTORWBSELEMENT
ENSTEHDAT = INSPLOTCREATEDONLOCALDATE
ENTSTEZEIT = INSPLOTCREATEDONLOCALTIME
STAT25 = INSPLOTDIGITALSGNTRINUSGEDCSN
STAT24 = INSPLOTDIGITALSGNTRRESULTSRECG
DYNREGEL = INSPLOTDYNAMICRULE
STAT44 = INSPLOTDYNAMICTRGGRPOINT
INSP_DOC_NUMBER = INSPLOTEXTERNALNUMBER
STAT43 = INSPLOTFORFIRSTARTICLEINSP
STAT10 = INSPLOTHASCONFIGNSPECIFICATION
STAT21 = INSPLOTHASMANUALSAMPLESIZE
STAT22 = INSPLOTHASMATERIALSPEC
STAT33 = INSPLOTHASMULTIPLESPEC
STAT07 = INSPLOTHASSUBSETS
STAT08 = INSPLOTISAUTOMUSGEDCSNPOSSIBLE
STAT26 = INSPLOTISBATCHREQUIRED
STAT01 = INSPLOTISCREATEDAUTOMATICALLY
STAT19 = INSPLOTISDOCUMENTATIONREQUIRED
EIN = INSPLOTISSERIALNMBRPOSSIBLE
STAT34 = INSPLOTISSTOCKPOSTINGCOMPLETED
STAT20 = INSPLOTISTASKLISTREQUIRED
MATNRNEU = INSPLOTMATERIALPOSTEDTO
ZUSMKZAEHL = INSPLOTNMBRADDLRECORDEDCHARC
OFFEN_LZMK = INSPLOTNMBROPENLONGTERMCHARC
OFFENNLZMK = INSPLOTNMBROPENSHORTTERMCHARC
LMENGEZER = INSPLOTQTYDESTROYED
LMENGEPR = INSPLOTQTYINSPECTED
LMENGE07 = INSPLOTQTYRETURNEDTOSUPPLIER
LMENGE06 = INSPLOTQTYTOANOTHERMATERIAL
LMENGEZUB = INSPLOTQTYTOBEPOSTED
LMENGE04 = INSPLOTQTYTOBLOCKED
LMENGE01 = INSPLOTQTYTOFREE
LMENGE09 = INSPLOTQTYTOOTHERSTOCK
LMENGE05 = INSPLOTQTYTORESERVES
LMENGE03 = INSPLOTQTYTOSAMPLE
LMENGE02 = INSPLOTQTYTOSCRAP
LMENGE08 = INSPLOTQTYTOSPECIALSTOCK
SELPPLVERW = INSPLOTSELBILLOFOPERATIONSUSGE
SELKUNNR = INSPLOTSELECTIONCUSTOMER
SELHERST = INSPLOTSELECTIONMANUFACTURER
SELMATNR = INSPLOTSELECTIONMATERIAL
SELWERK = INSPLOTSELECTIONPLANT
SELLIFNR = INSPLOTSELECTIONSUPPLIER
GUELTIGAB = INSPLOTSELECTIONVALIDFROMDATE
SELREVLV = INSPLOTSELMATLREVISIONLVL
LMENGELZ = INSPLOTSMPLQTYFORLONGTERMCHAR
STAT18 = INSPLOTSUMMARYCONTROL
STAT03 = INSPLOTUSAGEDECISIONTOOL
STAT32 = INSPLOTUSAGEINSTABILITYSTUDY
SLWBEZ = INSPSUBSETFIELDCOMBINATION
SIGNSTRAT_UD = INSPUSGEDCSNDGTLSGNTRSTRGY
SIGN_TYPE_UD = INSPUSGEDCSNDGTLSGNTRTYPE
KDPOS = INVENTORYSPCLSTKSALESDOCITM
KDAUF = INVENTORYSPCLSTKSALESDOCUMENT
CVP_XBLCK = ISBUSINESSPURPOSECOMPLETED
SPRACHE = LANGUAGE
WARPL = MAINTENANCEPLAN
WAPOS = MAINTENANCEPLANITEMINTID
STRAT = MAINTENANCESTRATEGY
MANDANT = MANDT
HERSTELLER = MANUFACTURER
EMATNR = MANUFACTURERPARTNMBR
AUFNR = MANUFACTURINGORDER
ANLN1 = MASTERFIXEDASSET
MATNR = MATERIAL
LS_KDMAT = MATERIALBYCUSTOMER
SOBKZ = MATERIALCOMPISSPECIALSTOCK
MBLNR = MATERIALDOCUMENT
ZEILE = MATERIALDOCUMENTITEM
MJAHR = MATERIALDOCUMENTYEAR
XCHPF = MATERIALISBATCHMANAGED
REVLV = MATERIALREVISIONLEVEL
BUDAT = MATLDOCLATESTPOSTGDATE
QMATAUTH = MATLQUALITYAUTHORIZATIONGROUP
APLZL = NETWORKACTIVITYINTERNALID
ANZSN = NUMBEROFSERIALNUMBERS
AUFPL = ORDERINTERNALBILLOFOPERATIONS
WERK = PLANT
VERID = PRODUCTIONVERSION
PAOBJNR = PROFITABILITYSEGMENT_2
PRCTR = PROFITCENTER
NPLNR = PROJECTNETWORK
EBELN = PURCHASINGDOCUMENT
STAT09 = PURCHASINGDOCUMENTCATEGORY
EBELP = PURCHASINGDOCUMENTITEM
PSTYP = PURCHASINGDOCUMENTITEMCATEGORY
EKORG = PURCHASINGORGANIZATION
AUFNR_CO = QUALITYCOSTCOLLECTOR
AUFPS = RESERVATIONITEM
LS_ROUTE = ROUTE
SA_AUFNR = SALESOPERATIONSPLANNINGORDER
LS_KDAUF = SALESORDER
LS_KDPOS = SALESORDERITEM
PS_PSP_PNR = SALESORDSTOCKWBSELEMENT
LS_VKORG = SALESORGANIZATION
STPRVER = SAMPLINGPROCEDURE
ETENR = SCHEDULELINE
SERNP = SERIALNUMBERPROFILE
PRBNAVERF = SMPLDRAWINGPROCEDURE
PRBNAVV = SMPLDRAWINGPROCEDUREVERSION
STAT12 = SMPLDRWGPROCEDISCONFREQUIRED
LS_KUNAG = SOLDTOPARTY
OBJNR = STATUSOBJECT
OBTYP = STATUSOBJECTCATEGORY
STSMA = STATUSPROFILE
LGPLA = STORAGEBIN
LGTYP = STORAGETYPE
LIFNR = SUPPLIER
LGNUM = WAREHOUSE
