I_INSPSPECIFICATIONVERSION = I_INSPSPECIFICATIONVERSION
ATINN = CHARCINTERNALID
EEANTVERF = DEFECTFRACTIONESTIMATIONPROCED
MKMNR = INSPECTIONSPECIFICATION
ZAEHLER = INSPECTIONSPECIFICATIONPLANT
SORTFELD = INSPECTIONSPECIFICATIONSRCHTXT
LOEKZ = INSPECTIONSPECIFICATIONSTATUS
MASSEINHSW = INSPECTIONSPECIFICATIONUNIT
VERSION = INSPECTIONSPECIFICATIONVERSION
PRFQL = INSPECTORQUALIFICATION
DATAE = INSPSPECCHANGEDATE
AEAUT = INSPSPECCHANGEDBYUSER
STEUERKZ = INSPSPECCONTROLINDICATORS
AUTOR = INSPSPECCREATEDBYUSER
DATES = INSPSPECCREATIONDATE
STELLEN = INSPSPECDECIMALPLACES
CODEGRQUAL = INSPSPECDEFECTCODEGRPREJECTION
CODEGR9U = INSPSPECDEFECTCODEGRPRJCNLOWER
CODEGR9O = INSPSPECDEFECTCODEGRPRJCNUPPER
CODEQUAL = INSPSPECDEFECTCODEREJECTION
CODE9U = INSPSPECDEFECTCODERJCNLOWER
CODE9O = INSPSPECDEFECTCODERJCNUPPER
SPEC_DET_RULE = INSPSPECDETERMINATIONRULE
GRENZEUN1 = INSPSPECFIRSTLOWERSPECLIMIT
GRENZEOB1 = INSPSPECFIRSTUPPERSPECLIMIT
CHARACT_ID1 = INSPSPECGLOBALNAME
GRENZUN1NI = INSPSPECHASFIRSTLOWERSPECLIMIT
GRENZOB1NI = INSPSPECHASFIRSTUPPERSPECLIMIT
TOLUNNI = INSPSPECHASLOWERLIMIT
PLAUSIUNNI = INSPSPECHASLOWRPLAUSIBILITYLMT
TOLWUNNI = INSPSPECHASLOWRSPECLIMITCHANGE
GRENZUN2NI = INSPSPECHASSECONDLOWRSPECLIMIT
GRENZOB2NI = INSPSPECHASSECONDUPRSPECLIMIT
SOLLWNI = INSPSPECHASTARGETVALUE
TOLOBNI = INSPSPECHASUPPERLIMIT
PLAUSIOBNI = INSPSPECHASUPRPLAUSIBILITYLMT
TOLWOBNI = INSPSPECHASUPRSPECLIMITCHANGE
MERKGEW = INSPSPECIMPORTANCECODE
DUMMY10 = INSPSPECINFORMATIONFIELD1
DUMMY20 = INSPSPECINFORMATIONFIELD2
DUMMY40 = INSPSPECINFORMATIONFIELD3
INPPROC = INSPSPECINPUTPROCEDURE
SPEC_DET_ACTIVE = INSPSPECISDETNRULEACTIVE
TOLERANZUN = INSPSPECLOWERLIMIT
PLAUSIUNTE = INSPSPECLOWERPLAUSIBILITYLIMIT
TOLERWEIUN = INSPSPECLOWERSPECLIMITCHANGE
GRENZEUN2 = INSPSPECSECONDLOWERSPECLIMIT
GRENZEOB2 = INSPSPECSECONDUPPERSPECLIMIT
SOLLWERT = INSPSPECTARGETVALUE
TOLERWAB = INSPSPECTOLERANCECHGVALIDFROM
TOLERWBIS = INSPSPECTOLERANCECHGVALIDTO
KONSISTENT = INSPSPECTRANSFERTYPE
TOLERANZOB = INSPSPECUPPERLIMIT
PLAUSIOBEN = INSPSPECUPPERPLAUSIBILITYLIMIT
TOLERWEIOB = INSPSPECUPPERSPECLIMITCHANGE
TOLERANZSL = INSPTOLERANCESPECIFICATION
MANDT = MANDT
WERKS = PLANT
QAUTH = QLTYMSTRDATAAUTHORIZATIONGROUP
GUELTIGAB = VALIDITYSTARTDATE
