RBCO = I_SUPLRINVOICEITEMGLACCTAPI01
ZUONR = ASSIGNMENTREFERENCE
GSBER = BUSINESSAREA
PRZNR = BUSINESSPROCESS
FIPOS = COMMITMENTITEM
BUKRS = COMPANYCODE
KOKRS = CONTROLLINGAREA
KOSTL = COSTCENTER
LSTAR = COSTCTRACTIVITYTYPE
KSTRG = COSTOBJECT
SHKZG = DEBITCREDITCODE
BEWAR = FINANCIALTRANSACTIONTYPE
GJAHR = FISCALYEAR
FKBER = FUNCTIONALAREA
GEBER = FUND
FISTL = FUNDSCENTER
SAKNR = GLACCOUNT
GRANT_NBR = GRANTID
AUFNR = INTERNALORDER
XSKRL = ISNOTCASHDISCOUNTLIABLE
MANDT = MANDT
VORNR = NETWORKACTIVITY
APLZL = NETWORKACTIVITYINTERNALID
PARGB = PARTNERBUSINESSAREA
PERNR = PERSONNELNUMBER
PRCTR = PROFITCENTER
NPLNR = PROJECTNETWORK
AUFPL = PROJECTNETWORKINTERNALID
MENGE = QUANTITY
MEINS = QUANTITYUNIT
VBELN = SALESORDER
VBELP = SALESORDERITEM
SERVICE_DOC_ID = SERVICEDOCUMENT
SERVICE_DOC_ITEM_ID = SERVICEDOCUMENTITEM
SERVICE_DOC_TYPE = SERVICEDOCUMENTTYPE
BELNR = SUPPLIERINVOICE
COBL_NR = SUPPLIERINVOICEITEM
WRBTR = SUPPLIERINVOICEITEMAMOUNT
SGTXT = SUPPLIERINVOICEITEMTEXT
MWSKZ = TAXCODE
TAX_COUNTRY = TAXCOUNTRY
TXJCD = TAXJURISDICTION
PS_PSP_PNR = WBSELEMENTINTERNALID
PS_PSP_PNR = WBSELEMENTINTERNALID_2
WORK_ITEM_ID = WORKITEM
