RBKP = I_SUPPLIERINVOICEAPI01
BLART = ACCOUNTINGDOCUMENTTYPE
ZUONR = ASSIGNMENTREFERENCE
BVTYP = BPBANKACCOUNTINTERNALID
BUPLA = BUSINESSPLACE
ZBD1T = CASHDISCOUNT1DAYS
ZBD1P = CASHDISCOUNT1PERCENT
ZBD2T = CASHDISCOUNT2DAYS
ZBD2P = CASHDISCOUNT2PERCENT
BUKRS = COMPANYCODE
ERFNAM = CREATEDBYUSER
CPUDT = CREATIONDATE
EGMLD = DELIVERYOFGOODSREPORTINGCNTRY
WAERS = DOCUMENTCURRENCY
BLDAT = DOCUMENTDATE
BKTXT = DOCUMENTHEADERTEXT
ZFBDT = DUECALCULATIONBASEDATE
LOGMX_UUID = ELECTRONICINVOICEUUID
KURSF = EXCHANGERATE
GJAHR = FISCALYEAR
ZBFIX = FIXEDCASHDISCOUNT
RMWWR = INVOICEGROSSAMOUNT
REBZG = INVOICEREFERENCE
REBZJ = INVOICEREFERENCEFISCALYEAR
LIFNR = INVOICINGPARTY
XEGDR = ISEUTRIANGULARDEAL
XRECH = ISINVOICE
GLO_BP1_HD = JRNLENTRYCNTRYSPECIFICBP1
GLO_BP2_HD = JRNLENTRYCNTRYSPECIFICBP2
GLO_DAT1_HD = JRNLENTRYCNTRYSPECIFICDATE1
GLO_DAT2_HD = JRNLENTRYCNTRYSPECIFICDATE2
GLO_DAT3_HD = JRNLENTRYCNTRYSPECIFICDATE3
GLO_DAT4_HD = JRNLENTRYCNTRYSPECIFICDATE4
GLO_DAT5_HD = JRNLENTRYCNTRYSPECIFICDATE5
GLO_REF1_HD = JRNLENTRYCNTRYSPECIFICREF1
GLO_REF2_HD = JRNLENTRYCNTRYSPECIFICREF2
GLO_REF3_HD = JRNLENTRYCNTRYSPECIFICREF3
GLO_REF4_HD = JRNLENTRYCNTRYSPECIFICREF4
GLO_REF5_HD = JRNLENTRYCNTRYSPECIFICREF5
USNAM = LASTCHANGEDBYUSER
MANDT = MANDT
WSKTO = MANUALCASHDISCOUNT
ZBD3T = NETPAYMENTDAYS
ZLSCH = PAYMENTMETHOD
PAYT_RSN = PAYMENTREASON
KIDNO = PAYMENTREFERENCE
ZTERM = PAYMENTTERMS
ESRPZ = PAYTSLIPWTHREFCHECKDIGIT
ESRRE = PAYTSLIPWTHREFREFERENCE
ESRNR = PAYTSLIPWTHREFSUBSCRIBER
BUDAT = POSTINGDATE
STBLG = REVERSEDOCUMENT
STJAH = REVERSEDOCUMENTFISCALYEAR
LZBKZ = STATECENTRALBANKPAYMENTREASON
ARKUEN = SUPLRINVCAUTOMREDUCEDAMOUNT
LIEFFN = SUPLRINVCMANUALLYREDUCEDAMOUNT
BELNR = SUPPLIERINVOICE
XBLNR = SUPPLIERINVOICEIDBYINVCGPARTY
IVTYP = SUPPLIERINVOICEORIGIN
RBSTAT = SUPPLIERINVOICESTATUS
SGTXT = SUPPLIERPOSTINGLINEITEMTEXT
STCEG = SUPPLIERVATREGISTRATION
LANDL = SUPPLYINGCOUNTRY
TAX_COUNTRY = TAXCOUNTRY
TXDAT = TAXDETERMINATIONDATE
FULFILLDATE = TAXFULFILLMENTDATE
XMWST = TAXISCALCULATEDAUTOMATICALLY
VATDATE = TAXREPORTINGDATE
BEZNK = UNPLANNEDDELIVERYCOST
MWSKZ_BNK = UNPLANNEDDELIVERYCOSTTAXCODE
TXJCD_BNK = UNPLNDDELIVCOSTTAXJURISDICTION
TAX_COUNTRY_BNK = UNPLNDDELIVERYCOSTTAXCOUNTRY
