ACDOCA.0.properties = ACDOCA 
ACDOCA.1.properties = ACDOCA 
ACDOCA.2.properties = ACDOCA 
AFKO.0.properties = AFKO 
AFPO.0.properties = AFPO 
AFRU.0.properties = AFRU 
AFVC.0.properties = AFVC 
AFVU.0.properties = AFVU 
AFVV.0.properties = AFVV 
AUFK.0.properties = AUFK 
BKPF.0.properties = BKPF 
BNKA.0.properties = BNKA 
BSEC.0.properties = BSEC 
BSED.0.properties = BSED 
BSEG.0.properties = BSEG 
BSEG_ADD.0.properties = BSEG_ADD 
BUT000.0.properties = BUT000 
CEPC.0.properties = CEPC 
CEPCT.0.properties = CEPCT 
CRHD.0.properties = CRHD 
CRTX.0.properties = CRTX 
CSKS.0.properties = CSKS 
CSKT.0.properties = CSKT 
CSLA.0.properties = CSLA 
CSLT.0.properties = CSLT 
DD07L.0.properties = DD07L 
DD07T.0.properties = DD07T 
DFKKKO.0.properties = DFKKKO 
DFKKOP.0.properties = DFKKOP 
DFKKOPK.0.properties = DFKKOPK 
EBAN.0.properties = EBAN 
EBKN.0.properties = EBKN 
EINA.0.properties = EINA 
EINE.0.properties = EINE 
EKBE.0.properties = EKBE 
EKES.0.properties = EKES 
EKET.0.properties = EKET 
EKKN.0.properties = EKKN 
EKKO.0.properties = EKKO 
EKPA.0.properties = EKPA 
EKPO.0.properties = EKPO 
EORD.0.properties = EORD 
EQUK.0.properties = EQUK 
EQUP.0.properties = EQUP 
FKKVK.0.properties = FKKVK 
FKKVKP.0.properties = FKKVKP 
KBED.0.properties = KBED 
KNA1.0.properties = KNA1 
KNB1.0.properties = KNB1 
KNB5.0.properties = KNB5 
KNBK.0.properties = KNBK 
KNVI.0.properties = KNVI 
KNVK.0.properties = KNVK 
KNVP.0.properties = KNVP 
KNVV.0.properties = KNVV 
KONH.0.properties = KONH 
KONM.0.properties = KONM 
KONP.0.properties = KONP 
KONV.0.properties = KONV 
LFA1.0.properties = LFA1 
LFAS.0.properties = LFAS 
LFB1.0.properties = LFB1 
LFBK.0.properties = LFBK 
LFM1.0.properties = LFM1 
LIKP.0.properties = LIKP 
LIPS.0.properties = LIPS 
MARA.0.properties = MARA 
MARA.1.properties = MARA 
MARA.2.properties = MARA 
MARA.3.properties = MARA 
MARA.4.properties = MARA 
MARC.0.properties = MARC 
MARC.1.properties = MARC 
MARC.2.properties = MARC 
MARC.3.properties = MARC 
MARC.4.properties = MARC 
MARC.5.properties = MARC 
MARC.6.properties = MARC 
MARC.7.properties = MARC 
MARC.8.properties = MARC 
MARD.0.properties = MARD 
MARM.0.properties = MARM 
MATDOC.0.properties = MATDOC 
MCH1.0.properties = MCH1 
MCHA.0.properties = MCHA 
MKAL.0.properties = MKAL 
MKPF.0.properties = MKPF 
MSEG.0.properties = MSEG 
MSKA.0.properties = MSKA 
MSKU.0.properties = MSKU 
MSLB.0.properties = MSLB 
MSLBH.0.properties = MSLBH 
MSPR.0.properties = MSPR 
PACKKP.0.properties = PACKKP 
PACKPO.0.properties = PACKPO 
PKHD.0.properties = PKHD 
PLFH.0.properties = PLFH 
PLKO.0.properties = PLKO 
PLPO.0.properties = PLPO 
PRCD_ELEMENTS.0.properties = PRCD_ELEMENTS 
QALS.0.properties = QALS 
QPCT.0.properties = QPCT 
QPCT.1.properties = QPCT 
QPCT.2.properties = QPCT 
QPMK.0.properties = QPMK 
RBCO.0.properties = RBCO 
RBKP.0.properties = RBKP 
RBSELBEST.0.properties = RBSELBEST 
RESB.0.properties = RESB 
RKWA.0.properties = RKWA 
RSEG.0.properties = RSEG 
SKA1.0.properties = SKA1 
SKAT.0.properties = SKAT 
SKB1.0.properties = SKB1 
T001.0.properties = T001 
T002.0.properties = T002 
T002T.0.properties = T002T 
T003.0.properties = T003 
T004.0.properties = T004 
T005.0.properties = T005 
T005T.0.properties = T005T 
T006.0.properties = T006 
T006A.0.properties = T006A 
T006B.0.properties = T006B 
T006C.0.properties = T006C 
T006D.0.properties = T006D 
T006I.0.properties = T006I 
T006J.0.properties = T006J 
T006T.0.properties = T006T 
T006T.1.properties = T006T 
T008.0.properties = T008 
T008T.0.properties = T008T 
T014.0.properties = T014 
T014T.0.properties = T014T 
T024.0.properties = T024 
T024D.0.properties = T024D 
T024E.0.properties = T024E 
T027A.0.properties = T027A 
T027B.0.properties = T027B 
T040S.0.properties = T040S 
T048.0.properties = T048 
T074T.0.properties = T074T 
T074U.0.properties = T074U 
T077X.0.properties = T077X 
T151.0.properties = T151 
T151T.0.properties = T151T 
T156.0.properties = T156 
T161.0.properties = T161 
T161T.0.properties = T161T 
T163D.0.properties = T163D 
T163I.0.properties = T163I 
T163K.0.properties = T163K 
T166C.0.properties = T166C 
T166K.0.properties = T166K 
T166P.0.properties = T166P 
T166T.0.properties = T166T 
T171T.0.properties = T171T 
T178.0.properties = T178 
T188.0.properties = T188 
T189.0.properties = T189 
T459A.0.properties = T459A 
T683.0.properties = T683 
T683S.0.properties = T683S 
T683T.0.properties = T683T 
T685.0.properties = T685 
T685A.0.properties = T685A 
T685T.0.properties = T685T 
TADIR.0.properties = TADIR 
TBSL.0.properties = TBSL 
TCURC.0.properties = TCURC 
TCURF.0.properties = TCURF 
TCURN.0.properties = TCURN 
TCURR.0.properties = TCURR 
TCURT.0.properties = TCURT 
TCURV.0.properties = TCURV 
TCURX.0.properties = TCURX 
TDEVC.0.properties = TDEVC 
TINC.0.properties = TINC 
TINCT.0.properties = TINCT 
TKA01.0.properties = TKA01 
TKA02.0.properties = TKA02 
TPAR.0.properties = TPAR 
TPAR.1.properties = TPAR 
TPART.0.properties = TPART 
TPRIO.0.properties = TPRIO 
TSKD.0.properties = TSKD 
TSKDT.0.properties = TSKDT 
TSPA.0.properties = TSPA 
TSPAT.0.properties = TSPAT 
TSTL.0.properties = TSTL 
TTYPT.0.properties = TTYPT 
TVAG.0.properties = TVAG 
TVAGT.0.properties = TVAGT 
TVAK.0.properties = TVAK 
TVAKT.0.properties = TVAKT 
TVAP.0.properties = TVAP 
TVAPT.0.properties = TVAPT 
TVAU.0.properties = TVAU 
TVAUT.0.properties = TVAUT 
TVBUR.0.properties = TVBUR 
TVBVK.0.properties = TVBVK 
TVCIN.0.properties = TVCIN 
TVCINT.0.properties = TVCINT 
TVEPT.0.properties = TVEPT 
TVFK.0.properties = TVFK 
TVFKT.0.properties = TVFKT 
TVFS.0.properties = TVFS 
TVFST.0.properties = TVFST 
TVGRT.0.properties = TVGRT 
TVKBT.0.properties = TVKBT 
TVKBZ.0.properties = TVKBZ 
TVKGG.0.properties = TVKGG 
TVKGGT.0.properties = TVKGGT 
TVKGR.0.properties = TVKGR 
TVKO.0.properties = TVKO 
TVKOT.0.properties = TVKOT 
TVKOV.0.properties = TVKOV 
TVKT.0.properties = TVKT 
TVKWZ.0.properties = TVKWZ 
TVLK.0.properties = TVLK 
TVLKT.0.properties = TVLKT 
TVLS.0.properties = TVLS 
TVLST.0.properties = TVLST 
TVM1.0.properties = TVM1 
TVM1T.0.properties = TVM1T 
TVM2.0.properties = TVM2 
TVM2T.0.properties = TVM2T 
TVM3.0.properties = TVM3 
TVM3T.0.properties = TVM3T 
TVM4.0.properties = TVM4 
TVM4T.0.properties = TVM4T 
TVM5.0.properties = TVM5 
TVM5T.0.properties = TVM5T 
TVPT.0.properties = TVPT 
TVSB.0.properties = TVSB 
TVSBT.0.properties = TVSBT 
TVST.0.properties = TVST 
TVSTT.0.properties = TVSTT 
TVTA.0.properties = TVTA 
TVTW.0.properties = TVTW 
TVTWT.0.properties = TVTWT 
TVV1.0.properties = TVV1 
TVV1T.0.properties = TVV1T 
TVV2.0.properties = TVV2 
TVV2T.0.properties = TVV2T 
TVV3.0.properties = TVV3 
TVV3T.0.properties = TVV3T 
TVV4.0.properties = TVV4 
TVV4T.0.properties = TVV4T 
TVV5.0.properties = TVV5 
TVV5T.0.properties = TVV5T 
TVZBT.0.properties = TVZBT 
UKMBP_CMS_SGM.0.properties = UKMBP_CMS_SGM 
UKMCRED_SGM0T.0.properties = UKMCRED_SGM0T 
VBAK.0.properties = VBAK 
VBAP.0.properties = VBAP 
VBEP.0.properties = VBEP 
VBFA.0.properties = VBFA 
VBFS.0.properties = VBFS 
VBKD.0.properties = VBKD 
VBRK.0.properties = VBRK 
VBRP.0.properties = VBRP 
VEDA.0.properties = VEDA 
VEKP.0.properties = VEKP 
VEKP.1.properties = VEKP 
VEPO.0.properties = VEPO 
VEPO.1.properties = VEPO 
WBASSOC.0.properties = WBASSOC 
WBASSOC.1.properties = WBASSOC 
WBGT.0.properties = WBGT 
WBHF.0.properties = WBHF 
WBIT.0.properties = WBIT 
T001W.0.properties = T001W 