RESB = I_RESERVATIONDOCUMENTITEM
MEINS = BASEUNIT
CHARG = BATCH
WAERS = COMPANYCODECURRENCY
VMENG = CONFDQTYFORATPINBASEUOM
SHKZG = DEBITCREDITCODE
ERFME = ENTRYUNIT
SAKNR = GLACCOUNT
XWAOK = GOODSMOVEMENTISALLOWED
BWART = GOODSMOVEMENTTYPE
WEMPF = GOODSRECIPIENTNAME
SOBKZ = INVENTORYSPECIALSTOCKTYPE
UMWRK = ISSUINGORRECEIVINGPLANT
UMLGO = ISSUINGORRECEIVINGSTORAGELOC
MANDT = MANDT
VORNR = MANUFACTURINGORDEROPERATION
DBSKZ = MATERIALCOMPISPROCUREDDIRECTLY
MATKL = MATERIALGROUP
BDTER = MATLCOMPREQUIREMENTDATE
WERKS = PLANT
MATNR = PRODUCT
EBELN = PURCHASINGDOCUMENT
EBELP = PURCHASINGDOCUMENTITEM
FMENG = QUANTITYISFIXED
RECIPIENT_LOCATION_CODE = RECIPIENTLOCATIONCODE
RSART = RECORDTYPE
BDART = REQUIREMENTTYPE
RSNUM = RESERVATION
RSPOS = RESERVATIONITEM
RSSTA = RESERVATIONITEMCREATIONCODE
KZEAR = RESERVATIONITEMISFINALLYISSUED
SGTXT = RESERVATIONITEMTEXT
XLOEK = RESERVATIONITMISMARKEDFORDELTN
KTOMA = RESVNACCOUNTISENTEREDMANUALLY
BDMNG = RESVNITMREQUIREDQTYINBASEUNIT
ERFMG = RESVNITMREQUIREDQTYINENTRYUNIT
SERVICE_DOC_ID = RESVNITMSRVCDOCASACCTASGT
SERVICE_DOC_ITEM_ID = RESVNITMSRVCDOCITMASACCTASGT
SERVICE_DOC_TYPE = RESVNITMSRVCDOCTYPEASACCTASGT
ENWRT = RESVNITMWITHDRAWNAMTINCCCRCY
ENMNG = RESVNITMWITHDRAWNQTYINBASEUNIT
CRM_HEADER_ID = SERVICEDOCUMENT
CRMS4_ITEM_ID = SERVICEDOCUMENTITEM
HEADER_BUS_TYPE = SERVICEOBJECTTYPE
PSPEL = SPECIALSTOCKIDFGWBSELEMENT
LGORT = STORAGELOCATION
LIFNR = SUPPLIER
ABLAD = UNLOADINGPOINTNAME
