RKWA = I_SUPCSGNMTPPLINEWTHDRWLAPI01
GSBER = BUSINESSAREA
BUKRS = COMPANYCODE
LIFNR = CONSIGNMENTPIPELINESUPPLIER
SHKZG = DEBITCREDITCODE
BWAER = DOCUMENTCURRENCY
BLDAT = DOCUMENTDATE
HKONT = GLACCOUNT
SOBKZ = ISSGORRCVGSTKIDFGSPCLSTKTYPE
MANDT = MANDT
MATNR = MATERIAL
MBLNR = MATERIALDOCUMENT
ZEILE = MATERIALDOCUMENTITEM
MJAHR = MATERIALDOCUMENTYEAR
NAVNW = NONDEDUCTIBLEINPUTTAXAMOUNT
WERKS = PLANT
BUDAT = POSTINGDATE
PRCTR = PROFITCENTER
BSTME = SUPCSGNMTPPLINEWTHDRWLQTYUNIT
WRBTR = SUPLRCSGNMTPPLINEWTHDRWLAMOUNT
BSTMG = SUPLRCSGNMTPPLINEWTHDRWLQTY
STATUS = SUPLRCSGNMTPPLINEWTHDRWLSTATUS
MWSKZ = TAXCODE
TAX_COUNTRY = TAXCOUNTRY
