RSEG = I_SUPLRINVCITEMPURORDREFAPI01
SHKZG = DEBITCREDITCODE
GJAHR = FISCALYEAR
LIFNR = FREIGHTSUPPLIER
XSKRL = ISNOTCASHDISCOUNTLIABLE
TBTKZ = ISSUBSEQUENTDEBITCREDIT
MANDT = MANDT
WERKS = PLANT
EBELN = PURCHASEORDER
EBELP = PURCHASEORDERITEM
MATNR = PURCHASEORDERITEMMATERIAL
BPRME = PURCHASEORDERPRICEUNIT
BSTME = PURCHASEORDERQUANTITYUNIT
BPMNG = QTYINPURCHASEORDERPRICEUNIT
MENGE = QUANTITYINPURCHASEORDERUNIT
LFBNR = REFERENCEDOCUMENT
LFGJA = REFERENCEDOCUMENTFISCALYEAR
LFPOS = REFERENCEDOCUMENTITEM
ZAEHK = SUPLRINVCDELIVERYCOSTCNDNCOUNT
STUNR = SUPLRINVCDELIVERYCOSTCNDNSTEP
KSCHL = SUPLRINVCDELIVERYCOSTCNDNTYPE
SPGRS = SUPLRINVCITEMHASAMOUNTOUTSDTOL
SPGRT = SUPLRINVCITEMHASDATEVARIANCE
SPGRG = SUPLRINVCITEMHASORDPRCQTYVARC
SPGRQ = SUPLRINVCITEMHASOTHERVARIANCE
SPGRP = SUPLRINVCITEMHASPRICEVARIANCE
SPGRM = SUPLRINVCITEMHASQTYVARIANCE
SPGRC = SUPLRINVCITMHASQUALITYVARIANCE
BNKAN = SUPLRINVCITMUNPLNDDELIVCOST
BELNR = SUPPLIERINVOICE
BUZEI = SUPPLIERINVOICEITEM
WRBTR = SUPPLIERINVOICEITEMAMOUNT
SGTXT = SUPPLIERINVOICEITEMTEXT
MWSKZ = TAXCODE
TAX_COUNTRY = TAXCOUNTRY
TXJCD = TAXJURISDICTION
