SKA1 = I_GLACCOUNTINCHARTOFACCOUNTS
XSPEA = ACCOUNTISBLOCKEDFORCREATION
XSPEP = ACCOUNTISBLOCKEDFORPLANNING
XSPEB = ACCOUNTISBLOCKEDFORPOSTING
XLOEV = ACCOUNTISMARKEDFORDELETION
MAIN_SAKNR = BANKRECONCILIATIONACCOUNT
KTOPL = CHARTOFACCOUNTS
BILKT = CORPORATEGROUPACCOUNT
ERNAM = CREATEDBYUSER
ERDAT = CREATIONDATE
FUNC_AREA = FUNCTIONALAREA
SAKNR = GLACCOUNT
SAKAN = GLACCOUNTEXTERNAL
KTOKS = GLACCOUNTGROUP
GLACCOUNT_SUBTYPE = GLACCOUNTSUBTYPE
GLACCOUNT_TYPE = GLACCOUNTTYPE
XBILK = ISBALANCESHEETACCOUNT
LAST_CHANGED_TS = LASTCHANGEDATETIME
MANDT = MANDT
VBUND = PARTNERCOMPANY
GVTYP = PROFITLOSSACCOUNTTYPE
MUSTR = SAMPLEGLACCOUNT
