SKB1 = I_GLACCOUNTINCOMPANYCODE
BUSAB = ACCOUNTINGCLERK
XSPEB = ACCOUNTISBLOCKEDFORPOSTING
XLOEB = ACCOUNTISMARKEDFORDELETION
ZUAWA = ACCTGDOCITMDISPLAYSEQUENCERULE
ALTKT = ALTERNATIVEGLACCOUNT
TOGRU = APARTOLERANCEGROUP
BEGRU = AUTHORIZATIONGROUP
XSALH = BALANCEHASLOCALCURRENCY
FDGRV = CASHPLANNINGGROUP
XLGCLR = CLEARINGISLEDGERGROUPSPECIFIC
FIPOS = COMMITMENTITEM
FIPOS = COMMITMENTITEMSHORTID
BUKRS = COMPANYCODE
ERNAM = CREATEDBYUSER
ERDAT = CREATIONDATE
KDFSL = EXCHRATEDIFFERENCESACCOUNTDETN
FSTAG = FIELDSTATUSGROUP
SAKNR = GLACCOUNT
WAERS = GLACCOUNTCURRENCY
INFKY = GLACCTINFLATIONKEY
HBKID = HOUSEBANK
HKTID = HOUSEBANKACCOUNT
VZSKZ = INTERESTCALCULATIONCODE
ZINDT = INTERESTCALCULATIONDATE
ZINRT = INTRSTCALCFREQUENCYINMONTHS
XINTB = ISAUTOMATICALLYPOSTED
XGKON = ISCASHFLOWACCOUNT
X_UJ_CLR = ISEXTENDEDOPENITEMMANAGED
XOPVW = ISOPENITEMMANAGED
RECID = JOINTVENTURERECOVERYCODE
DATLZ = LASTINTERESTCALCRUNDATE
XKRES = LINEITEMDISPLAYISENABLED
MANDT = MANDT
MCAKEY = MULTICURRENCYACCOUNTINGCODE
FDLEV = PLANNINGLEVEL
MITKZ = RECONCILIATIONACCOUNTTYPE
XMITK = RECONCILIATIONACCTISCHANGEABLE
XNKON = SUPPLEMENTISALLOWED
MWSKZ = TAXCATEGORY
XMWNO = TAXCODEISREQUIRED
BEWGP = VALUATIONGROUP
