TADIR = I_CUSTABAPOBJDIRECTORYENTRY
OBJ_NAME = ABAPOBJECT
PGMID = ABAPOBJECTCATEGORY
DELFLAG = ABAPOBJECTISDELETED
AUTHOR = ABAPOBJECTRESPONSIBLEUSER
OBJECT = ABAPOBJECTTYPE
DEVCLASS = ABAPPACKAGE
