TBSL = I_POSTINGKEY
SHKZG = DEBITCREDITCODE
KOART = FINANCIALACCOUNTTYPE
XUMSW = ISSALESRELATED
XSONU = ISSPECIALGLTRANSACTION
XZAHL = ISUSEDINPAYMENTTRANSACTION
MANDT = MANDT
BSCHL = POSTINGKEY
STBSL = REVERSALPOSTINGKEY
