TCURR = I_EXCHANGERATERAWDATA
UKURS = EXCHANGERATE
KURST = EXCHANGERATETYPE
MANDT = MANDT
FFACT = NUMBEROFSOURCECURRENCYUNITS
TFACT = NUMBEROFTARGETCURRENCYUNITS
FCURR = SOURCECURRENCY
TCURR = TARGETCURRENCY
