TCURV = I_EXCHANGERATETYPE
GKUZU = BUYINGRATEAVGEXCHANGERATETYPE
KURST = EXCHANGERATETYPE
XFIXD = FIXEDEXCHANGERATEISUSED
XINVR = INVERTEDEXCHANGERATEISALLOWED
MANDT = MANDT
BWAER = REFERENCECURRENCY
BKUZU = SELLINGRATEAVGEXCHANGERATETYPE
XBWRL = SOURCECURRENCYISBASECURRENCY
XEURO = SPECIALCONVERSIONISUSED
