TCURF = I_EXCHANGERATEFACTORSRAWDATA
ABWCT = ALTERNATIVEEXCHANGERATETYPE
ABWGA = ALTVEXCHANGERATETYPEVALDTYDATE
KURST = EXCHANGERATETYPE
MANDT = MANDT
FFACT = NUMBEROFSOURCECURRENCYUNITS
TFACT = NUMBEROFTARGETCURRENCYUNITS
FCURR = SOURCECURRENCY
TCURR = TARGETCURRENCY
