TDEVC = I_CUSTABAPPACKAGE
NAMESPACE = ABAPNAMESPACE
DEVCLASS = ABAPPACKAGE
AS4USER = ABAPPACKAGERESPONSIBLEUSER
DLVUNIT = ABAPSOFTWARECOMPONENT
CREATED_BY = CREATEDBYUSER
CREATED_ON = CREATIONDATE
CHANGED_ON = LASTCHANGEDATE
CHANGED_BY = LASTCHANGEDBYUSER
