TKA01 = I_CONTROLLINGAREA
BPHINR = BUSINESSPROCESSSTANDARDHIER
KTOPL = CHARTOFACCOUNTS
KOKRS = CONTROLLINGAREA
WAERS = CONTROLLINGAREACURRENCY
CTYP = CONTROLLINGAREACURRENCYROLE
BEZEI = CONTROLLINGAREANAME
VNAME = CONTROLLINGAREARESPONSIBLEUSER
KHINR = COSTCENTERSTANDARDHIERARCHY
KSTAR_FIN = CREDITDOWNPAYMENTDEFAULTGLACCT
LEADING_FSV = CTRLGSTDFINSTATEMENTVERSION
KSTAR_FID = DEBITDOWNPAYMENTDEFAULTGLACCT
DEFPRCTR = DEFAULTPROFITCENTER
FIKRS = FINANCIALMANAGEMENTAREA
LMONA = FISCALYEARVARIANT
MANDT = MANDT
ERKRS = OPERATINGCONCERN
PHINR = PROFITCENTERSTANDARDHIERARCHY
