TVAK = I_SALESDOCUMENTTYPE
LIFSK = DELIVERYBLOCKREASON
SPERR = ISLOCKED
BEZOB = MANDATORYREFERENCESDDOCCAT
MANDT = MANDT
NUMKE = NUMBERRANGEFOREXTIDASSIGNMENT
NUMKI = NUMBERRANGEFORINTIDASSIGNMENT
AUFAK = ORDERTYPEFORBILLINGREQUEST
PARGR = PARTNERDETERMINATIONPROCEDURE
MSR_ACTIVE = RETSMGMTISACTIVE
VBKLT = SALESDOCUMENTPROCESSINGTYPE
AUART = SALESDOCUMENTTYPE
KOPGR = SCREENSEQUENCEGROUP
VBTYP = SDDOCUMENTCATEGORY
PVBSM = SLSDOCPRODPROPOSALPROCEDURE
TXTGR = TEXTDETERMINATIONPROCEDURE
ITMAC = TRADECOMPLIANCEISACTIVE
