TVAP = I_SALESDOCUMENTITEMCATEGORY
FKREL = BILLINGRELEVANCECODE
EVRWR = COSTDETERMINATIONISREQUIRED
MANDT = MANDT
PARGR = PARTNERDETERMINATIONPROCEDURE
PRSFD = PRICINGRELEVANCE
PROPAGATE_PAOBJNR_BOM = PROPAGATEPRFTBLTYSGMT2BOM
PSTYV = SALESDOCUMENTITEMCATEGORY
ETERL = SCHEDULELINEISALLOWED
TXTGR = TEXTDETERMINATIONPROCEDURE
