TVFK = I_BILLINGDOCUMENTTYPE
TXTGR_P = BILLGPROCDOCITMTXTDETNPROCED
TXTGR = BILLGPROCDOCTXTDETNPROCEDURE
FKTYP = BILLINGDOCUMENTCATEGORY
FKART = BILLINGDOCUMENTTYPE
INCPO = INCREMENTITEMNUMBER
MANDT = MANDT
VBTYP = SDDOCUMENTCATEGORY
