TVKO = I_SALESORGANIZATION
ADRNR = ADDRESSID
J_1ANUTIME = ARGENTINADELIVERYDATEEVENT
BUKRS = COMPANYCODE
KUNNR = INTERCOMPANYBILLINGCUSTOMER
MANDT = MANDT
VKORG = SALESORGANIZATION
WAERS = SALESORGANIZATIONCURRENCY
XSTCEG = VATREGNNUMBERDETERMINATIONRULE
