TVTA = I_SALESAREA
REVFP = ATPRESULTMODECONTROL
KKBER = CREDITCONTROLAREA
VTWEG = DISTRIBUTIONCHANNEL
SPART = DIVISION
MANDT = MANDT
VTWAU = REFDISTRCHNLFORSLSDOCTYPE
SPAAU = REFDIVISIONFORSLSDOCTYPE
VTWKU = REFERENCEDISTRIBUTIONCHANNEL
SPAKU = REFERENCEDIVISION
VKOAU = REFSLSORGFORSLSDOCTYPE
VKORG = SALESORGANIZATION
