UKMBP_CMS_SGM = I_CREDITMANAGEMENTACCOUNT
PARTNER = BUSINESSPARTNER
XCRITICAL = BUSINESSPARTNERISCRITICAL
AUTOMATIC_REQ = CRDTLMTISREQDFRMAUTOMCALC
BLOCK_REASON = CREDITACCOUNTBLOCKREASON
XBLOCKED = CREDITACCOUNTISBLOCKED
FOLLOW_UP_DT = CREDITACCOUNTRESUBMISSIONDATE
COORDINATOR = CREDITCOORDINATOR
CRED_LIM_CALC = CREDITLIMITCALCULATEDAMOUNT
X_LIMIT_ZERO = CREDITLIMITISZERO
LIMIT_CHG_DATE = CREDITLIMITLASTCHANGEDATE
LIM_VAL_DATE_REQ = CREDITLIMITREQDVALIDITYENDDATE
REQ_DATE = CREDITLIMITREQUESTDATE
CRED_LIM_REQ = CREDITLIMITREQUESTEDAMOUNT
LIMIT_VALID_DATE = CREDITLIMITVALIDITYENDDATE
CREDIT_SGMNT = CREDITSEGMENT
CREDIT_LIMIT = CUSTOMERCREDITLIMITAMOUNT
CLIENT = MANDT
