VBAK = I_SALESDOCUMENT
XBLNR = ACCOUNTINGDOCEXTERNALREFERENCE
KVGR1 = ADDITIONALCUSTOMERGROUP1
KVGR2 = ADDITIONALCUSTOMERGROUP2
KVGR3 = ADDITIONALCUSTOMERGROUP3
KVGR4 = ADDITIONALCUSTOMERGROUP4
KVGR5 = ADDITIONALCUSTOMERGROUP5
GUEEN = AGRMTVALDTYENDDATE
GUEBG = AGRMTVALDTYSTARTDATE
CROSSITEM_PRC_DATE = ALTERNATIVEPRICINGDATE
ZUONR = ASSIGNMENTREFERENCE
BUKRS_VF = BILLINGCOMPANYCODE
BNDDT = BINDINGPERIODVALIDITYENDDATE
ANGDT = BINDINGPERIODVALIDITYSTARTDATE
GSBER = BUSINESSAREA
SOLUTION_ORDER_ID = BUSINESSSOLUTIONORDER
CMPS_CM = CENTRALCREDITCHECKSTATUS
CMPS_TE = CENTRALCREDITCHKTECHERRSTS
AUTLF = COMPLETEDELIVERYISDEFINED
DP_CLEAR_STA_HDR = CONTRACTDOWNPAYMENTSTATUS
MANEK = CONTRACTMANUALCOMPLETION
KOKRS = CONTROLLINGAREA
CMWAE = CONTROLLINGAREACURRENCY
OBJNR = CONTROLLINGOBJECT
IHREZ = CORRESPNCEXTERNALREFERENCE
KOSTL = COSTCENTER
GSKST = COSTCENTERBUSINESSAREA
ERNAM = CREATEDBYUSER
ERDAT = CREATIONDATE
ERZET = CREATIONTIME
CMFRE = CREDITBLOCKRELEASEDATE
KKBER = CREDITCONTROLAREA
KNKLI = CUSTOMERCREDITACCOUNT
BSTDK = CUSTOMERPURCHASEORDERDATE
BSTZD = CUSTOMERPURCHASEORDERSUPLMNT
BSARK = CUSTOMERPURCHASEORDERTYPE
KNUMA = CUSTOMERREBATEAGREEMENT
TAXK1 = CUSTOMERTAXCLASSIFICATION1
TAXK2 = CUSTOMERTAXCLASSIFICATION2
TAXK3 = CUSTOMERTAXCLASSIFICATION3
TAXK4 = CUSTOMERTAXCLASSIFICATION4
TAXK5 = CUSTOMERTAXCLASSIFICATION5
TAXK6 = CUSTOMERTAXCLASSIFICATION6
TAXK7 = CUSTOMERTAXCLASSIFICATION7
TAXK8 = CUSTOMERTAXCLASSIFICATION8
TAXK9 = CUSTOMERTAXCLASSIFICATION9
LIFSK = DELIVERYBLOCKREASON
DELIVERY_DATE_TYPE_RULE = DELIVERYDATETYPERULE
ABDIS = DELIVSCHEDTYPEMRPRLVNCECODE
VTWEG = DISTRIBUTIONCHANNEL
KURST = EXCHANGERATETYPE
CMPSJ = EXPRTINSURCREDITCHECKSTATUS
EXT_REV_TMSTMP = EXTERNALDOCLASTCHANGEDATETIME
EXT_REF_DOC_ID = EXTERNALDOCUMENTID
FSH_CANDATE = FASHIONCANCELDATE
CMPSI = FINDOCCREDITCHECKSTATUS
UVALL = HDRGENERALINCOMPLETIONSTATUS
AWAHR = HDRORDERPROBABILITYINPERCENT
UVFAK = HEADERBILLGINCOMPLETIONSTATUS
FAKSK = HEADERBILLINGBLOCKREASON
UVVLK = HEADERDELIVINCOMPLETIONSTATUS
XEGDR = ISEUTRIANGULARDEAL
AEDAT = LASTCHANGEDATE
UPD_TMSTMP = LASTCHANGEDATETIME
LAST_CHANGED_BY_USER = LASTCHANGEDBYUSER
MAHDT = LASTCUSTOMERCONTACTDATE
MANDT = MANDT
VBELN_GRP = MASTERSALESCONTRACT
ABRVW = MATLUSAGEINDICATOR
CMPSC = MAXDOCVALUECREDITCHECKSTATUS
CMNUP = NEXTCREDITCHECKDATE
CMNGV = NEXTSHIPPINGDATE
BOB_STATUS = OMNICHNLSALESPROMOTIONSTATUS
AUFNR = ORDERID
SPART = ORGANIZATIONDIVISION
FSSTK = OVERALLBILLINGBLOCKSTATUS
TOTAL_PCSTA = OVERALLCHMLCMPLNCSTATUS
TOTAL_DGSTA = OVERALLDANGEROUSGOODSSTATUS
BESTK = OVERALLDELIVCONFSTATUS
LSSTK = OVERALLDELIVERYBLOCKSTATUS
LFSTK = OVERALLDELIVERYSTATUS
FKSAK = OVERALLORDRELTDBILLGSTATUS
UVPRS = OVERALLPRICINGINCOMPLETIONSTS
COSTA = OVERALLPURCHASECONFSTATUS
TOTAL_SDSSTA = OVERALLSAFETYDATASHEETSTATUS
RFSTK = OVERALLSDDOCREFERENCESTATUS
ABSTK = OVERALLSDDOCUMENTREJECTIONSTS
GBSTK = OVERALLSDPROCESSSTATUS
LFGSK = OVERALLTOTALDELIVERYSTATUS
RFGSK = OVERALLTOTALSDDOCREFSTATUS
TOTAL_EMCST = OVERALLTRDCMPLNCEMBARGOSTS
UVFAS = OVRLITMBILLINGINCOMPLETIONSTS
UVVLS = OVRLITMDELIVINCOMPLETIONSTS
UVALS = OVRLITMGENERALINCOMPLETIONSTS
TOTAL_LCCST = OVRLTRDCMPLNCLEGALCTRLCHKSTS
TOTAL_SLCST = OVRLTRDCMPLNCSNCTNDLISTCHKSTS
RPLNR = PAYMENTPLAN
CMPSD = PAYMENTTERMCREDITCHECKSTATUS
CMPSK = PAYTAUTHSNCREDITCHECKSTS
VGBEL = REFERENCESDDOCUMENT
VGTYP = REFERENCESDDOCUMENTCATEGORY
AMTBL = RELEASEDCREDITAMOUNT
VDATU = REQUESTEDDELIVERYDATE
FSH_KVGR10 = RETAILADDITIONALCUSTOMERGRP10
FSH_KVGR6 = RETAILADDITIONALCUSTOMERGRP6
FSH_KVGR7 = RETAILADDITIONALCUSTOMERGRP7
FSH_KVGR8 = RETAILADDITIONALCUSTOMERGRP8
FSH_KVGR9 = RETAILADDITIONALCUSTOMERGRP9
MSR_ID = RETSMGMTPROCESS
APM_APPROVAL_REASON = SALESDOCAPPROVALREASON
APM_APPROVAL_STATUS = SALESDOCAPPROVALSTATUS
VBELN = SALESDOCUMENT
KNUMV = SALESDOCUMENTCONDITION
AUDAT = SALESDOCUMENTDATE
VBKLT = SALESDOCUMENTPROCESSINGTYPE
AUART = SALESDOCUMENTTYPE
VKGRP = SALESGROUP
KTEXT = SALESITEMPROPOSALDESCRIPTION
VKBUR = SALESOFFICE
VKORG = SALESORGANIZATION
ABDIS = SCHEDULINGAGREEMENTPROFILECODE
VBTYP = SDDOCUMENTCATEGORY
SUBMI = SDDOCUMENTCOLLECTIVENUMBER
AUGRU = SDDOCUMENTREASON
KALSM = SDPRICINGPROCEDURE
EXT_BUS_SYST_ID = SENDERBUSINESSSYSTEMNAME
VSBED = SHIPPINGCONDITION
KUNNR = SOLDTOPARTY
STWAE = STATISTICSCURRENCY
LANDTX = TAXDEPARTURECOUNTRY
SPSTG = TOTALBLOCKSTATUS
CMGST = TOTALCREDITCHECKSTATUS
NETWR = TOTALNETAMOUNT
WAERK = TRANSACTIONCURRENCY
STCEG_L = VATREGISTRATIONCOUNTRY
