VBKD = I_SALESDOCUMENTITEM
KVGR1_ANA = ADDITIONALCUSTOMERGROUP1
KVGR2_ANA = ADDITIONALCUSTOMERGROUP2
KVGR3_ANA = ADDITIONALCUSTOMERGROUP3
KVGR4_ANA = ADDITIONALCUSTOMERGROUP4
KVGR5_ANA = ADDITIONALCUSTOMERGROUP5
MVGR1 = ADDITIONALMATERIALGROUP1
MVGR2 = ADDITIONALMATERIALGROUP2
MVGR3 = ADDITIONALMATERIALGROUP3
MVGR4 = ADDITIONALMATERIALGROUP4
MVGR5 = ADDITIONALMATERIALGROUP5
GRPOS = ALTERNATIVETOITEM
ATP_ABC_SUBSTITUTION_STATUS = ALTVBSDCONFSUBSTITUTIONSTATUS
ARUN_GROUP_PRIO = ARUNDEMANDGROUPPRIORITY
ASSIGNMENT_PRIORITY = ARUNPRIORITYVALUE
MEINS = BASEUNIT
CHARG = BATCH
XCHAR = BATCHMANAGEMENTISSALESINTERNAL
FSSTA = BILLINGBLOCKSTATUS
FKDAT_ANA = BILLINGDOCUMENTDATE
FPLNR_ANA = BILLINGPLAN
STLNR = BILLOFMATERIAL
KUNRE_ANA = BILLTOPARTY
STDAT = BOMEXPLOSIONDATE
GSBER = BUSINESSAREA
SOLUTION_ORDER_ID = BUSINESSSOLUTIONORDER
SOLUTION_ORDER_ITM_ID = BUSINESSSOLUTIONORDERITEM
CAPPED_NET_AMOUNT = CAPPEDNETAMOUNT
CAPPED_NET_AMOUNT_ALERT_THLD = CAPPEDNETAMTALERTTHLDINPCT
PCSTA = CHMLCMPLNCSTATUS
CMTD_DELIV_CREADATE = COMMITTEDDELIVCREATIONDATE
CMTD_DELIV_DATE = COMMITTEDDELIVERYDATE
CMTD_DELIV_QTY_SU = COMMITTEDDELIVQTYINORDQTYUNIT
ERLRE = COMPLETIONRULE
KLMENG = CONFDDELIVERYQTYINBASEUNIT
KBMENG = CONFDDELIVQTYINORDERQTYUNIT
KZVBR = CONSUMPTIONPOSTING
DP_CLEAR_STA_ITM = CONTRACTITEMDOWNPAYMENTSTATUS
OBJNR = CONTROLLINGOBJECT
WAVWR = COSTAMOUNT
ERNAM = CREATEDBYUSER
ERDAT = CREATIONDATE
ERZET = CREATIONTIME
KDGRP_ANA = CUSTOMERGROUP
DGSTA = DANGEROUSGOODSSTATUS
LSSTA = DELIVERYBLOCKSTATUS
BESTA = DELIVERYCONFIRMATIONSTATUS
FIXMG = DELIVERYDATEQUANTITYISFIXED
DELIVERY_DATE_TYPE_RULE = DELIVERYDATETYPERULE
GRKOR = DELIVERYGROUP
LPRIO = DELIVERYPRIORITY
LFSTA = DELIVERYSTATUS
VTWEG_ANA = DISTRIBUTIONCHANNEL
SPART = DIVISION
EXT_REF_ITEM_ID = EXTERNALITEMID
FSH_CANDATE = FASHIONCANCELDATE
UEPOS = HIGHERLEVELITEM
UEPVW = HIGHERLEVELITEMUSAGE
EAN11 = INTERNATIONALARTICLENUMBER
SOBKZ = INVENTORYSPECIALSTOCKTYPE
KZBWS = INVENTORYSPECIALSTOCKVALNTYPE
SHKZG = ISRETURNSITEM
FAKSP = ITEMBILLINGBLOCKREASON
UVFAK = ITEMBILLINGINCOMPLETIONSTATUS
UVVLK = ITEMDELIVERYINCOMPLETIONSTATUS
UVALL = ITEMGENERALINCOMPLETIONSTATUS
BRGEW = ITEMGROSSWEIGHT
FKREL = ITEMISBILLINGRELEVANT
LFREL = ITEMISDELIVERYRELEVANT
NTGEW = ITEMNETWEIGHT
AWAHR = ITEMORDERPROBABILITYINPERCENT
VOLUM = ITEMVOLUME
VOLEH = ITEMVOLUMEUNIT
GEWEI = ITEMWEIGHTUNIT
AEDAT = LASTCHANGEDATE
UPMAT = MAINITEMPRICINGREFPRODUCT
MANDT = MANDT
MATNR = MATERIAL
KDMAT = MATERIALBYCUSTOMER
PROSA = MATERIALDETERMINATIONTYPE
MATKL = MATERIALGROUP
KONDM = MATERIALPRICINGGROUP
SUGRD = MATERIALSUBSTITUTIONREASON
KTGRM = MATLACCOUNTASSIGNMENTGROUP
ANTLF = MAXNMBROFPARTIALDELIVERY
SUBSTN_DENOMINATOR = MDSUBSTNCONVERSIONDENOMINATOR
SUBSTN_NUMERATOR = MDSUBSTNCONVERSIONNUMERATOR
LFMNG = MINDELIVERYQTYINBASEUNIT
BERID = MRPAREA
NETWR = NETAMOUNT
NETPR = NETPRICEAMOUNT
KPEIN = NETPRICEQUANTITY
KMEIN = NETPRICEQUANTITYUNIT
BOB_PROMOTION_ID = OMNICHANNELSALESPROMOTION
BOB_FG_ID = OMNICHANNELSALESPROMOTIONRULE
KZFME = OPENDELIVERYLEADINGUNITCODE
AUFNR = ORDERID
KWMENG = ORDERQUANTITY
VRKME = ORDERQUANTITYUNIT
FKSAA = ORDERRELATEDBILLINGSTATUS
UMVKN = ORDERTOBASEQUANTITYDNMNTR
UMVKZ = ORDERTOBASEQUANTITYNMRTR
SPART_ANA = ORGANIZATIONDIVISION
MATWA = ORIGINALLYREQUESTEDMATERIAL
ORIGINAL_PLANT = ORIGINALPLANT
VBELV = ORIGINSDDOCUMENT
POSNV = ORIGINSDDOCUMENTITEM
ZWERT = OUTLINEAGREEMENTTARGETAMOUNT
UEBTO = OVERDELIVTOLRTDLMTRATIOINPCT
TOTAL_LCCST = OVRLTRDCMPLNCLEGALCTRLCHKSTS
KZTLF = PARTIALDELIVERYISALLOWED
KUNRG_ANA = PAYERPARTY
VPMAT = PLANNINGMATERIAL
VPWRK = PLANNINGPLANT
WERKS = PLANT
PLAVO = PLNGDELIVSCHEDINSTRN
UVPRS = PRICINGINCOMPLETIONSTATUS
PMATN = PRICINGREFERENCEMATERIAL
MTVFP = PRODAVAILABILITYCHECKGROUP
UMREF = PRODPLNTPLNGMATLCONVERSIONFCTR
MATNR = PRODUCT
PRBME = PRODUCTBASEUNIT
WRF_CHARSTC1 = PRODUCTCHARACTERISTIC1
WRF_CHARSTC2 = PRODUCTCHARACTERISTIC2
WRF_CHARSTC3 = PRODUCTCHARACTERISTIC3
FSH_COLLECTION = PRODUCTCOLLECTION
CUOBJ = PRODUCTCONFIGURATION
MATKL = PRODUCTGROUP
PRODH = PRODUCTHIERARCHYNODE
FSH_SEASON = PRODUCTSEASON
FSH_SEASON_YEAR = PRODUCTSEASONYEAR
TAXM1 = PRODUCTTAXCLASSIFICATION1
TAXM2 = PRODUCTTAXCLASSIFICATION2
TAXM3 = PRODUCTTAXCLASSIFICATION3
TAXM4 = PRODUCTTAXCLASSIFICATION4
TAXM5 = PRODUCTTAXCLASSIFICATION5
TAXM6 = PRODUCTTAXCLASSIFICATION6
TAXM7 = PRODUCTTAXCLASSIFICATION7
TAXM8 = PRODUCTTAXCLASSIFICATION8
TAXM9 = PRODUCTTAXCLASSIFICATION9
FSH_THEME = PRODUCTTHEME
PAOBJNR = PROFITABILITYSEGMENT_2
PRCTR = PROFITCENTER
COSTA = PURCHASECONFIRMATIONSTATUS
BSTKD_ANA = PURCHASEORDERBYCUSTOMER
FMENG = QUANTITYISFIXED
VGBEL = REFERENCESDDOCUMENT
VGTYP = REFERENCESDDOCUMENTCATEGORY
VGPOS = REFERENCESDDOCUMENTITEM
VDATU_ANA = REQUESTEDDELIVERYDATE
REQQTY_BU = REQUESTEDQUANTITYINBASEUNIT
SGT_RCAT = REQUIREMENTSEGMENT
PERZM_ANA = RESPONSIBLEEMPLOYEE
PERZM_ANA = RESPONSIBLEEMPLOYEEWORKAGRMT
ABGRS = RESULTANALYSISINTERNALID
MSR_APPROV_BLOCK = RETSMGMTPROCESSINGBLOCK
MSR_RET_REASON = RETURNREASON
MSR_REFUND_CODE = RETURNSREFUNDEXTENT
ROUTE = ROUTE
SDSSTA = SAFETYDATASHEETSTATUS
KNUMA_AG = SALESDEAL
BZIRK_ANA = SALESDISTRICT
VBELN = SALESDOCUMENT
KNUMV_ANA = SALESDOCUMENTCONDITION
AUDAT_ANA = SALESDOCUMENTDATE
POSNR = SALESDOCUMENTITEM
PSTYV = SALESDOCUMENTITEMCATEGORY
PROCESS_CODE = SALESDOCUMENTITEMPROCGCODE
ARKTX = SALESDOCUMENTITEMTEXT
POSAR = SALESDOCUMENTITEMTYPE
HANDLE = SALESDOCUMENTITEMUUID
ABGRU = SALESDOCUMENTRJCNREASON
AUART_ANA = SALESDOCUMENTTYPE
PERVE_ANA = SALESEMPLOYEE
PERVE_ANA = SALESEMPLOYEEWORKAGREEMENT
VKGRP_ANA = SALESGROUP
VKBUR_ANA = SALESOFFICE
VKORG_ANA = SALESORGANIZATION
KNUMA_PI = SALESPROMOTION
RFSTA = SDDOCREFERENCESTATUS
VBTYP_ANA = SDDOCUMENTCATEGORY
AUGRU_ANA = SDDOCUMENTREASON
ABSTA = SDDOCUMENTREJECTIONSTATUS
GBSTA = SDPROCESSSTATUS
RFM_SCC_INDICATOR = SEASONCOMPLETENESSSTATUS
SERVICE_DOC_ID = SERVICEDOCUMENT
SERVICE_DOC_ITEM_ID = SERVICEDOCUMENTITEM
SERVICE_DOC_TYPE = SERVICEDOCUMENTTYPE
VSBED_ANA = SHIPPINGCONDITION
RFM_PSST_GROUP = SHIPPINGGROUPNUMBER
RFM_PSST_RULE = SHIPPINGGROUPRULE
VSTEL = SHIPPINGPOINT
VSART_ANA = SHIPPINGTYPE
KUNWE_ANA = SHIPTOPARTY
KUNNR_ANA = SOLDTOPARTY
KOWRR = STATISTICALVALUECONTROL
LGORT = STORAGELOCATION
KZWI1 = SUBTOTAL1AMOUNT
KZWI2 = SUBTOTAL2AMOUNT
KZWI3 = SUBTOTAL3AMOUNT
KZWI4 = SUBTOTAL4AMOUNT
KZWI5 = SUBTOTAL5AMOUNT
KZWI6 = SUBTOTAL6AMOUNT
LSMENG = TARGETDELIVQTYINORDERQTYUNIT
ZMENG = TARGETQUANTITY
ZIEME = TARGETQUANTITYUNIT
UMZIN = TARGETTOBASEQUANTITYDNMNTR
UMZIZ = TARGETTOBASEQUANTITYNMRTR
MWSBP = TAXAMOUNT
LFGSA = TOTALDELIVERYSTATUS
RFGSA = TOTALSDDOCREFERENCESTATUS
IFRS15_TOTAL_SSP = TOTALSTANDALONESELLINGPRICE
WAERK = TRANSACTIONCURRENCY
TRANSIT_PLANT = TRANSITPLANT
EMCST = TRDCMPLNCEMBARGOSTS
SLCST = TRDCMPLNCSNCTNDLISTCHKSTS
UNTTO = UNDERDELIVTOLRTDLMTRATIOINPCT
POSEX = UNDERLYINGPURCHASEORDERITEM
UEBTK = UNLIMITEDOVERDELIVERYISALLOWED
VCM_CHAIN_CATEGORY = VALUECHAINCATEGORY
WKTNR = VALUECONTRACT
WKTPS = VALUECONTRACTITEM
PS_PSP_PNR = WBSELEMENT
PS_PSP_PNR = WBSELEMENTINTERNALID
