VBEP = I_SALESDOCUMENTSCHEDULELINE
MEINS = BASEUNIT
BMENG = CONFDORDERQTYBYMATLAVAILCHECK
REQ_DLVDATE = CONFDSCHEDLINEREQDDELIVDATE
CRQQTY_BU = CONFIRMEDRQMTQTYINBASEUNIT
CMENG = CORRECTEDQTYINORDERQTYUNIT
AESKD = CUSTENGINEERINGCHGSTATUS
LIFSP = DELIVBLOCKREASONFORSCHEDLINE
PRGRS = DELIVDATECATEGORY
DLVQTY_SU = DELIVEREDQTYINORDERQTYUNIT
DLVQTY_BU = DELIVEREDQUANTITYINBASEUNIT
CREA_DLVDATE = DELIVERYCREATIONDATE
EDATU = DELIVERYDATE
WADAT = GOODSISSUEDATE
WAUHR = GOODSISSUETIME
BWART = GOODSMOVEMENTTYPE
LFREL = ITEMISDELIVERYRELEVANT
LDDAT = LOADINGDATE
LDUHR = LOADINGTIME
MANDT = MANDT
LMENG = MRPREQUIREDQUANTITYINBASEUNIT
OCDQTY_BU = OPENCONFDDELIVQTYINBASEUNIT
OCDQTY_SU = OPENCONFDDELIVQTYINORDQTYUNIT
ODN_AMOUNT = OPENDELIVERYNETAMOUNT
ORDQTY_BU = OPENREQDDELIVQTYINBASEUNIT
ORDQTY_SU = OPENREQDDELIVQTYINORDQTYUNIT
AUFNR = ORDERID
VRKME = ORDERQUANTITYUNIT
FSH_OS_ID = ORDERSCHEDULINGGROUP
UMVKN = ORDERTOBASEQUANTITYDNMNTR
UMVKZ = ORDERTOBASEQUANTITYNMRTR
PLNUM = PLANNEDORDER
BDART = PRODAVAILABILITYCHECKRQMTTYPE
PLART = PRODAVAILYCHECKPLANNINGTYPE
MBDAT = PRODUCTAVAILABILITYDATE
MBUHR = PRODUCTAVAILABILITYTIME
BDDAT = PRODUCTAVAILCHECKRQMTDATE
BANFN = PURCHASEREQUISITION
BNFPO = PURCHASEREQUISITIONITEM
BSTYP = PURCHASINGDOCUMENTCATEGORY
BSART = PURCHASINGORDERTYPE
RRQQTY_BU = REQUESTEDRQMTQTYINBASEUNIT
BEDAR = REQUIREMENTSCLASS
AULWE = ROUTESCHEDULE
VBELN = SALESDOCUMENT
POSNR = SALESDOCUMENTITEM
ETENR = SCHEDULELINE
ABRUF = SCHEDULELINEBYFORECASTDELIVERY
ETTYP = SCHEDULELINECATEGORY
WEPOS = SCHEDULELINECONFIRMATIONSTATUS
WMENG = SCHEDULELINEORDERQUANTITY
ABART = SCHEDULINGAGREEMENTRELEASETYPE
LCCST = TRADECMPLNCLEGALCTRLCHKSTS
WAERK = TRANSACTIONCURRENCY
TDDAT = TRANSPORTATIONPLANNINGDATE
TDUHR = TRANSPORTATIONPLANNINGTIME
