VBFA = I_SDDOCUMENTMULTILEVELPROCFLOW
MEINS = BASEUNIT
FPLNR = BILLINGPLAN
FPLTR = BILLINGPLANITEM
ERDAT = CREATIONDATE
ERZET = CREATIONTIME
RUUID = DOCRELATIONSHIPUUID
AEDAT = LASTCHANGEDATE
MANDT = MANDT
MJAHR = MATERIALDOCUMENTYEAR
RFWRT = NETAMOUNT
VRKME = ORDERQUANTITYUNIT
VBELV = PRECEDINGDOCUMENT
VBTYP_V = PRECEDINGDOCUMENTCATEGORY
POSNV = PRECEDINGDOCUMENTITEM
STUFE = PROCESSFLOWLEVEL
RFMNG = QUANTITYINBASEUNIT
RFMNG_FLT = REFQUANTITYINBASEUNITASFLOAT
RFMNG_FLO = REFQUANTITYINORDQTYUNITASFLOAT
PLMIN = SDFULFILLMENTCALCULATIONRULE
WAERS = STATISTICSCURRENCY
VBELN = SUBSEQUENTDOCUMENT
VBTYP_N = SUBSEQUENTDOCUMENTCATEGORY
POSNN = SUBSEQUENTDOCUMENTITEM
TAQUI = TRANSFERORDERINWRHSMGMTISCONFD
LGNUM = WAREHOUSENUMBER
