VBFS = I_COLLECTIVEPROCESSINGERRORLOG
SAMMG = COLLECTIVEPROCESSING
ZAEHL = COLLECTIVEPROCESSINGMSGCOUNTER
SMART = COLLECTIVEPROCESSINGTYPE
MANDT = MANDT
ETENR = SCHEDULELINE
VBELN = SDDOCUMENT
POSNR = SDDOCUMENTITEM
MSGID = SYSTEMMESSAGEIDENTIFICATION
MSGNO = SYSTEMMESSAGENUMBER
MSGTY = SYSTEMMESSAGETYPE
MSGV1 = SYSTEMMESSAGEVARIABLE1
MSGV2 = SYSTEMMESSAGEVARIABLE2
MSGV3 = SYSTEMMESSAGEVARIABLE3
MSGV4 = SYSTEMMESSAGEVARIABLE4
