VBAK = I_SALESDOCUMENT
KURRF = ACCOUNTINGEXCHANGERATE
VALTG = ADDITIONALVALUEDAYS
FKDAT = BILLINGDOCUMENTDATE
FPLNR = BILLINGPLAN
VKONT = CONTRACTACCOUNT
KTGRD = CUSTOMERACCOUNTASSIGNMENTGROUP
KDGRP = CUSTOMERGROUP
ZTERM = CUSTOMERPAYMENTTERMS
KONDA = CUSTOMERPRICEGROUP
KURSK_DAT = EXCHANGERATEDATE
POPER = FISCALPERIOD
GJAHR = FISCALYEAR
VALDT = FIXEDVALUEDATE
INCO1 = INCOTERMSCLASSIFICATION
INCO2_L = INCOTERMSLOCATION1
INCO3_L = INCOTERMSLOCATION2
INCO2 = INCOTERMSTRANSFERLOCATION
INCOV = INCOTERMSVERSION
KZAZU = ORDERCOMBINATIONISALLOWED
ZLSCH = PAYMENTMETHOD
KURSK = PRICEDETNEXCHANGERATE
PLTYP = PRICELISTTYPE
PRSDT = PRICINGDATE
WMINR = PRODUCTCATALOG
BSTKD = PURCHASEORDERBYCUSTOMER
BSTKD_E = PURCHASEORDERBYSHIPTOPARTY
EMPST = RECEIVINGPOINT
WAKTION = RETAILPROMOTION
BZIRK = SALESDISTRICT
FBUDA = SERVICESRENDEREDDATE
VSART = SHIPPINGTYPE
PODKZ = SLSDOCISRLVTFORPROOFOFDELIV
