VBRK = I_BILLINGDOCUMENTBASIC
BELNR = ACCOUNTINGDOCUMENT
KURRF = ACCOUNTINGEXCHANGERATE
CPKUR = ACCOUNTINGEXCHANGERATEISSET
BUCHK = ACCOUNTINGPOSTINGSTATUS
RFBSK = ACCOUNTINGTRANSFERSTATUS
VALTG = ADDITIONALVALUEDAYS
ZUONR = ASSIGNMENTREFERENCE
BDR_REF_LOGSYS = BILLGDOCREQREFLGCLSYST
BDR_REF_VBTYP = BILLGDOCREQREFSDDOCCATEGORY
APM_APPROVAL_REASON = BILLGPROCDOCAPPROVALREASON
APM_APPROVAL_STATUS = BILLGPROCDOCAPPROVALSTATUS
ZUKRI = BILLINGDOCCOMBINATIONCRITERIA
BDR_REF = BILLINGDOCREQUESTREFERENCE
VBELN = BILLINGDOCUMENT
FKTYP = BILLINGDOCUMENTCATEGORY
FKDAT = BILLINGDOCUMENTDATE
FKSTO = BILLINGDOCUMENTISCANCELLED
DRAFT = BILLINGDOCUMENTISTEMPORARY
FKART = BILLINGDOCUMENTTYPE
VF_TODO = BILLINGISSUETYPE
SFAKN = CANCELLEDBILLINGDOCUMENT
CITYC = CITYCODE
BUKRS = COMPANYCODE
VKONT = CONTRACTACCOUNT
LAND1 = COUNTRY
COUNC = COUNTY
ERNAM = CREATEDBYUSER
ERDAT = CREATIONDATE
ERZET = CREATIONTIME
KKBER = CREDITCONTROLAREA
KTGRD = CUSTOMERACCOUNTASSIGNMENTGROUP
KDGRP = CUSTOMERGROUP
ZTERM = CUSTOMERPAYMENTTERMS
KONDA = CUSTOMERPRICEGROUP
KNUMA = CUSTOMERREBATEAGREEMENT
TAXK1 = CUSTOMERTAXCLASSIFICATION1
TAXK2 = CUSTOMERTAXCLASSIFICATION2
TAXK3 = CUSTOMERTAXCLASSIFICATION3
TAXK4 = CUSTOMERTAXCLASSIFICATION4
TAXK5 = CUSTOMERTAXCLASSIFICATION5
TAXK6 = CUSTOMERTAXCLASSIFICATION6
TAXK7 = CUSTOMERTAXCLASSIFICATION7
TAXK8 = CUSTOMERTAXCLASSIFICATION8
TAXK9 = CUSTOMERTAXCLASSIFICATION9
VTWEG = DISTRIBUTIONCHANNEL
SPART = DIVISION
XBLNR = DOCUMENTREFERENCEID
MABER = DUNNINGAREA
MANSP = DUNNINGBLOCKINGREASON
MSCHL = DUNNINGKEY
KURRF_DAT = EXCHANGERATEDATE
KURST = EXCHANGERATETYPE
POPER = FISCALPERIOD
GJAHR = FISCALYEAR
VALDT = FIXEDVALUEDATE
HITYP_PR = HIERARCHYTYPEPRICING
INCO1 = INCOTERMSCLASSIFICATION
INCO2_L = INCOTERMSLOCATION1
INCO3_L = INCOTERMSLOCATION2
INCO2 = INCOTERMSTRANSFERLOCATION
INCOV = INCOTERMSVERSION
LCNUM = INTERNALFINANCIALDOCUMENT
CLRST = INVOICECLEARINGSTATUS
FKDAT_RL = INVOICELISTBILLINGDATE
RELIK = INVOICELISTSTATUS
FKART_RL = INVOICELISTTYPE
XEGDR = ISEUTRIANGULARDEAL
INTRA_EXCL = ISINTRASTATREPORTINGEXCLUDED
INTRA_REL = ISINTRASTATREPORTINGRELEVANT
ACCRREL = ISRELEVANTFORACCRUAL
AEDAT = LASTCHANGEDATE
CHANGED_ON = LASTCHANGEDATETIME
LOGSYS = LOGICALSYSTEM
MANDT = MANDT
MRNKZ = MANUALINVOICEMAINTISRELEVANT
NUMPG = NMBROFPAGES
BDR_STATUS = OVERALLBILLINGDOCREQSTATUS
VF_STATUS = OVERALLBILLINGSTATUS
FKSAK = OVERALLDOCUMENTBILLINGSTATUS
UVPRS = OVERALLPRICINGINCOMPLETIONSTS
GBSTK = OVERALLSDPROCESSSTATUS
UVALS = OVRLITMGENERALINCOMPLETIONSTS
VBUND = PARTNERCOMPANY
KUNRG = PAYERPARTY
ZLSCH = PAYMENTMETHOD
KIDNO = PAYMENTREFERENCE
ICO_LIFNR = PLANTSUPPLIER
PBD_STATUS = PRELIMBILLINGDOCUMENTSTATUS
PLTYP = PRICELISTTYPE
KNUMV = PRICINGDOCUMENT
FKARA = PROPOSEDBILLINGDOCUMENTTYPE
BSTNK_VF = PURCHASEORDERBYCUSTOMER
REGIO = REGION
STGRD = REVERSALREASON
BZIRK = SALESDISTRICT
VKORG = SALESORGANIZATION
VBTYP = SDDOCUMENTCATEGORY
KALSM = SDPRICINGPROCEDURE
MNDID = SEPAMANDATE
VSBED = SHIPPINGCONDITION
KUNAG = SOLDTOPARTY
STWAE = STATISTICSCURRENCY
LANDTX = TAXDEPARTURECOUNTRY
NETWR = TOTALNETAMOUNT
MWSBK = TOTALTAXAMOUNT
WAERK = TRANSACTIONCURRENCY
STCEG = VATREGISTRATION
STCEG_L = VATREGISTRATIONCOUNTRY
STCEG_H = VATREGISTRATIONORIGIN
