VBRP = I_BILLINGDOCUMENTITEMBASIC
KVGR1 = ADDITIONALCUSTOMERGROUP1
KVGR2 = ADDITIONALCUSTOMERGROUP2
KVGR3 = ADDITIONALCUSTOMERGROUP3
KVGR4 = ADDITIONALCUSTOMERGROUP4
KVGR5 = ADDITIONALCUSTOMERGROUP5
MVGR1 = ADDITIONALMATERIALGROUP1
MVGR2 = ADDITIONALMATERIALGROUP2
MVGR3 = ADDITIONALMATERIALGROUP3
MVGR4 = ADDITIONALMATERIALGROUP4
MVGR5 = ADDITIONALMATERIALGROUP5
MEINS = BASEUNIT
CHARG = BATCH
VGPOS_EX = BILLINGDOCEXTREFERENCEDOCITEM
VBELN = BILLINGDOCUMENT
FKTYP_ANA = BILLINGDOCUMENTCATEGORY
FKDAT_ANA = BILLINGDOCUMENTDATE
DRAFT = BILLINGDOCUMENTISTEMPORARY
POSNR = BILLINGDOCUMENTITEM
POSPA = BILLINGDOCUMENTITEMINPARTSGMT
ARKTX = BILLINGDOCUMENTITEMTEXT
FKART_ANA = BILLINGDOCUMENTTYPE
PEROP_END = BILLINGPERFORMANCEPERIODENDDTE
PEROP_BEG = BILLINGPERFORMANCEPERIODSTRDTE
FPLNR = BILLINGPLAN
FPLTR = BILLINGPLANITEM
FAREG = BILLINGPLANRULE
FKIMG = BILLINGQUANTITY
FKLMG = BILLINGQUANTITYINBASEUNIT
VRKME = BILLINGQUANTITYUNIT
UMVKN = BILLINGTOBASEQUANTITYDNMNTR
UMVKZ = BILLINGTOBASEQUANTITYNMRTR
KUNRE_ANA = BILLTOPARTY
LLAND_AUFT = BILLTOPARTYCOUNTRY
REGIO_AUFT = BILLTOPARTYREGION
SERNR = BOMEXPLOSION
GSBER = BUSINESSAREA
SOLUTION_ORDER_ID = BUSINESSSOLUTIONORDER
SOLUTION_ORDER_ITEM_ID = BUSINESSSOLUTIONORDERITEM
SKTOF = CASHDISCOUNTISDEDUCTIBLE
CITYC_ANA = CITYCODE
ITM_COMCO = COMMODITYCODE
BUKRS_ANA = COMPANYCODE
KOKRS = CONTROLLINGAREA
WAVWR = COSTAMOUNT
KOSTL = COSTCENTER
LAND1_ANA = COUNTRY
SPE_HERKL = COUNTRYOFORIGIN
COUNC_ANA = COUNTY
ERNAM = CREATEDBYUSER
ERDAT = CREATIONDATE
ERZET = CREATIONTIME
CMPRE = CREDITRELATEDPRICE
KDKG1 = CUSTOMERCONDITIONGROUP1
KDKG2 = CUSTOMERCONDITIONGROUP2
KDKG3 = CUSTOMERCONDITIONGROUP3
KDKG4 = CUSTOMERCONDITIONGROUP4
KDKG5 = CUSTOMERCONDITIONGROUP5
KDGRP_ANA = CUSTOMERGROUP
KONDA_ANA = CUSTOMERPRICEGROUP
KNUMA_ANA = CUSTOMERREBATEAGREEMENT
ALAND = DEPARTURECOUNTRY
VTWEG_ANA = DISTRIBUTIONCHANNEL
SPART = DIVISION
FKSAA = DOCUMENTBILLINGSTATUS
SKFBP = ELIGIBLEAMOUNTFORCASHDISCOUNT
VGBEL_EX = EXTERNALREFERENCEDOCUMENT
VGPOS_EX = EXTERNALREFERENCEDOCUMENTITEM
BRTWR = GROSSAMOUNT
UEPOS = HIGHERLEVELITEM
UEPVW = HIGHERLEVELITEMUSAGE
UECHA = HIGHERLVLITMOFBATSPLTITM
EAN11 = INTERNATIONALARTICLENUMBER
BRGEW = ITEMGROSSWEIGHT
CMPNT = ITEMISRELEVANTFORCREDIT
NTGEW = ITEMNETWEIGHT
VOLUM = ITEMVOLUME
VOLEH = ITEMVOLUMEUNIT
GEWEI = ITEMWEIGHTUNIT
UKONM = MAINITEMMATERIALPRICINGGROUP
UPMAT = MAINITEMPRICINGREFMATERIAL
MANDT = MANDT
MPROK = MANUALPRICECHANGETYPE
MATNR = MATERIAL
PROVG = MATERIALCOMMISSIONGROUP
PROSA = MATERIALDETERMINATIONTYPE
MATKL = MATERIALGROUP
WGRU1 = MATERIALGROUPHIERARCHY1
WGRU2 = MATERIALGROUPHIERARCHY2
KONDM = MATERIALPRICINGGROUP
KTGRM = MATLACCOUNTASSIGNMENTGROUP
LMENG = MRPREQUIREDQUANTITYINBASEUNIT
NETWR = NETAMOUNT
AUFNR = ORDERID
SPARA = ORGANIZATIONDIVISION
MATWA = ORIGINALLYREQUESTEDMATERIAL
VBELV = ORIGINSDDOCUMENT
POSNV = ORIGINSDDOCUMENTITEM
VF_STATUS_ANA = OVERALLBILLINGSTATUS
GBSTK_ANA = OVERALLSDPROCESSSTATUS
KUNRG_ANA = PAYERPARTY
WERKS = PLANT
WKCTY = PLANTCITY
WKCOU = PLANTCOUNTY
WKREG = PLANTREGION
PBD_ID = PRELIMBILLINGDOCUMENT
PBD_ITEM_ID = PRELIMBILLINGDOCUMENTITEM
KURSK = PRICEDETNEXCHANGERATE
KURSK_DAT = PRICEDETNEXCHANGERATEDATE
PRSDT = PRICINGDATE
PMATN = PRICINGREFERENCEMATERIAL
PRSFD = PRICINGRELEVANCE
SMENG = PRICINGSCALEQUANTITYINBASEUNIT
MATNR = PRODUCT
CUOBJ = PRODUCTCONFIGURATION
MATKL = PRODUCTGROUP
PRODH = PRODUCTHIERARCHYNODE
TAXM1 = PRODUCTTAXCLASSIFICATION1
TAXM2 = PRODUCTTAXCLASSIFICATION2
TAXM3 = PRODUCTTAXCLASSIFICATION3
TAXM4 = PRODUCTTAXCLASSIFICATION4
TAXM5 = PRODUCTTAXCLASSIFICATION5
TAXM6 = PRODUCTTAXCLASSIFICATION6
TAXM7 = PRODUCTTAXCLASSIFICATION7
TAXM8 = PRODUCTTAXCLASSIFICATION8
TAXM9 = PRODUCTTAXCLASSIFICATION9
PRCTR = PROFITCENTER
VTKEY = PROVIDERCONTRACT
VTPOS = PROVIDERCONTRACTITEM
BONBA = REBATEBASISAMOUNT
LOGSYS = REFERENCELOGICALSYSTEM
VGBEL = REFERENCESDDOCUMENT
VGTYP = REFERENCESDDOCUMENTCATEGORY
VGPOS = REFERENCESDDOCUMENTITEM
REGIO_ANA = REGION
SPE_HERKR = REGIONOFORIGIN
ATPKZ = REPLACEMENTPARTTYPE
PERZM_ANA = RESPONSIBLEEMPLOYEE
AKTNR = RETAILPROMOTION
SHKZG = RETURNITEMPROCESSINGTYPE
KNUMA_AG = SALESDEAL
BZIRK_ANA = SALESDISTRICT
AUREF = SALESDOCISCREATEDFROMREFERENCE
AUBEL = SALESDOCUMENT
AUPOS = SALESDOCUMENTITEM
PSTYV = SALESDOCUMENTITEMCATEGORY
POSAR = SALESDOCUMENTITEMTYPE
PERVE_ANA = SALESEMPLOYEE
VKGRP = SALESGROUP
VKBUR = SALESOFFICE
KDGRP_AUFT = SALESORDERCUSTOMERGROUP
KONDA_AUFT = SALESORDERCUSTOMERPRICEGROUP
VTWEG_AUFT = SALESORDERDISTRIBUTIONCHANNEL
PLTYP_AUFT = SALESORDERPRICELISTTYPE
BZIRK_AUFT = SALESORDERSALESDISTRICT
VKORG_AUFT = SALESORDERSALESORGANIZATION
VKORG_ANA = SALESORGANIZATION
KNUMA_PI = SALESPROMOTION
AUTYP = SALESSDDOCUMENTCATEGORY
VBTYP_ANA = SDDOCUMENTCATEGORY
AUGRU_AUFT = SDDOCUMENTREASON
SERVICE_DOC_ID = SERVICEDOCUMENT
SERVICE_DOC_ITEM_ID = SERVICEDOCUMENTITEM
SERVICE_DOC_TYPE = SERVICEDOCUMENTTYPE
FBUDA = SERVICESRENDEREDDATE
VSTEL = SHIPPINGPOINT
KUNWE_ANA = SHIPTOPARTY
KUNAG_ANA = SOLDTOPARTY
KOWRR = STATISTICALVALUECONTROL
STCUR = STATISTICSEXCHANGERATE
LGORT = STORAGELOCATION
KZWI1 = SUBTOTAL1AMOUNT
KZWI2 = SUBTOTAL2AMOUNT
KZWI3 = SUBTOTAL3AMOUNT
KZWI4 = SUBTOTAL4AMOUNT
KZWI5 = SUBTOTAL5AMOUNT
KZWI6 = SUBTOTAL6AMOUNT
MWSBP = TAXAMOUNT
MWSK1 = TAXCODE
TXJCD = TAXJURISDICTION
TXDAT_FROM = TAXRATEVALIDITYSTARTDATE
CATS_OVERTIME_CATEGORY = TIMESHEETOVERTIMECATEGORY
WAERK = TRANSACTIONCURRENCY
TRANSIT_PLANT = TRANSITPLANT
VCM_CHAIN_CATEGORY = VALUECHAINCATEGORY
BONUS = VOLUMEREBATEGROUP
PS_PSP_PNR = WBSELEMENT
PS_PSP_PNR = WBSELEMENTINTERNALID
J_1ARFZ = ZEROVATRSN
