VBAK = I_SALESDOCUMENT
VBELKUE = CANCLNDOCBYCONTRPARTNER
VBEDKUE = CONTRACTPARTNERCANCLNDOCDATE
VABNDAT = EQUIPMENTDELIVERYACCPTCDATE
VDEMDAT = EQUIPMENTDISMANTLINGDATE
VINSDAT = EQUIPMENTINSTALLATIONDATE
VLAUFZ = NMBROFSALESCONTRACTVALDTYPERD
VWUNDAT = REQUESTEDCANCELLATIONDATE
VKUEPAR = SALESCONTRACTCANCLNPARTY
VKUESCH = SALESCONTRACTCANCLNPROCEDURE
VKUEGRU = SALESCONTRACTCANCLNREASON
VAKTSCH = SALESCONTRACTFOLLOWUPACTION
VUNTDAT = SALESCONTRACTSIGNEDDATE
VLAUFK = SALESCONTRACTVALIDITYPERDCAT
VLAUEZ = SALESCONTRACTVALIDITYPERDUNIT
VEINDAT = SLSCONTRACTCANCLNREQRCPTDATE
VASDA = SLSCONTRACTFOLLOWUPACTIONDATE
