VEKP = I_HANDLINGUNITTP
ERNAM = CREATEDBYUSER
BTVOL = GROSSVOLUME
BRGEW = GROSSWEIGHT
EXIDV = HANDLINGUNITEXTERNALID
EXIDA = HANDLINGUNITEXTERNALIDTYPE
HOEHE = HANDLINGUNITHEIGHT
STATUS = HANDLINGUNITINTERNALSTATUS
LAENG = HANDLINGUNITLENGTH
UEVEL = HANDLINGUNITLOWERLEVELREFER
MAVOL = HANDLINGUNITMAXVOLUME
MAGEW = HANDLINGUNITMAXWEIGHT
NTVOL = HANDLINGUNITNETVOLUME
EXIDV2 = HANDLINGUNITSECONDEXTERNALID
TAVOL = HANDLINGUNITTAREVOLUME
VOLEH = HANDLINGUNITTAREVOLUMEUNIT
TARAG = HANDLINGUNITTAREWEIGHT
GEWEI = HANDLINGUNITTAREWEIGHTUNIT
BREIT = HANDLINGUNITWIDTH
NTGEW = NETWEIGHT
VHILM = PACKAGINGMATERIAL
VHART = PACKAGINGMATERIALTYPE
PACKVORSCHR = PACKINGINSTRUCTION
EXIDV = PARENTHANDLINGUNITNUMBER
WERKS = PLANT
VSTEL = SHIPPINGPOINT
HANDLE = SOURCEHANDLINGUNITUUID
LGORT = STORAGELOCATION
MEABM = UNITOFMEASUREDIMENSION
VOLEH_MAX = VOLUMEUNIT
GEWEI_MAX = WEIGHTUNIT
