VEKP = I_HANDLINGUNITHEADER
ERNAM = CREATEDBYUSER
ERDAT = CREATIONDATE
ERUHR = CREATIONTIME
VTWEG = DISTRIBUTIONCHANNEL
BTVOL = GROSSVOLUME
BRGEW = GROSSWEIGHT
MEINS = HANDLINGUNITBASEUNITOFMEASURE
INHALT = HANDLINGUNITCONTENTDESCRIPTION
VHILM_KU = HANDLINGUNITCUSTOMERPACKMAT
VBELN_GEN = HANDLINGUNITDELIVERYWITHPKGITM
EXIDV = HANDLINGUNITEXTERNALID
EXIDA = HANDLINGUNITEXTERNALIDTYPE
POSNR_GEN = HANDLINGUNITGENDELIVERYITEM
VEGR1 = HANDLINGUNITGROUP1
VEGR2 = HANDLINGUNITGROUP2
VEGR3 = HANDLINGUNITGROUP3
VEGR4 = HANDLINGUNITGROUP4
VEGR5 = HANDLINGUNITGROUP5
HOEHE = HANDLINGUNITHEIGHT
VENUM = HANDLINGUNITINTERNALID
STATUS = HANDLINGUNITINTERNALSTATUS
KZGVH = HANDLINGUNITISCLOSED
ERLKZ = HANDLINGUNITISCOMPLETE
LAENG = HANDLINGUNITLENGTH
UEVEL = HANDLINGUNITLOWERLEVELREFER
MAVOL = HANDLINGUNITMAXVOLUME
MAGEW = HANDLINGUNITMAXWEIGHT
NTVOL = HANDLINGUNITNETVOLUME
VPOBJKEY = HANDLINGUNITPACKINGOBJECTKEY
VPOBJ = HANDLINGUNITPACKINGOBJECTTYPE
EXIDV2 = HANDLINGUNITSECONDEXTERNALID
HU_SYSTEM = HANDLINGUNITSTOCKMGMTTYPE
TAVOL = HANDLINGUNITTAREVOLUME
VOLEH = HANDLINGUNITTAREVOLUMEUNIT
TARAG = HANDLINGUNITTAREWEIGHT
GEWEI = HANDLINGUNITTAREWEIGHTUNIT
VOLTO = HANDLINGUNITVOLUMETOLERANCE
GEWTO = HANDLINGUNITWEIGHTTOLERANCE
GEWFX = HANDLINGUNITWEIGHTVOLUMEISFIX
BREIT = HANDLINGUNITWIDTH
ADGE_DG = HAZARDOUSSUBSTANCEINDICATOR
AEDAT = LASTCHANGEDATE
AENAM = LASTCHANGEDBYUSER
AEZET = LASTCHANGETIME
LSTEL = LOADINGPOINT
MANDT = MANDT
NTGEW = NETWEIGHT
VHILM = PACKAGINGMATERIAL
VELTP = PACKAGINGMATERIALCATEGORY
MAGRV = PACKAGINGMATERIALGROUP
VHART = PACKAGINGMATERIALTYPE
PACKVORSCHR = PACKINGINSTRUCTION
PACKVORSCHR_ST = PACKINGINSTRUCTIONSTATUS
ZUL_AUFL = PACKINGINSTRUCTMAXLOADQUANTITY
LABELTYP = PACKINSTRUCTEXTLABELNOTPRINTED
WERKS = PLANT
PSTYV = SALESDOCUMENTITEMCATEGORY
VKORG = SALESORGANIZATION
VSTEL = SHIPPINGPOINT
HANDLE = SOURCEHANDLINGUNITUUID
LGORT = STORAGELOCATION
MEABM = UNITOFMEASUREDIMENSION
VOLEH_MAX = VOLUMEUNIT
LGNUM = WAREHOUSE
GEWEI_MAX = WEIGHTUNIT
