VEPO = I_HANDLINGUNITITEM
CHARG = BATCH
CUOBJ = CONFIGURATIONOBJECT
ALTME = HANDLINGUNITALTUNITOFMEASURE
POSNR_GEN = HANDLINGUNITGENDELIVERYITEM
WDATU = HANDLINGUNITGOODSRECEIPTDATE
QPLOS = HANDLINGUNITINSPECTLOTNUMBER
VENUM = HANDLINGUNITINTERNALID
VEPOS = HANDLINGUNITITEM
KZBEI = HANDLINGUNITITEMISSUPPLEMENT
HANDLE_VEPO = HANDLINGUNITITEMUUID
UNVEL = HANDLINGUNITNESTEDINTERNALID
VEANZ = HANDLINGUNITNROFAUXPACKGMAT
ANZSN = HANDLINGUNITNUMBEROFSERIALNUMB
VEMNG = HANDLINGUNITQUANTITY
VEMEH = HANDLINGUNITQUANTITYUNIT
POSNR = HANDLINGUNITREFDOCUMENTITEM
VBELN = HANDLINGUNITREFERENCEDOCUMENT
VELIN = HANDLINGUNITTYPEOFCONTENT
SOBKZ = INVENTORYSPECIALSTOCKTYPE
MANDT = MANDT
MATNR = MATERIAL
P_MATERIAL = MATERIALBYCUSTOMER
WERKS = PLANT
PSTYV = SALESDOCUMENTITEMCATEGORY
VBTYP = SDDOCUMENTCATEGORY
SERAIL = SERIALNUMBERPROFILE
VFDAT = SHELFLIFEEXPIRATIONDATE
SONUM = SPECIALSTOCKNUMBER
SGT_SCAT = STOCKSEGMENT
LGORT = STORAGELOCATION
