VEPO = I_HANDLINGUNITITEMTP
CHARG = BATCH
ALTME = HANDLINGUNITALTUNITOFMEASURE
WDATU = HANDLINGUNITGOODSRECEIPTDATE
VEPOS = HANDLINGUNITITEM
VEANZ = HANDLINGUNITNROFAUXPACKGMAT
ANZSN = HANDLINGUNITNUMBEROFSERIALNUMB
VEMNG = HANDLINGUNITQUANTITY
VEMEH = HANDLINGUNITQUANTITYUNIT
VBELN = HANDLINGUNITREFERENCEDOCUMENT
VELIN = HANDLINGUNITTYPEOFCONTENT
MATNR = MATERIAL
WERKS = PLANT
SERAIL = SERIALNUMBERPROFILE
VFDAT = SHELFLIFEEXPIRATIONDATE
LGORT = STORAGELOCATION
