WBGT = ZR_TRDGDOCRELTDDOCINFO
CHARG = BATCH
ERNAM = CREATEDBYUSER
ERDAT = CREATIONDATE
WERKS = PLANT
MATNR = PRODUCT
MATKL = PRODUCTGROUP
PUR_QUAN = PURCHASINGDOCUMENTORDERQTY
LGORT = STORAGELOCATION
TKONN = TRADINGDOCUMENT
TPOSN = TRADINGDOCUMENTITEM
BUSINESS_STEP = TRADINGPROCESSBUSINESSSTEP
ERROR_TEW = TRADINGPROCESSERRORFLAG
PRE_STEP = TRADINGPROCESSPREVIOUSSTEP
ORIGINAL_STEP = TRADINGPROCESSSOURCESTEP
TEW_MODE = TRADINGPROCESSVARIANTMODE
TEW_TYPE = TRADINGPROCESSVARIANTTYPE
SCENARIO = TRDGDOCBUSINESSSCENARIO
REL_FLAG = TRDGDOCDELTNISRLVT
GUID = TRDGDOCDGTLSGNTRPROCID
DI_STATUS = TRDGDOCDIFFINVCSTATUS
MOVE_TYPE_CODE = TRDGDOCDRCTNOFGDSCSHFLW
TKONN_EX = TRDGDOCEXTERNALIDENTIFIER
HAS_SHADOW_TC = TRDGDOCHASSHDWCONTR
COMPLETE = TRDGDOCITEMISCOMPLETE
TAX_EXP_SUM = TRDGDOCITMEXPENSETAXAMOUNT
EXP_NRP = TRDGDOCNONRCOVBLPURGEXPNAMT
EXP_NRS = TRDGDOCNONRCOVBLSLSEXPNAMT
GROUP_CODE = TRDGDOCPRCGPAYTEVTGRPVALUE
SEND_COMPL = TRDGDOCPROCCOMPLTNCAT
EXP_RP = TRDGDOCPURGEXPNAMT
PUR_UOM = TRDGDOCPURGQUANTITYUNIT
UMZ = TRDGDOCQTNDNMNTR
UMN = TRDGDOCQTYNMRTR
EXP_RS = TRDGDOCRCOVBLSLSEXPNAMT
VBELN = TRDGDOCRELATEDDOCUMENT
POD_QUAN = TRDGDOCRELTDBILLEDQUANTITY
CURR_VAL = TRDGDOCRELTDDOCCURRENCY
DEL_FLAG = TRDGDOCRELTDDOCDELTNCAT
RATE_VAL = TRDGDOCRELTDDOCEXCHANGERATE
CURR_EXP = TRDGDOCRELTDDOCEXPNCURRENCY
RATE_EXP = TRDGDOCRELTDDOCEXPNEXCHRATE
RET_ITEM = TRDGDOCRELTDDOCHASRETITM
VALUE = TRDGDOCRELTDDOCITEMAMOUNT
TAX_VAL = TRDGDOCRELTDDOCITEMTAXAMT
EXP_SUM = TRDGDOCRELTDDOCITMTOTEXPNAMT
BWTAR = TRDGDOCRELTDDOCITMVALNTYPE
OWN_QUAN = TRDGDOCRELTDDOCQUANTITY
VALUE_COST = TRDGDOCRELTDDOCSTKAMT
AV_DATE = TRDGDOCRELTDDOCUMENTDATE
POSNR = TRDGDOCRELTDDOCUMENTITEM
GJAHR = TRDGDOCRELTDDOCUMENTYEAR
UNIT_DOC = TRDGDOCRELTDDOCUOM
VAL_TYPE = TRDGDOCRELTDDOCVALNCAT
PRED_DOC_BUKRS = TRDGDOCRELTDPRECDGDOCCOCODE
PRED_DOC_NR = TRDGDOCRELTDPRECDGDOCUMENT
PRED_DOC_YEAR = TRDGDOCRELTDPRECDGDOCYEAR
PRED_ITEM = TRDGDOCRELTDPRECDGITEM
SIDE = TRDGDOCRELTDSIDECAT
PRED_DOC_TYPE = TRDGDOCRLVTPRECDGDOCTYPE
POD_UOM = TRDGDOCSLSQUANTITYUNIT
DOC_TYPE = TRDGRELTDDOCCATEGORY
RUUID = TRDGRELTDDOCUMENTUUID
