source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               icons/,\
               resources/
qualifier = context
src.includes = META-INF/,\
               build.properties,\
               icons/,\
               plugin.xml,\
               resources/,\
               src/
